# TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS

Environment Data is not always stable or stationary over time or space and is frequently subjected to sustained or cyclical change to the affecting factors. These concepts will help us understand the temporal effects better; 

**Temporal Trends: ** refer to changes in a variable or phenomenon over time. Consider monitoring soil nitrogen levels in agricultural field over several years. There might be temporal rise of nitrogen immediately after application of nitrogen-based fertilizer and return back to almost the average state after time. Although there might be a general increase in soil nitrogen levels, but they won't match the immediate spikes after fertilizer application.

**Autocorrelation** or **serial correlation: ** is the
correlation between data values of the same variable. **Positive autocorrelation** means that values close in time/space tend to be similar while **negative autocorrelation** means that they tend to differ. 

**Monotonic trend: ** this is a trend that is in one direction, either constantly upward or downwards. A good example are the levels of carbon dioxide(CO2) concentrations in the atmosphere, they have been consistently rising due to industrial activities and deforestation. 

**Cyclic or Seasonal trend** refer to patterns that repeat at regular intervals such as daily ,hourly or annually. These trends are usually affected by natural cycles, human activities or climatic conditions. For instance, these trends are evident in phosphorous levels in water bodies that might increase during rainy seasons due agricultural runoff and decline during dry seasons. 

When testing for autocorrelation and temporal effects the data samples are assumed to have values that are independent or uncorrelated, and identically or similarly distributed. The data are said to be *autocorrelated* or *serially correlated* when this assumption is violated.

These are the tests that are used to check for autocorrelation: 

- *Sample Autocorrelation Function(ACF): * used for a single time series where data is normally distributed. 

- *Rank von Neumann ratio test* used when the data samples evidence of nonnormality. 

- *The complete block design ANOVA or Friedman test* is used for multiple different data samples for instance testing the concentration of ground water contaminant from multiple monitoring wells at a site. 

## Test for Autocorrelation Using the Sample Autocorrelation Function

Before testing for autocorrelation using the ACF method, the data sample should be; 

* normally distributed. 
* stationary(that is, not trending). 
* free of outliers.
* containing atleast 10 to 12 observations.

... And here is how ACf is computed. 

1. Arrange the data in lagged data pairs ($x_{i}, x_{i + k}$), for $i$ = 1, 2, ....($n-k$), where;

  i. $n$ is the size of the data samples(number of data values therein). 
  ii. $k$ is the lag. i.e number of sampling events dates separating one data value in the pair from the second value. For instance a lag of 1 shows that the two value pairs were collected in consecutive time intervals(e.g days) while lag shows that the data value pairs were collected every each time interval


2. Calculate the sample Autocorrelation coefficient $$r_k = {{\sum^{n-k}_{i=1}(x_i-x^!)(x_{i+k}- x^!)}\over{\sum^n_{i=1}(x_i - x^!)^2}}$$ where; 
  
  - $n$ is the data sample size.
  - $k$ is the lag
  - $x^!$ is the data sample mean
  - $x_{i}, x_{i + k}$ are the components of the data pairs formed based on the lag. 

3. If $k$ = 1, the sample autocorrelation coefﬁcient, $r_1$ is referred to as the ﬁrst order sample autocorrelation coefﬁcient. If $k$ = 2, $r_2$ is the second order coefﬁcient, and so on.

4. Lets breakdown the possible results of autocorrelation; 

  $r_0$ = 1: Autocorrelation at lag 0 is always one because a value is perfectly correlated with itself. 
  Random Data: if the data is random, most autocorrelation coefficients will be close to zero, and will decrease further as the lag increases. 
  Autocorrelated Data: If there's autocorrelation, some coefficients($r_k$) will be significantly larger than zero, but their strength decreases with higher lags. 
  Trend in data: If there is a trend, coefficients wont diminish, showing persistent correlation. 
  
As a summary, the normally distributed data, $r_k$ should be close to zero if there is no correlation. At a 95% confidence level, autocorrelation is insignificant if no $r_k$ exceeds the threshold $2\over{\sqrt{n}}$. There result of each autocorrelation are therefore plotted in a correlogram and the confidence limits are show as the horizontal lines.

<span style="color: orange;">**Try it!**</span> 








