<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 HYPOTHESIS TESTING | Ecological Analysis</title>
  <meta name="description" content="Chapter 2 HYPOTHESIS TESTING | Ecological Analysis" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 HYPOTHESIS TESTING | Ecological Analysis" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 HYPOTHESIS TESTING | Ecological Analysis" />
  
  
  

<meta name="author" content="Basim Alsaedi" />


<meta name="date" content="2024-11-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="test-for-autocorrelation-and-temporal-effects.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SHORT TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUCTION</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-distributions"><i class="fa fa-check"></i><b>1.1</b> Data Distributions</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#types-of-distribution"><i class="fa fa-check"></i><b>1.1.1</b> Types of Distribution</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#hands-on-exercises"><i class="fa fa-check"></i><b>1.2</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>2</b> HYPOTHESIS TESTING</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-tests"><i class="fa fa-check"></i><b>2.2</b> Parametric tests</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-single-sample-test"><i class="fa fa-check"></i><b>2.2.1</b> Parametric single-sample test</a></li>
<li class="chapter" data-level="2.2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-two-sample-test"><i class="fa fa-check"></i><b>2.2.2</b> Parametric two-sample test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-test"><i class="fa fa-check"></i><b>2.3</b> Nonparametric test</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-sample-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.1</b> Nonparametric One-Sample Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="2.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-two-sample-paired-sign-test-and-paired-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.2</b> Nonparametric two-sample paired sign test and paired Wilcoxon Signed Rank Test</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-one-way-anova"><i class="fa fa-check"></i><b>2.4.1</b> Parametric One-Way ANOVA</a></li>
<li class="chapter" data-level="2.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-way-anova-kruskal-wallis-test"><i class="fa fa-check"></i><b>2.4.2</b> Nonparametric One-Way ANOVA (Kruskal-Wallis Test)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hands-on-exercise"><i class="fa fa-check"></i><b>2.5</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html"><i class="fa fa-check"></i><b>3</b> TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS</a>
<ul>
<li class="chapter" data-level="3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#test-for-autocorrelation-using-the-sample-autocorrelation-function"><i class="fa fa-check"></i><b>3.1</b> Test for Autocorrelation Using the Sample Autocorrelation Function</a></li>
<li class="chapter" data-level="3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#an-example-on-site-wide-temporal-effects"><i class="fa fa-check"></i><b>3.2</b> An Example on Site-Wide Temporal Effects</a></li>
<li class="chapter" data-level="3.3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#tests-for-trend"><i class="fa fa-check"></i><b>3.3</b> TESTS FOR TREND</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#parametric-test-for-trends---simple-linear-regression"><i class="fa fa-check"></i><b>3.3.1</b> Parametric Test for Trends - Simple Linear Regression</a></li>
<li class="chapter" data-level="3.3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#nonparametric-test-for-trends"><i class="fa fa-check"></i><b>3.3.2</b> Nonparametric Test for Trends</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#hands-on-exercises-1"><i class="fa fa-check"></i><b>3.4</b> <span style="color: green;"><strong>Hands-On Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html"><i class="fa fa-check"></i><b>4</b> CORRELATION, COVARIANCE, GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> INTRODUCTION</a></li>
<li class="chapter" data-level="4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#correlation-and-covariance"><i class="fa fa-check"></i><b>4.2</b> CORRELATION AND COVARIANCE</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>4.2.1</b> Pearson’s Correlation Coefficient</a></li>
<li class="chapter" data-level="4.2.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#spearmans-and-kendalls-correlaton-coefficients"><i class="fa fa-check"></i><b>4.2.2</b> Spearman’s and Kendall’s Correlaton Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#covariance"><i class="fa fa-check"></i><b>4.3</b> COVARIANCE</a></li>
<li class="chapter" data-level="4.4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#geostatistics"><i class="fa fa-check"></i><b>4.4</b> GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#variogram-modelling"><i class="fa fa-check"></i><b>4.4.1</b> Variogram Modelling</a></li>
<li class="chapter" data-level="4.4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#kriging"><i class="fa fa-check"></i><b>4.4.2</b> Kriging</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html"><i class="fa fa-check"></i><b>5</b> LINEAR REGRESSION ANALYSIS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#simple-linear-regression-analysis"><i class="fa fa-check"></i><b>5.1</b> Simple Linear Regression Analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#empirical-model-building-regression-analysis"><i class="fa fa-check"></i><b>5.1.1</b> Empirical model-building-regression analysis</a></li>
<li class="chapter" data-level="5.1.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#interpreting-the-regression-results"><i class="fa fa-check"></i><b>5.1.2</b> Interpreting the regression results</a></li>
<li class="chapter" data-level="5.1.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#r-squared-and-adjusted-r-squared"><i class="fa fa-check"></i><b>5.1.3</b> R-squared and Adjusted R-Squared</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-versus-generalized-linear-model"><i class="fa fa-check"></i><b>5.2</b> Data transformation versus generalized linear model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-approach-log-transformation"><i class="fa fa-check"></i><b>5.2.1</b> Data Transformation Approach (Log Transformation)</a></li>
<li class="chapter" data-level="5.2.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#generalized-linear-modelglm"><i class="fa fa-check"></i><b>5.2.2</b> Generalized Linear Model(GLM)</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#multiple-linear-regression-mlr-model"><i class="fa fa-check"></i><b>5.3</b> Multiple Linear Regression (MLR) model</a></li>
<li class="chapter" data-level="5.4" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#hands-on-exercise-1"><i class="fa fa-check"></i><b>5.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html"><i class="fa fa-check"></i><b>6</b> CONVENTIONAL AND PROBABILISTIC RISK ASSESSMENT</a>
<ul>
<li class="chapter" data-level="6.1" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#introduction-3"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#conventional-or-point-risk-estimation"><i class="fa fa-check"></i><b>6.2</b> Conventional or Point Risk Estimation</a></li>
<li class="chapter" data-level="6.3" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#probabilistic-risk-assessment-using-monte-carlo-simulation"><i class="fa fa-check"></i><b>6.3</b> Probabilistic Risk Assessment Using Monte Carlo Simulation</a></li>
<li class="chapter" data-level="6.4" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#practical-exercise"><i class="fa fa-check"></i><b>6.4</b> <span style="color: green;"><strong>Practical Exercise</strong></span></a></li>
<li class="chapter" data-level="6.5" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#hands-on-exercise-2"><i class="fa fa-check"></i><b>6.5</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>7</b> Datasets</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ecological Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hypothesis-testing" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> HYPOTHESIS TESTING<a href="hypothesis-testing.html#hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-1" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Introduction<a href="hypothesis-testing.html#introduction-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hypothesis testing is a standard statistical procedure for deciding between two competing alternatives or scenarios, based on evidence presented by a data sample collected for the purpose of conducting the test. Most descriptive statistics such as mean, median and standard deviation are usually computed from data samples which may vary with the whole population. For instance, we want to find the concentration of hexavalent chromium, a human carcinogen, in soil. We will collect random 20 samples. The average concentration of the carcinogen from the collected samples will at most vary with the average concentration in the entire land, that’s where <strong>hypothesis testing</strong> comes in.</p>
<p><strong>Basic terminology and procedure for hypothesis testing</strong></p>
<p>There is a need to understand the basic terms before diving deep into the process of hypothesis testing. If we have historical data, the presence of a trend must be established and below are the assumptions that should be made prior to conducting hypothesis testing;</p>
<ol style="list-style-type: lower-roman">
<li>The data is assumed to belong to a specified distribution(typically normal distribution).</li>
<li>The data has a stable or stationary trend(free from of temporal or spatial trend).</li>
<li>There are no unusual observations or outliers.</li>
</ol>
<p>The hypothesis testing that involves data samples that holds the above assumptions is described as <strong>parametric hypothesis testing</strong>. Otherwise, if the above assumptions are not met, the test is known as <strong>non-parametric hypothesis testing</strong>.</p>
<ul>
<li><p><strong>Null hypothesis</strong> (<span class="math inline">\(H_0\)</span>): Is a statement of the presumed default or baseline condition. In this case the null hypothesis is that there is no difference between the carcinogenic concentration is below the allowed limit.</p></li>
<li><p><strong>Alternate hypothesis</strong> (<span class="math inline">\(H_1\)</span> or <span class="math inline">\(H_A\)</span>): is the inverse or the opposite of the null hypothesis. Alternate hypothesis contradicts the statement of the presumed default. In this case, the alternate hypothesis states that the carcinogenic level is above the allowed limit.</p></li>
</ul>
<p>The evidence produced by the sample after conducting hypothesis testing can either refute or support the null hypothesis.</p>
<ul>
<li><p>The <strong>one-tailed (One-Sided) Hypothesis</strong> test checks for an effect in only one direction. In our case, we test if the carcinogen levels exceed the allowed limit(right side). Alternatively, it can be checked of it is below the allowed limits (left-sided).</p></li>
<li><p><strong>Upper-Tailed Hypothesis Test</strong> is the same as the right one-tailed hypothesis test that checks if the value of interest exceed the null hypothesis value</p></li>
<li><p><strong>Lower-Tailed Hypothesis Test</strong> is the left one-tailed hypthesis test where it checks if the value of interest is below the null hypothesis value. In our case the allowed limit for carcinogens in soil.</p></li>
<li><p><strong>Two-Tailed Hypothesis Test</strong> checks for the effect in both directions. In our we can change to find if the carcinogen levels are below or above the allowed limit.</p></li>
<li><p><strong>T-Value</strong> is the test statistic calculated from the sample data to determine how far the sample mean is from the hypothesized mean, in terms of standard error.</p></li>
<li><p><strong>Critical T-Value</strong> is the threshold value for the t-distribution that corresponds to the significance level. If the t-value exceeds the critical t-value, the null hypothesis is rejected.</p></li>
<li><p><strong>Significant level</strong>(<span class="math inline">\(\alpha\)</span>) is the probability threshold for rejecting the null hypothesis, usually set to 0.05(5%).</p></li>
</ul>
<p>In most cases if the probability of observing the test statistic (p-value) is less than 0.005, the null hypothesis is rejected.</p>
<ul>
<li><strong>Degrees of Freedom(df)</strong> are the number of independent values in the data sample that are free to vary when calculating a statistic.</li>
</ul>
<p>In most cases <strong>df</strong> is calculated as <span class="math display">\[df = n - 1\]</span></p>
<p>where <span class="math inline">\(n\)</span> represents the sample size(count).</p>
<p>In our cases where we have 20 samples therefore <span class="math inline">\(df = 20 -1\)</span> and the degree of freedom will be 19</p>
<ul>
<li><strong>P-Value</strong> indicates the probability of obtaining a test statistic at least as extreme as the observed one, assuming the null hypothesis is true.</li>
</ul>
<p>Below are the steps taken in hypothesis testing;</p>
<ol style="list-style-type: lower-roman">
<li>Formulate the null and alternate hypothesis.</li>
<li>Assume the null hypothesis is true and compute a test statistic that follows a known distribution.</li>
<li>Calculate a test statistic value based on the data sample which follows a known distribution and determine the critical value for chosen distribution at a given significance level.</li>
<li>Compare the test statistic to the critical value to assess the plausibility of the null hypothesis. For symmetrical distributions(e.g t, normal), critical values are located on;</li>
</ol>
<ul>
<li><em>upper-tailed test</em>: positive side of the distribution</li>
<li><em>lower-tailed test</em>: negative side of the distribution</li>
<li><em>two-tailed test</em>: both sides, with equal magnitude</li>
</ul>
<ol start="22" style="list-style-type: lower-alpha">
<li>Calculate the p-value to find how the probability of obtaining a test statistic more extreme than the observed value.</li>
</ol>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>To get the steps above clear, lets work on an example. This is an hypothetical problem where a regulatory body sets that the acceptable phosphorous concentration in a lake at <strong>1.5mg/L</strong>. 30 sample measurements were collected at different locations in the lake. The objective was to determine if the phosphorous levels are significantly higher than the allowed limit.</p>
<p>Lets simulate the data.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="hypothesis-testing.html#cb80-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># for reproducibility</span></span>
<span id="cb80-2"><a href="hypothesis-testing.html#cb80-2" tabindex="-1"></a></span>
<span id="cb80-3"><a href="hypothesis-testing.html#cb80-3" tabindex="-1"></a>phosphorous_levels <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">30</span>,</span>
<span id="cb80-4"><a href="hypothesis-testing.html#cb80-4" tabindex="-1"></a>                            <span class="at">mean =</span> <span class="fl">1.7</span>,</span>
<span id="cb80-5"><a href="hypothesis-testing.html#cb80-5" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<ul>
<li><p>Formulate the null hypothesis</p>
<ul>
<li>Null Hypothesis(<span class="math inline">\(H_0\)</span>): <span class="math inline">\(\mu\)</span> &lt; 1.5 - phosphorous levels are within the acceptable levels.</li>
<li>Alternate Hypothesis (<span class="math inline">\(H_1\)</span>): <span class="math inline">\(\mu\)</span> &gt; 1.5 - phosphorous levels exceed the acceptable limit.</li>
</ul></li>
</ul>
<p>This is a right-sided(one-sided) test since we are only interested in detecting an increase in phosphorous levels</p>
<ul>
<li><p>We use a one-sample t-test since the population data standard deviation is unknown, and the sample size is small(n=30). The formula for t-statistic is calculated as; <span class="math display">\[t = {{\overline{x} - \mu_0}\over{s/\sqrt{n}}}\]</span>
Where:</p>
<ul>
<li><span class="math inline">\(\overline{x}\)</span> is the sample mean.</li>
<li><span class="math inline">\(\mu_0\)</span> is the population mean under null hypothesis (1.5mg/L)</li>
<li><span class="math inline">\(s\)</span> is the sample standard deviation.</li>
<li><span class="math inline">\(n\)</span> is the sample size.</li>
</ul></li>
<li><p>Perform the one-sample t-test</p></li>
</ul>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="hypothesis-testing.html#cb81-1" tabindex="-1"></a><span class="co"># One sample t-test </span></span>
<span id="cb81-2"><a href="hypothesis-testing.html#cb81-2" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(phosphorous_levels, </span>
<span id="cb81-3"><a href="hypothesis-testing.html#cb81-3" tabindex="-1"></a>                        <span class="at">mu =</span> <span class="fl">1.5</span>,</span>
<span id="cb81-4"><a href="hypothesis-testing.html#cb81-4" tabindex="-1"></a>                        <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span>
<span id="cb81-5"><a href="hypothesis-testing.html#cb81-5" tabindex="-1"></a></span>
<span id="cb81-6"><a href="hypothesis-testing.html#cb81-6" tabindex="-1"></a><span class="co"># Display the results </span></span>
<span id="cb81-7"><a href="hypothesis-testing.html#cb81-7" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  phosphorous_levels
## t = 5.3201, df = 29, p-value = 5.21e-06
## alternative hypothesis: true mean is greater than 1.5
## 95 percent confidence interval:
##  1.629713      Inf
## sample estimates:
## mean of x 
##  1.690579</code></pre>
<ul>
<li><p>Determine the critical value</p>
<ul>
<li>For the right-tailed test at a 5% significance levels(<span class="math inline">\(alpha\)</span>=0.05), the critical value is the t-value that corresponds to the top 5% of the t-distribution. The <code>qt()</code> function will be used to calculate this; <span class="math display">\[t_{critical} = qt(1-\alpha, df = n - 1)\]</span></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="hypothesis-testing.html#cb83-1" tabindex="-1"></a>critical_t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="fu">length</span>(phosphorous_levels) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb83-2"><a href="hypothesis-testing.html#cb83-2" tabindex="-1"></a></span>
<span id="cb83-3"><a href="hypothesis-testing.html#cb83-3" tabindex="-1"></a>critical_t</span></code></pre></div>
<pre><code>## [1] 1.699127</code></pre>
<p>The t-statistic is greater than the critical t therefore the null hypothesis is rejected. Lets confirm this by also computing the p_value</p>
<ul>
<li>Compute the p-value</li>
</ul>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="hypothesis-testing.html#cb85-1" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> t_test_result<span class="sc">$</span>p.value</span>
<span id="cb85-2"><a href="hypothesis-testing.html#cb85-2" tabindex="-1"></a>p_value</span></code></pre></div>
<pre><code>## [1] 5.210072e-06</code></pre>
<p>The null hypothesis is rejected as the p_value is less than 0.05. Therefore, we make conclusion that the phosphorous levels in the lake exceed the acceptable levels.</p>
</div>
<div id="parametric-tests" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Parametric tests<a href="hypothesis-testing.html#parametric-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As described before parametric tests rely on the assumptions that the data follows a known distribution (commonly the normal distribution) and it should be free of major outliers. In case where the test requires the data to follow a normal distribution, if the sample size is small it must follow a normal distribution while for larger sample size (e.g n≥30) the <strong>Central Limit Theorem</strong> allows the researchers to approximate normality even of the data is not perfectly normal</p>
<div id="parametric-single-sample-test" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Parametric single-sample test<a href="hypothesis-testing.html#parametric-single-sample-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This type of test is used to determine whether the mean of a single sample is significantly different from a known or hypothesized population mean. It assumes that the sample data comes from a population that follows a normal distribution (or has a large enough sample size to approximate normality).</p>
<p>The <strong>main objective</strong> of this test is to <em>test whether the sample mean differs significantly from a reference or target value, such as an industry standard, a population average, or a theoretical expectation in hypothesis testing</em></p>
<p>These are the steps taken for One-Sample T-test;</p>
<ol style="list-style-type: decimal">
<li><em>State the Hypotheses:</em></li>
</ol>
<ul>
<li><strong>Null Hypothesis</strong>(<span class="math inline">\(H_0\)</span>): The sample mean equals the population mean (<span class="math inline">\(\mu = \mu_0\)</span>)</li>
<li><strong>Alternate Hypothesis</strong>(<span class="math inline">\(H_A\)</span>): The sample mean is different from the population mean(<span class="math inline">\(\mu \neq \mu_0\)</span>)</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li><em>Compute the test statistic</em></li>
</ol>
<p>The formula for test statistic is <span class="math display">\[t = {{\overline x - \mu_0}\over{s/\sqrt n}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\overline x\)</span>: is the sample mean</li>
<li><span class="math inline">\(\mu_0\)</span>: is the hypothesized population mean</li>
<li><span class="math inline">\(s\)</span>: is the sample standard deviation</li>
<li><span class="math inline">\(n\)</span>: is the sample size</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Determine the degree of freedom as <span class="math inline">\(df = n- 1\)</span></li>
<li>Compare <span class="math inline">\(t\)</span> to critical value or use p-value.</li>
</ol>
</div>
<div id="parametric-two-sample-test" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Parametric two-sample test<a href="hypothesis-testing.html#parametric-two-sample-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Lets understand what is two-sample test, before specifically diving into the <strong>parametric two sample test</strong>; Two-sample tests are essential statistical tools used to compare two different populations to determine if there are significant differences between them. These tests are widely applied in ecology to compare environmental factors such as contaminant levels, species diversity, or soil nutrient concentrations across different locations or time periods.</p>
<p>Two-sample tests help us compare the means, medians, or other characteristics of two groups. For example, scientists might want to know if the average soil arsenic concentration in an industrial area is higher than that in a nearby natural reserve. To perform these tests, data must be collected from both groups being compared.</p>
<p>Here are the assumptions of two-sample tests;</p>
<ol style="list-style-type: decimal">
<li><em>Independence of Data Values:</em> Data points should not influence each other.</li>
<li><em>No trends in data:</em> data should not show patterns over time for instance increasing and decreasing trends. If trends exist, adjustments such as pairing or deseasonalization should be considered.</li>
</ol>
<p>In this case, we are focusing on the parametric tests – a parametric two-sample test is carried when the data follows a normal distribution. There are two types of parametric two-sample tests; <em>independent</em> and <em>paired sample tests</em>.</p>
<ol style="list-style-type: decimal">
<li><strong>Independent Two-Sample Test</strong></li>
</ol>
<p>These tests are used when the two groups being compared have no inherent connection. For example:</p>
<ul>
<li>Comparing soil arsenic levels up-gradient vs. down-gradient of an industrial facility.</li>
<li>Measuring PCB concentrations upstream and downstream of a river.</li>
</ul>
<p>In these cases, since the samples are collected from different locations without any relationship, an independent test is appropriate. These are the steps taken when carrying out independent tests;</p>
<ul>
<li>Calculate the test statistic based on the difference between sample means.</li>
<li>Compare the test statistic with a critical value from the t-distribution.</li>
<li>If the test statistic is extreme or the p-value is less than the significance level (e.g., 0.05), reject the null hypothesis.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li><strong>Paired Two-Sample Tests</strong></li>
</ol>
<p>Paired tests are used when the samples are related or dependent on each other. This often happens when measurements are taken from the same location at different times. Examples include:</p>
<ul>
<li>Before and After Cleanup: Measuring soil contaminant levels at a site before and after remediation.</li>
<li>Duplicate Sample Analysis: Sending identical samples to two different laboratories to assess the consistency of results.</li>
</ul>
<p>Before carrying out paired two-sample test it is assumed that the data is paired(each observation in one group corresponds to an observation in the other group), differences between pairs should follow a normal distribution and no extreme outliers should be present.</p>
<p>Here are the steps taken when performing paired two-sample test;</p>
<ul>
<li>Calculate the differences between paired observations.</li>
<li>Compute the mean and standard deviation of the differences</li>
<li>Calculate the t-statistic</li>
<li>Compare the test statistic with the critical value or p-value</li>
<li>If the test statistic is extreme or the p-value is less than the significance level, reject the null hypothesis.</li>
</ul>
<p>Here is the formula for calculating the t-statistic; <span class="math display">\[{t_0} = {{\overline D}\over{S_D/\sqrt n}}\]</span></p>
<p>where;</p>
<ul>
<li><span class="math inline">\(\overline D\)</span> and <span class="math inline">\(S_D\)</span> is the mean and standard deviation of the <em>differences</em> between the data samples of the two populations</li>
<li><span class="math inline">\(n\)</span> is the sample size</li>
</ul>
<p>The null hypothesis <span class="math inline">\(H_0\)</span> is that the population mean difference between the two populations, $_D $ is zero</p>
<p>Imagine an ecologist wants to determine if the cleanup of an industrial site has effectively reduced contaminant levels. By comparing pre- and post-cleanup soil samples at the same locations, they can assess the success of remediation efforts using a paired two-sample test. Similarly, comparing background levels with site concentrations using an independent two-sample test can help identify pollution sources.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Arsenic contamination in groundwater is a significant ecological and public health concern. Prolonged exposure to arsenic can lead to severe health issues, including cancer and organ damage. To evaluate arsenic contamination in different water sources, we will apply parametric hypothesis tests. You will be provided with <code>arsenic.csv</code> that will be used to analyze the arsenic concentrations in different sources by parametric tests.</p>
<ul>
<li><p>let’s test whether arsenic concentrations at Site A exceed the WHO limit of <span class="math inline">\(10 \mu g/L\)</span> using single-sample test, First, foumulate the null and alternate hypothesis;</p>
<ul>
<li>Null Hypothesis (H₀): Mean concentration = <span class="math inline">\(10 \mu g/L\)</span></li>
<li>Alternative Hypothesis (H₁): Mean concentration &gt; <span class="math inline">\(10 \mu g/L\)</span>(one-tailed test)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="hypothesis-testing.html#cb87-1" tabindex="-1"></a><span class="co"># Load the data </span></span>
<span id="cb87-2"><a href="hypothesis-testing.html#cb87-2" tabindex="-1"></a>arsenic_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/arsenic.csv&quot;</span>)</span>
<span id="cb87-3"><a href="hypothesis-testing.html#cb87-3" tabindex="-1"></a></span>
<span id="cb87-4"><a href="hypothesis-testing.html#cb87-4" tabindex="-1"></a>site_A <span class="ot">=</span> <span class="fu">c</span>(arsenic_data<span class="sc">$</span>Site_A)</span>
<span id="cb87-5"><a href="hypothesis-testing.html#cb87-5" tabindex="-1"></a></span>
<span id="cb87-6"><a href="hypothesis-testing.html#cb87-6" tabindex="-1"></a><span class="co"># Single sample t.test</span></span>
<span id="cb87-7"><a href="hypothesis-testing.html#cb87-7" tabindex="-1"></a><span class="fu">t.test</span>(site_A, <span class="at">mu =</span> <span class="dv">10</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  site_A
## t = 5.2797, df = 14, p-value = 5.819e-05
## alternative hypothesis: true mean is greater than 10
## 95 percent confidence interval:
##  11.5359     Inf
## sample estimates:
## mean of x 
##  12.30477</code></pre>
<p>The p-value is less than 0.05 therefore the null hypothesis is rejected. It is concluded that the arsenic concentration in Site A exceeds the WHO limit.</p>
<ul>
<li><p>Apply parametric independent two-sample test to compare arsenic levels between two independent water sources (Site A vs. Site B). Formulating the hypothesis;</p>
<ul>
<li>Null hypothesis: Mean concentration at Site A = Mean concentration at Site B.</li>
<li>Alternate hypothesis: Mean concentration at Site A ≠ Mean concentration at Site B.</li>
</ul></li>
</ul>
<p>We assume that both samples are <strong>normally distributed</strong> and have <strong>equal variances</strong>.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="hypothesis-testing.html#cb89-1" tabindex="-1"></a><span class="co"># Declare variables </span></span>
<span id="cb89-2"><a href="hypothesis-testing.html#cb89-2" tabindex="-1"></a>site_A <span class="ot">=</span> <span class="fu">c</span>(arsenic_data<span class="sc">$</span>Site_A)</span>
<span id="cb89-3"><a href="hypothesis-testing.html#cb89-3" tabindex="-1"></a>site_B <span class="ot">=</span> <span class="fu">c</span>(arsenic_data<span class="sc">$</span>Site_B)</span>
<span id="cb89-4"><a href="hypothesis-testing.html#cb89-4" tabindex="-1"></a></span>
<span id="cb89-5"><a href="hypothesis-testing.html#cb89-5" tabindex="-1"></a><span class="co"># Perform t-test</span></span>
<span id="cb89-6"><a href="hypothesis-testing.html#cb89-6" tabindex="-1"></a><span class="fu">t.test</span>(site_A, site_B, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)  <span class="co"># Two-tailed test</span></span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  site_A and site_B
## t = 5.324, df = 28, p-value = 1.144e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.336700 5.259205
## sample estimates:
## mean of x mean of y 
## 12.304769  8.506816</code></pre>
<p>The p-value is less than the 0.05 therefore the null hypothesis is rejected. It is concluded that <strong>Mean concentration at Site A ≠ Mean concentration at Site B</strong></p>
<ul>
<li><p>Use the paired t-test to compare arsenic levels at the same sites before and after remediation to determine if the intervention was effective. The question here is, “Did arsenic levels significantly decrease after remediation?”. Lets formulate the hypothesis before answering the above question;</p>
<ul>
<li>Null Hypothesis (H₀): Mean before = Mean after.</li>
<li>Alternative Hypothesis (H₁): Mean before &gt; Mean after (one-tailed test)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="hypothesis-testing.html#cb91-1" tabindex="-1"></a><span class="co"># Declare variables </span></span>
<span id="cb91-2"><a href="hypothesis-testing.html#cb91-2" tabindex="-1"></a>before_remediation <span class="ot">=</span> <span class="fu">c</span>(arsenic_data<span class="sc">$</span>Before_Remediation)</span>
<span id="cb91-3"><a href="hypothesis-testing.html#cb91-3" tabindex="-1"></a>after_remediation <span class="ot">=</span> <span class="fu">c</span>(arsenic_data<span class="sc">$</span>After_Remediation)</span>
<span id="cb91-4"><a href="hypothesis-testing.html#cb91-4" tabindex="-1"></a></span>
<span id="cb91-5"><a href="hypothesis-testing.html#cb91-5" tabindex="-1"></a><span class="co"># Perform t-test</span></span>
<span id="cb91-6"><a href="hypothesis-testing.html#cb91-6" tabindex="-1"></a><span class="fu">t.test</span>(before_remediation, after_remediation, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  before_remediation and after_remediation
## t = 9.7991, df = 14, p-value = 6.002e-08
## alternative hypothesis: true mean difference is greater than 0
## 95 percent confidence interval:
##  1.69087     Inf
## sample estimates:
## mean difference 
##        2.061387</code></pre>
<p>Conclusion: p-value &lt; 0.05, we reject H₀, meaning that remediation significantly reduced arsenic levels.</p>
<p>Here are the important considerations when performing parametric two sample test;</p>
<ol style="list-style-type: decimal">
<li>If the data is not normally distributed, applying a logarithmic transformation can help, but it should be done carefully to avoid misinterpretation.</li>
<li>These tests are often conducted using statistical software such as R, Python, or Excel for ease and accuracy.</li>
</ol>
<p><span style="color: green;"><strong>Practical exercises</strong></span></p>
<p>Industrial fertilizer use can increase organic carbon levels in groundwater, potentially impacting water quality and ecosystem health. In this exercise, you will use three parametric tests to answer the following questions:</p>
<ul>
<li><strong>Single-Sample Test:</strong> Is the average organic carbon concentration in background (control) wells significantly different from a regulatory threshold (e.g., 25 ppm)?</li>
<li><strong>Paired Two-Sample Test:</strong> Is there a significant difference in organic carbon concentration between cleaned water and before?</li>
<li><strong>Independent Two-Sample Test:</strong></li>
</ul>
<p>Your are provided with water portability data set that can be downloaded from <a href="https://www.kaggle.com/code/moosecat/water-quality-eda-cleaning-and-prediction?select=water_potability.csv">here</a></p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
<div id="nonparametric-test" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Nonparametric test<a href="hypothesis-testing.html#nonparametric-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="nonparametric-one-sample-wilcoxon-signed-rank-test" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Nonparametric One-Sample Wilcoxon Signed-Rank Test<a href="hypothesis-testing.html#nonparametric-one-sample-wilcoxon-signed-rank-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>Wilcoxon Signed-Rank (WSR) Test</strong> is a nonparametric test used to determine whether the median of a population differs from a fixed reference value. Unlike the <strong>sign test</strong>, which only considers the direction of differences, the <strong>WSR test</strong> accounts for the magnitude of deviations as well.</p>
<p>Here are the asssumptions to considered when performing the test;</p>
<ul>
<li>The data values are independent.</li>
<li>The underlying population is symmetrically distributed (but not necessarily normal) around the median.</li>
<li>The number of tied values should be minimal.</li>
<li>The test cannot handle nondetect (ND) values because it requires actual magnitudes for ranking.</li>
</ul>
<p>Just follow the procedures outline below to perform the test;</p>
<ol style="list-style-type: decimal">
<li>Compute the deviations from the reference value.</li>
<li>Rank the absolute values of the deviations (smallest gets rank 1, next smallest gets rank 2, etc.).</li>
<li>Assign average ranks in case of tied values.</li>
<li>Sum the ranks corresponding to positive deviations.</li>
<li>Compare the test statistic with a critical value (from tables) or use a normal approximation if sample size is large (n &gt; 20).</li>
<li>Compute a p-value and determine statistical significance.</li>
</ol>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Suppose we have measured pollutant concentrations at a site and want to test whether the median concentration is different from a standard of 50 ppm.</p>
<p>Lets formulate the null and the alternate hypothesis before carrying out the test.</p>
<ul>
<li><em>Null Hypothesis(<span class="math inline">\(H_0\)</span>):</em> The median of the population is equal to the reference value.</li>
<li><em>Alternate Hypothesis(<span class="math inline">\(H_A\)</span>):</em> The median is different from the reference value.</li>
</ul>
<p>Now lets perform the test, where it will return the <strong>W#-statistic</strong> and <strong>p-value</strong> if:</p>
<ul>
<li>If p &lt; 0.05, we reject H₀, indicating that the median is significantly different from 50 ppm.</li>
<li>If p &gt; 0.05, we fail to reject H₀, meaning there is no strong evidence to say the median differs from 50 ppm.</li>
</ul>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="hypothesis-testing.html#cb93-1" tabindex="-1"></a><span class="co"># Load required package</span></span>
<span id="cb93-2"><a href="hypothesis-testing.html#cb93-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb93-3"><a href="hypothesis-testing.html#cb93-3" tabindex="-1"></a>data_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">55</span>, <span class="dv">60</span>, <span class="dv">52</span>, <span class="dv">48</span>, <span class="dv">51</span>, <span class="dv">53</span>, <span class="dv">47</span>, <span class="dv">49</span>, <span class="dv">54</span>)</span>
<span id="cb93-4"><a href="hypothesis-testing.html#cb93-4" tabindex="-1"></a>reference_value <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb93-5"><a href="hypothesis-testing.html#cb93-5" tabindex="-1"></a></span>
<span id="cb93-6"><a href="hypothesis-testing.html#cb93-6" tabindex="-1"></a><span class="co"># Perform Wilcoxon Signed-Rank Test</span></span>
<span id="cb93-7"><a href="hypothesis-testing.html#cb93-7" tabindex="-1"></a><span class="fu">wilcox.test</span>(data_values, <span class="at">mu =</span> reference_value, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  data_values
## V = 36, p-value = 0.4136
## alternative hypothesis: true location is not equal to 50</code></pre>
<p><strong>Note that!</strong></p>
<ul>
<li>The test does not work well if the data contain ND values (nondetects), since exact magnitudes are needed.</li>
<li>Works best when the data are symmetrically distributed</li>
<li>For large samples (n &gt; 20), the normal approximation is used instead of exact critical values.</li>
</ul>
<p>The Wilcoxon Signed-Rank Test is a useful nonparametric alternative to the one-sample t-test when normality is questionable. It provides a robust way to assess median differences while taking data magnitudes into account.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Acid rain is a major environmental concern, particularly in industrial areas. In our study, we are interested in understanding the effect of emission controls on rainwater acidity. Rainwater pH values are recorded before and after the intervention at the same 15 monitoring stations. Because pH measurements are continuous but the data set is relatively small and may not meet the assumptions of parametric tests, nonparametric methods offer a robust alternative.</p>
<p>You are required to perform to use the <code>acid_rain</code> data set provided by the instructor to perform Nonparametric One-Sample Wilcoxon Signed-Rank Test. The objective of this project is to test whether the median rainwater pH before the intervention is different from the regulatory standard of 5.5.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><strong>Project Objective</strong>: Test whether the median rainwater pH before the intervention is different from the regulatory standard of 5.5.</p>
<p><strong>Hypotheses</strong>:</p>
<ul>
<li><em>Null Hypothesis</em>: The median pH before intervention is 5.5</li>
<li><em>Alternative Hypothesis</em>: The median pH before intervention is not 5.5.</li>
</ul>
<p><strong>Mathematical Concept:</strong></p>
<p>For each observation, compute the difference:
<span class="math display">\[d_i = pH_i - 5.5\]</span>
Then rank the absolute differences <span class="math inline">\(|d_i|\)</span> (ignoring zeros) and sum the ranks for positive differences. The Wilcoxon test statistic <span class="math inline">\(W\)</span> is compared against its distribution to determine significance.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="hypothesis-testing.html#cb95-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb95-2"><a href="hypothesis-testing.html#cb95-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb95-3"><a href="hypothesis-testing.html#cb95-3" tabindex="-1"></a></span>
<span id="cb95-4"><a href="hypothesis-testing.html#cb95-4" tabindex="-1"></a><span class="co"># Read the dataset (adjust the URL as needed)</span></span>
<span id="cb95-5"><a href="hypothesis-testing.html#cb95-5" tabindex="-1"></a>acid_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/acid_rain.csv&quot;</span>)</span>
<span id="cb95-6"><a href="hypothesis-testing.html#cb95-6" tabindex="-1"></a></span>
<span id="cb95-7"><a href="hypothesis-testing.html#cb95-7" tabindex="-1"></a><span class="co"># View the first few rows</span></span>
<span id="cb95-8"><a href="hypothesis-testing.html#cb95-8" tabindex="-1"></a><span class="co">#head(acid_data)</span></span>
<span id="cb95-9"><a href="hypothesis-testing.html#cb95-9" tabindex="-1"></a></span>
<span id="cb95-10"><a href="hypothesis-testing.html#cb95-10" tabindex="-1"></a><span class="co"># Nonparametric One-Sample Wilcoxon Signed-Rank Test on &#39;Before&#39; pH values</span></span>
<span id="cb95-11"><a href="hypothesis-testing.html#cb95-11" tabindex="-1"></a><span class="co"># Test if the median pH before intervention is 5.5</span></span>
<span id="cb95-12"><a href="hypothesis-testing.html#cb95-12" tabindex="-1"></a>wilcox_test_before <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(acid_data<span class="sc">$</span>Before, <span class="at">mu =</span> <span class="fl">5.5</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span>
<span id="cb95-13"><a href="hypothesis-testing.html#cb95-13" tabindex="-1"></a><span class="fu">print</span>(wilcox_test_before)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  acid_data$Before
## V = 67, p-value = 0.7197
## alternative hypothesis: true location is not equal to 5.5</code></pre>
<p>p-value is above 0.05 therefore the null hypothesis is accepted where we conclude that the median pH before the intervention is 5.5.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="nonparametric-two-sample-paired-sign-test-and-paired-wilcoxon-signed-rank-test" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Nonparametric two-sample paired sign test and paired Wilcoxon Signed Rank Test<a href="hypothesis-testing.html#nonparametric-two-sample-paired-sign-test-and-paired-wilcoxon-signed-rank-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>Wilcoxon Rank Sum Test</strong> (also known as the <strong>Mann–Whitney U test</strong> or the <strong>Wilcoxon–Mann–Whitney test</strong>) is a nonparametric procedure that tests for a difference between two population medians. The test is used to determine whether one population consistently produces larger or smaller measurements than another, assuming that the two populations have approximately equal variance.</p>
<p>Here are the assumptions before carrying out the test;</p>
<ul>
<li>The two samples are independent.</li>
<li>The data distributions of the two populations are similar in shape (same variance), though not necessarily the same mean or median.</li>
<li>The test does not assume a specific distribution (e.g., normal, lognormal, gamma, etc.).</li>
<li>The sample size for each group should preferably be at least 20, but meaningful results can still be obtained with samples as small as 10 using refined algorithms.</li>
</ul>
<p>Follow the steps below to carry out the tests;</p>
<ol style="list-style-type: decimal">
<li>Combine the two samples into a single data set and rank the observations in ascending order.</li>
<li>Compute the Wilcoxon test statistic as the sum of the ranks for one of the groups (usually the smaller group).</li>
<li>If each sample size is , obtain the critical value from statistical tables.</li>
<li>If each sample size is , compute the test statistic’s standardized form and compare it to the normal distribution.</li>
<li>Compute the p-value from statistical tables or using functions in R such as <code>pnorm()</code>.</li>
</ol>
<p>If tied values exist;</p>
<ul>
<li>the average rank is assigned to all tied values.</li>
<li>The presence of ties may require an adjustment to the test statistic calculation.</li>
</ul>
<p>If there exist Non-Detects (NDs);</p>
<ul>
<li>If all NDs share a single reporting limit, they can be treated as tied values.</li>
<li>If multiple reporting limits exist, alternative tests such as the Gehan test are preferred.</li>
</ul>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets test between two groups</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="hypothesis-testing.html#cb97-1" tabindex="-1"></a><span class="co"># Sample data</span></span>
<span id="cb97-2"><a href="hypothesis-testing.html#cb97-2" tabindex="-1"></a>group1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">15</span>)</span>
<span id="cb97-3"><a href="hypothesis-testing.html#cb97-3" tabindex="-1"></a>group2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>)</span>
<span id="cb97-4"><a href="hypothesis-testing.html#cb97-4" tabindex="-1"></a></span>
<span id="cb97-5"><a href="hypothesis-testing.html#cb97-5" tabindex="-1"></a><span class="co"># Perform Wilcoxon Rank Sum Test</span></span>
<span id="cb97-6"><a href="hypothesis-testing.html#cb97-6" tabindex="-1"></a><span class="fu">wilcox.test</span>(group1, group2, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  group1 and group2
## W = 16, p-value = 0.5476
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Exact testing using <code>wilcox.exact()</code></p>
<p>install the <code>exactRankTests</code></p>
<pre><code>install.packages(&quot;exactRankTests&quot;)</code></pre>
<p>Run the test</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="hypothesis-testing.html#cb100-1" tabindex="-1"></a><span class="fu">library</span>(exactRankTests)</span></code></pre></div>
<pre><code>##  Package &#39;exactRankTests&#39; is no longer under development.
##  Please consider using package &#39;coin&#39; instead.</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="hypothesis-testing.html#cb102-1" tabindex="-1"></a><span class="fu">wilcox.exact</span>(group1, group2, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Exact Wilcoxon rank sum test
## 
## data:  group1 and group2
## W = 16, p-value = 0.5476
## alternative hypothesis: true mu is not equal to 0</code></pre>
<p>Using <code>coin</code> package for more complex cases. First install the package <code>install.packages("coin")</code></p>
<p>Run the test</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="hypothesis-testing.html#cb104-1" tabindex="-1"></a><span class="fu">library</span>(coin)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;coin&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     alpha</code></pre>
<pre><code>## The following objects are masked from &#39;package:exactRankTests&#39;:
## 
##     dperm, pperm, qperm, rperm</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="hypothesis-testing.html#cb108-1" tabindex="-1"></a><span class="co"># wilcox_test(group1 ~ group2)</span></span></code></pre></div>
<p>The Wilcoxon Rank Sum Test is a useful nonparametric alternative to the two-sample t-test when normality cannot be assumed. It is robust to outliers and does not require knowledge of the underlying data distribution. R provides multiple functions for computing the test, with options for handling ties and computing exact p-values.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Using the “acid rain” above determine if there is a consistent direction of change in pH values (i.e., whether more stations show an increase or decrease in pH after the intervention). Use the non-parametric paired sign test.</p>
<p>Repeat what you have done with Nonparametric Paired Wilcoxon Signed-Rank Test. However, in this case, test whether there is a statistically significant difference between the pH values before and after the intervention.
_______________________________________________________________________
<span style="color: brown;"><strong>Solution</strong></span></p>
<p><strong>Project Objective</strong>: Is there a consistent direction of change in pH values (i.e., whether more stations show an increase or decrease in pH after the intervention).</p>
<p><strong>Hypotheses</strong></p>
<ul>
<li><em>Null Hypothesis:</em> There is no difference in the number of stations with increased versus decreased pH.</li>
<li><em>Alternate Hypothesis:</em> There is a significant difference in the number of stations showing an increase compared to a decrease.</li>
</ul>
<p><strong>Methods</strong></p>
<p>For each station, calculate:</p>
$$
sign(d_i) =
<span class="math display">\[\begin{cases}
1, &amp; \text{if } After - Before &gt; 0 \\
0, &amp; \text{if } After - Before = 0 \\
-1, &amp; \text{if } After - Before &lt; 0
\end{cases}\]</span>
<p>$$
Count the number of positive differences and use a binomial test to see if it deviates from the expected 50% chance.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="hypothesis-testing.html#cb109-1" tabindex="-1"></a><span class="co"># Compute differences between After and Before pH values</span></span>
<span id="cb109-2"><a href="hypothesis-testing.html#cb109-2" tabindex="-1"></a>acid_data <span class="ot">&lt;-</span> acid_data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Diff =</span> After <span class="sc">-</span> Before)</span>
<span id="cb109-3"><a href="hypothesis-testing.html#cb109-3" tabindex="-1"></a></span>
<span id="cb109-4"><a href="hypothesis-testing.html#cb109-4" tabindex="-1"></a><span class="co"># Count number of positive changes (excluding ties)</span></span>
<span id="cb109-5"><a href="hypothesis-testing.html#cb109-5" tabindex="-1"></a>positive_changes <span class="ot">&lt;-</span> <span class="fu">sum</span>(acid_data<span class="sc">$</span>Diff <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb109-6"><a href="hypothesis-testing.html#cb109-6" tabindex="-1"></a>total_nonzero <span class="ot">&lt;-</span> <span class="fu">sum</span>(acid_data<span class="sc">$</span>Diff <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb109-7"><a href="hypothesis-testing.html#cb109-7" tabindex="-1"></a></span>
<span id="cb109-8"><a href="hypothesis-testing.html#cb109-8" tabindex="-1"></a><span class="co"># Perform a binomial test assuming a 50% chance of an increase</span></span>
<span id="cb109-9"><a href="hypothesis-testing.html#cb109-9" tabindex="-1"></a>sign_test <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(positive_changes, total_nonzero, <span class="at">p =</span> <span class="fl">0.5</span>)</span>
<span id="cb109-10"><a href="hypothesis-testing.html#cb109-10" tabindex="-1"></a><span class="fu">print</span>(sign_test)</span></code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  positive_changes and total_nonzero
## number of successes = 10, number of trials = 15, p-value = 0.3018
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.3838037 0.8817589
## sample estimates:
## probability of success 
##              0.6666667</code></pre>
<p>p-value is above 0.05 therefore the null hypothesis is accepted. We will conclude that there is no difference in the number of stations with increased versus decreased pH.</p>
<p>Lets repeat the same for <em>Nonparametric Paired Wilcoxon Signed-Rank Test</em></p>
<p><strong>Project Objective</strong> : Test whether there is a statistically significant difference between the pH values before and after the intervention.</p>
<p><strong>Hypotheses</strong>:</p>
<ul>
<li><em>Null hypothesis</em>: The median difference between paired pH values (After - Before) is zero.</li>
<li><em>Alternate hypothesis</em>: The median difference is not zero.</li>
</ul>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="hypothesis-testing.html#cb111-1" tabindex="-1"></a><span class="co"># Paired Wilcoxon Signed-Rank Test</span></span>
<span id="cb111-2"><a href="hypothesis-testing.html#cb111-2" tabindex="-1"></a>paired_wilcox <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(acid_data<span class="sc">$</span>Before, acid_data<span class="sc">$</span>After, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span>
<span id="cb111-3"><a href="hypothesis-testing.html#cb111-3" tabindex="-1"></a><span class="fu">print</span>(paired_wilcox)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  acid_data$Before and acid_data$After
## V = 53, p-value = 0.7197
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The p-value is above -.-5 therefore there is no significant change in pH after the intervention.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
<div id="one-way-anova" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> One-Way ANOVA<a href="hypothesis-testing.html#one-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>ANOVA (Analysis of Variance) is a statistical method used to compare three or more groups to determine whether their means or medians significantly differ, or if they belong to the same population. It is particularly useful in scenarios where multiple groups need to be analyzed simultaneously, reducing the risk of errors that arise from multiple two-sample tests. ANOVA can be categorized into parametric (assuming normality and equal variances) and nonparametric (distribution-free) methods. Variants include One-Way ANOVA (influenced by a single factor) and Two-Way or Multifactor ANOVA (considering multiple factors). While ANOVA helps identify overall differences, post hoc tests are often needed to determine which groups specifically differ</p>
<p>In this analysis we will focus on One-Way ANOVA, the parametric and non-parametric one.</p>
<div id="parametric-one-way-anova" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Parametric One-Way ANOVA<a href="hypothesis-testing.html#parametric-one-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One-Way ANOVA is a parametric statistical test used to determine whether there are significant differences among the means of three or more independent groups. It is commonly applied in various fields, including ecology, to analyze how a single factor influences a dependent variable, such as plant growth across different soil types.</p>
<p>Here are the assumptions that must be met before conducting One-Way ANOVA</p>
<ul>
<li><strong>Normality</strong> – Each group’s data should follow a normal distribution. This can be tested using the <strong>Shapiro-Wilk test</strong> or <strong>Kolmogorov-Smirnov test</strong>.</li>
<li><strong>Homogeneity of Variance</strong> – The variance across groups should be approximately equal, verified using <strong>Levene’s test</strong> or <strong>Bartlett’s test</strong>.</li>
<li><strong>Independence</strong> – Observations should be independent, meaning one measurement should not influence another.</li>
</ul>
<p>If these assumptions are violated, alternatives such as <strong>Welch’s ANOVA</strong> (for unequal variances) or <strong>Kruskal-Wallis test</strong> (non-parametric alternative) should be considered.</p>
<p>This is how One-Way ANOVA works; It compares -</p>
<ul>
<li><em>Between-Group Variance</em> – Measures differences among the group means.</li>
<li><em>Within-Group Variance</em> – Measures variability within each group.</li>
</ul>
<p>A high F-statistic suggests that at least one group mean differs significantly. The test’s p-value is then used to determine statistical significance (typically, if p &lt; 0.05, the null hypothesis is rejected).</p>
<p>One-Way ANOVA is important in Ecology as it can be used to find;
- Differences in <strong>plant species diversity</strong> across multiple forest regions.
- Variations in <strong>water pH levels</strong> among different lakes.
- The effect of <strong>pollution levels</strong> on fish populations across multiple rivers.</p>
<p>For example, an ecologist studying wetland ecosystems might apply One-Way ANOVA to determine whether soil nitrogen levels significantly affect plant biodiversity across different wetland sites. If the test finds a significant difference, post hoc tests like Tukey’s HSD can identify which specific wetland sites differ.</p>
<p>By using One-Way ANOVA, ecologists and researchers can make informed, data-driven decisions about conservation efforts and environmental management strategies.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>In our case, we have have generated the sample data for three groups; <code>group1</code>, <code>group2</code> and <code>group3</code>. Formulating the null hypothesis;</p>
<ul>
<li><em>Null Hypothesis</em>: The mean is the same across all gropu populations.</li>
<li><em>Alternate hypothesis</em>: At least one group population has a different mean from the rest of the group.</li>
</ul>
<p>When modelling the parametric one-way ANOVA, the <strong>F-statistic</strong> is computed as;
<span class="math display">\[{F} = {{\text Between-Groups Variance(MSG)}\over{\text Within-Group Variance(MSEE)}}\]</span>
Where;</p>
<ul>
<li><span class="math inline">\(MSG = {{SSBG}\over{k-1}}\)</span>, the <span class="math inline">\(SSBG\)</span> is the sum of squares.</li>
<li><span class="math inline">\(MSE = {{SSWG}\over{N-k}}\)</span>, the <span class="math inline">\(SSWG\)</span> is the between group sum of squares.</li>
</ul>
<p><span class="math inline">\(k\)</span> as the number of groups and <span class="math inline">\(N\)</span> as the total number of observaions.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="hypothesis-testing.html#cb113-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb113-2"><a href="hypothesis-testing.html#cb113-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb113-3"><a href="hypothesis-testing.html#cb113-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb113-4"><a href="hypothesis-testing.html#cb113-4" tabindex="-1"></a></span>
<span id="cb113-5"><a href="hypothesis-testing.html#cb113-5" tabindex="-1"></a><span class="co"># Generate sample data</span></span>
<span id="cb113-6"><a href="hypothesis-testing.html#cb113-6" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb113-7"><a href="hypothesis-testing.html#cb113-7" tabindex="-1"></a>group1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb113-8"><a href="hypothesis-testing.html#cb113-8" tabindex="-1"></a>group2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">55</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb113-9"><a href="hypothesis-testing.html#cb113-9" tabindex="-1"></a>group3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">60</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb113-10"><a href="hypothesis-testing.html#cb113-10" tabindex="-1"></a></span>
<span id="cb113-11"><a href="hypothesis-testing.html#cb113-11" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb113-12"><a href="hypothesis-testing.html#cb113-12" tabindex="-1"></a>  <span class="at">values =</span> <span class="fu">c</span>(group1, group2, group3),</span>
<span id="cb113-13"><a href="hypothesis-testing.html#cb113-13" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Group1&quot;</span>, <span class="st">&quot;Group2&quot;</span>, <span class="st">&quot;Group3&quot;</span>), <span class="at">each =</span> <span class="dv">10</span>)</span>
<span id="cb113-14"><a href="hypothesis-testing.html#cb113-14" tabindex="-1"></a>)</span>
<span id="cb113-15"><a href="hypothesis-testing.html#cb113-15" tabindex="-1"></a></span>
<span id="cb113-16"><a href="hypothesis-testing.html#cb113-16" tabindex="-1"></a><span class="co"># Compute group means and overall mean</span></span>
<span id="cb113-17"><a href="hypothesis-testing.html#cb113-17" tabindex="-1"></a>means <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_value =</span> <span class="fu">mean</span>(values))</span>
<span id="cb113-18"><a href="hypothesis-testing.html#cb113-18" tabindex="-1"></a>overall_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>values)</span>
<span id="cb113-19"><a href="hypothesis-testing.html#cb113-19" tabindex="-1"></a></span>
<span id="cb113-20"><a href="hypothesis-testing.html#cb113-20" tabindex="-1"></a><span class="co"># Compute sum of squares</span></span>
<span id="cb113-21"><a href="hypothesis-testing.html#cb113-21" tabindex="-1"></a>SSBG <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="dv">10</span> <span class="sc">*</span> (means<span class="sc">$</span>mean_value <span class="sc">-</span> overall_mean)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Between-group sum of squares</span></span>
<span id="cb113-22"><a href="hypothesis-testing.html#cb113-22" tabindex="-1"></a>SSWG <span class="ot">&lt;-</span> <span class="fu">sum</span>((data<span class="sc">$</span>values <span class="sc">-</span> <span class="fu">ave</span>(data<span class="sc">$</span>values, data<span class="sc">$</span>group, <span class="at">FUN =</span> mean))<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Within-group sum of squares</span></span>
<span id="cb113-23"><a href="hypothesis-testing.html#cb113-23" tabindex="-1"></a>SSTotal <span class="ot">&lt;-</span> <span class="fu">sum</span>((data<span class="sc">$</span>values <span class="sc">-</span> overall_mean)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Total sum of squares</span></span>
<span id="cb113-24"><a href="hypothesis-testing.html#cb113-24" tabindex="-1"></a></span>
<span id="cb113-25"><a href="hypothesis-testing.html#cb113-25" tabindex="-1"></a>df_SSBG <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>group)) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb113-26"><a href="hypothesis-testing.html#cb113-26" tabindex="-1"></a>df_SSWG <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data) <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>group))</span>
<span id="cb113-27"><a href="hypothesis-testing.html#cb113-27" tabindex="-1"></a>df_SSTotal <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb113-28"><a href="hypothesis-testing.html#cb113-28" tabindex="-1"></a></span>
<span id="cb113-29"><a href="hypothesis-testing.html#cb113-29" tabindex="-1"></a><span class="co"># Compute mean squares</span></span>
<span id="cb113-30"><a href="hypothesis-testing.html#cb113-30" tabindex="-1"></a>MSG <span class="ot">&lt;-</span> SSBG <span class="sc">/</span> df_SSBG</span>
<span id="cb113-31"><a href="hypothesis-testing.html#cb113-31" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSWG <span class="sc">/</span> df_SSWG</span>
<span id="cb113-32"><a href="hypothesis-testing.html#cb113-32" tabindex="-1"></a></span>
<span id="cb113-33"><a href="hypothesis-testing.html#cb113-33" tabindex="-1"></a><span class="co"># Compute F-statistic</span></span>
<span id="cb113-34"><a href="hypothesis-testing.html#cb113-34" tabindex="-1"></a>F0 <span class="ot">&lt;-</span> MSG <span class="sc">/</span> MSE</span>
<span id="cb113-35"><a href="hypothesis-testing.html#cb113-35" tabindex="-1"></a></span>
<span id="cb113-36"><a href="hypothesis-testing.html#cb113-36" tabindex="-1"></a><span class="co"># Compute critical F value</span></span>
<span id="cb113-37"><a href="hypothesis-testing.html#cb113-37" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb113-38"><a href="hypothesis-testing.html#cb113-38" tabindex="-1"></a>F_critical <span class="ot">&lt;-</span> <span class="fu">qf</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, df_SSBG, df_SSWG)</span>
<span id="cb113-39"><a href="hypothesis-testing.html#cb113-39" tabindex="-1"></a></span>
<span id="cb113-40"><a href="hypothesis-testing.html#cb113-40" tabindex="-1"></a><span class="co"># Compute p-value</span></span>
<span id="cb113-41"><a href="hypothesis-testing.html#cb113-41" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(F0, df_SSBG, df_SSWG)</span>
<span id="cb113-42"><a href="hypothesis-testing.html#cb113-42" tabindex="-1"></a></span>
<span id="cb113-43"><a href="hypothesis-testing.html#cb113-43" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb113-44"><a href="hypothesis-testing.html#cb113-44" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Between-group sum of squares (SSBG):&quot;</span>, SSBG, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Between-group sum of squares (SSBG): 223.5015</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="hypothesis-testing.html#cb115-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Within-group sum of squares (SSWG):&quot;</span>, SSWG, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Within-group sum of squares (SSWG): 2568.336</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="hypothesis-testing.html#cb117-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total sum of squares (SSTotal):&quot;</span>, SSTotal, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Total sum of squares (SSTotal): 2791.837</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="hypothesis-testing.html#cb119-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;F-statistic (Fo):&quot;</span>, F0, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## F-statistic (Fo): 1.174796</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="hypothesis-testing.html#cb121-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Critical F value (Fc):&quot;</span>, F_critical, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Critical F value (Fc): 3.354131</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="hypothesis-testing.html#cb123-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;p-value:&quot;</span>, p_value, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## p-value: 0.3241775</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="hypothesis-testing.html#cb125-1" tabindex="-1"></a><span class="co"># Perform ANOVA using built-in function</span></span>
<span id="cb125-2"><a href="hypothesis-testing.html#cb125-2" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(values <span class="sc">~</span> group, <span class="at">data =</span> data)</span>
<span id="cb125-3"><a href="hypothesis-testing.html#cb125-3" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## group        2  223.5  111.75   1.175  0.324
## Residuals   27 2568.3   95.12</code></pre>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Air quality is an important ecological and public health concern. For example, understanding whether Nitrogen Dioxide (<span class="math inline">\(NO_2\)</span>) concentrations differ significantly across different states can inform regulatory decisions and resource management. In this exercise, you will use the “Air Quality Data in India” dataset, which is publicly available on Kaggle, to test the following:</p>
<p>You are required to use the <strong>Parametric One-Way ANOVA</strong> to compare the means of the pollutant levels across different groups.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="hypothesis-testing.html#cb127-1" tabindex="-1"></a><span class="co"># Load the required libraries</span></span>
<span id="cb127-2"><a href="hypothesis-testing.html#cb127-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb127-3"><a href="hypothesis-testing.html#cb127-3" tabindex="-1"></a></span>
<span id="cb127-4"><a href="hypothesis-testing.html#cb127-4" tabindex="-1"></a><span class="co"># Load the data </span></span>
<span id="cb127-5"><a href="hypothesis-testing.html#cb127-5" tabindex="-1"></a>air_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/AirQualityDataIndia.csv&quot;</span>)</span>
<span id="cb127-6"><a href="hypothesis-testing.html#cb127-6" tabindex="-1"></a></span>
<span id="cb127-7"><a href="hypothesis-testing.html#cb127-7" tabindex="-1"></a></span>
<span id="cb127-8"><a href="hypothesis-testing.html#cb127-8" tabindex="-1"></a><span class="co"># Perform one-way ANOVA</span></span>
<span id="cb127-9"><a href="hypothesis-testing.html#cb127-9" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(no2 <span class="sc">~</span> state, <span class="at">data =</span> air_data)</span>
<span id="cb127-10"><a href="hypothesis-testing.html#cb127-10" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##                 Df   Sum Sq Mean Sq F value Pr(&gt;F)    
## state           33 53343341 1616465    7511 &lt;2e-16 ***
## Residuals   419475 90281183     215                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 16233 observations deleted due to missingness</code></pre>
<p>Although there were missing values in the data set, The F-statistic was 7511 and 33 degrees of freedom.</p>
<p>The p-value was far much less than 0.05 therefore there is enough evidence to reject the null hypothesis. We conclude that <em>atleast one state had a different mean concentration of Nitrogen dioxide from the rest of the states</em></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="nonparametric-one-way-anova-kruskal-wallis-test" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Nonparametric One-Way ANOVA (Kruskal-Wallis Test)<a href="hypothesis-testing.html#nonparametric-one-way-anova-kruskal-wallis-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When conducting a parametric one-way ANOVA, one of the key assumptions is that the residuals follow a normal distribution. If this assumption is violated, a common approach is to apply a logarithmic transformation—using either the natural logarithm (<span class="math inline">\(ln\)</span>) or the base-10 logarithm (log10)—to the data. If this transformation successfully normalizes the data and satisfies the assumption of homogeneity of variances, then the ANOVA can be performed on the transformed values.</p>
<p>However, if both the original and log-transformed data fail to meet the assumptions required for parametric ANOVA, an alternative nonparametric test, the <strong>Kruskal–Wallis test</strong>, can be used. Unlike parametric ANOVA, the Kruskal–Wallis test does not assume normality but does require that the distributions of the populations have similar shapes, particularly regarding skewness and variance. This test also assumes that the data points are independent and do not exhibit trends.</p>
<p>If the presence of a trend affects the data, one approach is to use the <strong>Friedman test</strong>, which accounts for structured variability by analyzing data within blocks. Another option for handling seasonal or cyclical trends is <strong>deseasonalization</strong> before applying the Kruskal–Wallis test.</p>
<p><strong>Kruskal–Wallis Test Procedure</strong></p>
<p>The Kruskal–Wallis test examines differences in the medians of multiple groups rather than their means. It is performed by ranking all data values across groups and using the calculating a test statistic:</p>
<p>This statistic follows a <code>chi-square()</code> distribution with degrees of freedom, where is the number of groups. If exceeds the critical value at a chosen <code>significance level()</code>, or if the p-value is below 0.05, the null hypothesis of equal medians is rejected.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p><strong>Ecological Example: Testing Differences in Soil Nutrient Levels</strong></p>
<p>Consider a study where researchers measure soil nitrogen levels in three different ecosystems: grassland, wetland, and forest. Since soil nutrient data often exhibit skewness, the Kruskal–Wallis test is a suitable choice.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="hypothesis-testing.html#cb129-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb129-2"><a href="hypothesis-testing.html#cb129-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb129-3"><a href="hypothesis-testing.html#cb129-3" tabindex="-1"></a></span>
<span id="cb129-4"><a href="hypothesis-testing.html#cb129-4" tabindex="-1"></a><span class="co"># Simulated soil nitrogen data (in mg/kg)</span></span>
<span id="cb129-5"><a href="hypothesis-testing.html#cb129-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb129-6"><a href="hypothesis-testing.html#cb129-6" tabindex="-1"></a>grassland <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">30</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb129-7"><a href="hypothesis-testing.html#cb129-7" tabindex="-1"></a>wetland <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">40</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb129-8"><a href="hypothesis-testing.html#cb129-8" tabindex="-1"></a>forest <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">35</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb129-9"><a href="hypothesis-testing.html#cb129-9" tabindex="-1"></a></span>
<span id="cb129-10"><a href="hypothesis-testing.html#cb129-10" tabindex="-1"></a><span class="co"># Combine into a data frame</span></span>
<span id="cb129-11"><a href="hypothesis-testing.html#cb129-11" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb129-12"><a href="hypothesis-testing.html#cb129-12" tabindex="-1"></a>  <span class="at">Nitrogen =</span> <span class="fu">c</span>(grassland, wetland, forest),</span>
<span id="cb129-13"><a href="hypothesis-testing.html#cb129-13" tabindex="-1"></a>  <span class="at">Ecosystem =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Grassland&quot;</span>, <span class="st">&quot;Wetland&quot;</span>, <span class="st">&quot;Forest&quot;</span>), <span class="at">each =</span> <span class="dv">10</span>)</span>
<span id="cb129-14"><a href="hypothesis-testing.html#cb129-14" tabindex="-1"></a>)</span>
<span id="cb129-15"><a href="hypothesis-testing.html#cb129-15" tabindex="-1"></a></span>
<span id="cb129-16"><a href="hypothesis-testing.html#cb129-16" tabindex="-1"></a><span class="co"># Perform Kruskal-Wallis test</span></span>
<span id="cb129-17"><a href="hypothesis-testing.html#cb129-17" tabindex="-1"></a><span class="fu">kruskal.test</span>(Nitrogen <span class="sc">~</span> Ecosystem, <span class="at">data =</span> data)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Nitrogen by Ecosystem
## Kruskal-Wallis chi-squared = 4.2039, df = 2, p-value = 0.1222</code></pre>
<p>Since the p-value (0.1222) is greater than 0.05, we fail to reject the null hypothesis. This suggests that there is no statistically significant difference in median soil nitrogen levels among the three ecosystems. If a lower p-value had been obtained, further analysis using post hoc pairwise comparisons would be required to determine which specific ecosystems differ.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Using the air quality data in India from the previous exercise, perform non-parametric one-way ANOVA(Kruskal-Wallis Test) to compare the medians when data assumptions for ANOVA might not hold.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Formulate the hypothesis;</p>
<ul>
<li><em>Null hypothesis:</em> The median Nitrogen dioxide concentration is the same across all states.</li>
<li><em>Alternate hypothesis:</em> At least one state has a median Nitrogen dioxide concentration that is different.</li>
</ul>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="hypothesis-testing.html#cb131-1" tabindex="-1"></a><span class="co"># Perform the Kruskal-Wallis test</span></span>
<span id="cb131-2"><a href="hypothesis-testing.html#cb131-2" tabindex="-1"></a>kruskal_result <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(no2 <span class="sc">~</span> state, <span class="at">data =</span> air_data)</span>
<span id="cb131-3"><a href="hypothesis-testing.html#cb131-3" tabindex="-1"></a><span class="fu">print</span>(kruskal_result)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  no2 by state
## Kruskal-Wallis chi-squared = 166893, df = 33, p-value &lt; 2.2e-16</code></pre>
<p>The p-value is far much below 0.05 therefore the null hypothesis is rejected. It is concluded that at least one state has a median Nitrogen dioxide concentration that is different.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
<div id="hands-on-exercise" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> <span style="color: green;"><strong>Hands-on Exercise</strong></span><a href="hypothesis-testing.html#hands-on-exercise" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You are required to analyze the forest health and ecological diversity by performing various hypothesis testing. The data set can be downloaded from <a href="https://www.kaggle.com/datasets/ziya07/forest-health-and-ecological-diversity">here</a> – use the <code>forest_health_data_with_target.csv</code> Use the . Here is the breakdown of some of the data set attributes;</p>
<ul>
<li><em>Tree Height (m):</em> The height of individual trees.</li>
<li><em>Diameter at Breast Height (DBH) (cm):</em> The diameter of the tree trunk measured at breast height.</li>
<li><em>Species:</em> The species of each tree.</li>
<li><em>Health Status:</em> Categorized as ‘Healthy’ or ‘Unhealthy’.</li>
<li><em>Location:</em> Geographical location of the trees.</li>
</ul>
<p>The exercise will cover what we have just learnt above.
Answer the questions below;</p>
<ol style="list-style-type: decimal">
<li>Load the data set, and check for null values. If there is, handle them appropriately.</li>
<li>Apply the parametric single-sample test to test if the mean tree height differs from a hypothesized population mean. Hypothesized mean = 15 meters.</li>
<li>Perform the parametric independent two-sample t-tes to compare the mean DBH between ‘Healthy’ and ‘Unhealthy’ trees.</li>
<li>Perform parametric one-way ANOVA to determine if there’s a significant difference in mean Tree Height among different health status.</li>
<li>Using nonparametric one-way ANOVA(Kruskal-Wallis Test), test if there’s a significant difference in median DBH among different health status.</li>
</ol>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ol style="list-style-type: decimal">
<li>Load the data set, and check for null values. If there is, handle them appropriately.</li>
</ol>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="hypothesis-testing.html#cb133-1" tabindex="-1"></a><span class="co"># Load the data </span></span>
<span id="cb133-2"><a href="hypothesis-testing.html#cb133-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/forest_health/forest_health_data_with_target.csv&quot;</span>)</span>
<span id="cb133-3"><a href="hypothesis-testing.html#cb133-3" tabindex="-1"></a></span>
<span id="cb133-4"><a href="hypothesis-testing.html#cb133-4" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data)) <span class="co"># Check if there are missing values -- found none</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Apply the parametric single-sample test to test if the mean tree height differs from a hypothesized population mean. Hypothesized mean = 15 meters.</li>
</ol>
<ul>
<li><strong>Null hypothesis:</strong> The mean height of trees is equal to 15</li>
<li><strong>Alternate hypothesis:</strong> The mean height of trees is not equal to 15.</li>
</ul>
<p><em>Assumption:</em> Tree Height data is normally distributed.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="hypothesis-testing.html#cb135-1" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>Tree_Height, <span class="at">mu=</span><span class="dv">15</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data$Tree_Height
## t = 2.8797, df = 999, p-value = 0.004065
## alternative hypothesis: true mean is not equal to 15
## 95 percent confidence interval:
##  15.23272 16.22829
## sample estimates:
## mean of x 
##   15.7305</code></pre>
<p>From the test, the p-value is less than 0.05 therefore the null hypothesis is rejected. It is concluded the mean tree height of the entire population is not equal to 15</p>
<ol start="3" style="list-style-type: decimal">
<li>Perform the parametric independent two-sample t-test to compare the mean DBH between ‘Healthy’ and ‘Unhealthy’ trees.</li>
</ol>
<ul>
<li><p><strong>Null hypothesis:</strong> The mean DBH between health and unhealthy trees is the same.<br />
</p></li>
<li><p><strong>Alternate hypothesis:</strong> The mean DBH between health and unhealthy trees is the different</p></li>
<li><p><em>Assumptions:</em> DBH is normally distributed within each group, and variances are equal.</p></li>
</ul>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="hypothesis-testing.html#cb137-1" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb137-2"><a href="hypothesis-testing.html#cb137-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb137-3"><a href="hypothesis-testing.html#cb137-3" tabindex="-1"></a></span>
<span id="cb137-4"><a href="hypothesis-testing.html#cb137-4" tabindex="-1"></a><span class="co"># Get only the &#39;Healthy&#39; and &#39;Unhealthy&#39; matching values in the variables</span></span>
<span id="cb137-5"><a href="hypothesis-testing.html#cb137-5" tabindex="-1"></a>subset_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb137-6"><a href="hypothesis-testing.html#cb137-6" tabindex="-1"></a>  <span class="fu">subset</span>(Health_Status <span class="sc">==</span> <span class="st">&quot;Healthy&quot;</span> <span class="sc">|</span> Health_Status <span class="sc">==</span> <span class="st">&quot;Unhealthy&quot;</span>)</span>
<span id="cb137-7"><a href="hypothesis-testing.html#cb137-7" tabindex="-1"></a></span>
<span id="cb137-8"><a href="hypothesis-testing.html#cb137-8" tabindex="-1"></a><span class="co"># Perform the test </span></span>
<span id="cb137-9"><a href="hypothesis-testing.html#cb137-9" tabindex="-1"></a><span class="fu">t.test</span>(DBH <span class="sc">~</span> Health_Status, <span class="at">data =</span> subset_data, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  DBH by Health_Status
## t = 1.1018, df = 761, p-value = 0.2709
## alternative hypothesis: true difference in means between group Healthy and group Unhealthy is not equal to 0
## 95 percent confidence interval:
##  -1.763876  6.276335
## sample estimates:
##   mean in group Healthy mean in group Unhealthy 
##                54.37697                52.12074</code></pre>
<p>The p-value is way above 0.05 therefore we fail to reject the null hypothesis. It is concluded the mean DBH between Healthy and unhealthy trees is the same.</p>
<ol start="4" style="list-style-type: decimal">
<li>Perform parametric one-way ANOVA to determine if there’s a significant difference in mean Tree Height among different health status.</li>
</ol>
<ul>
<li><p><strong>Null hypothesis:</strong> There is no significant different between the height among trees with different health status.</p></li>
<li><p><strong>Alternate hypothesis:</strong> There is a significant different between the height among trees with different health status.</p></li>
<li><p><em>Assumptions:</em> There is normality and homogeneity of variances across groups.</p></li>
</ul>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="hypothesis-testing.html#cb139-1" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(Tree_Height <span class="sc">~</span> Health_Status, <span class="at">data =</span> data)</span>
<span id="cb139-2"><a href="hypothesis-testing.html#cb139-2" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Health_Status   3  15544    5181   105.9 &lt;2e-16 ***
## Residuals     996  48739      49                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-value is way much less than 0.05 therefore the null hypothesis is rejected. There is a significant height difference between trees with different health status.</p>
<ol start="5" style="list-style-type: decimal">
<li>Using nonparametric one-way ANOVA(Kruskal-Wallis Test), test if there’s a significant difference in median DBH among different health status.</li>
</ol>
<p>— Remember to provide a solution to the last question —————————————————–</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="test-for-autocorrelation-and-temporal-effects.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/balsaedi/RCourse/edit/main/02-hypothesis_testing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/balsaedi/RCourse/blob/main/02-hypothesis_testing.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
