<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Ecological Analysis</title>
  <meta name="description" content="Ecological Analysis" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Ecological Analysis" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Ecological Analysis" />
  
  
  

<meta name="author" content="Basim Alsaedi" />


<meta name="date" content="2024-11-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="hypothesis-testing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SHORT TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUCTION</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-distributions"><i class="fa fa-check"></i><b>1.1</b> Data Distributions</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#types-of-distribution"><i class="fa fa-check"></i><b>1.1.1</b> Types of Distribution</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#hands-on-exercises"><i class="fa fa-check"></i><b>1.2</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>2</b> HYPOTHESIS TESTING</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-tests"><i class="fa fa-check"></i><b>2.2</b> Parametric tests</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-single-sample-test"><i class="fa fa-check"></i><b>2.2.1</b> Parametric single-sample test</a></li>
<li class="chapter" data-level="2.2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-two-sample-test"><i class="fa fa-check"></i><b>2.2.2</b> Parametric two-sample test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-test"><i class="fa fa-check"></i><b>2.3</b> Nonparametric test</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-sample-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.1</b> Nonparametric One-Sample Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="2.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-two-sample-paired-sign-test-and-paired-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.2</b> Nonparametric two-sample paired sign test and paired Wilcoxon Signed Rank Test</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-one-way-anova"><i class="fa fa-check"></i><b>2.4.1</b> Parametric One-Way ANOVA</a></li>
<li class="chapter" data-level="2.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-way-anova-kruskal-wallis-test"><i class="fa fa-check"></i><b>2.4.2</b> Nonparametric One-Way ANOVA (Kruskal-Wallis Test)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hands-on-exercise"><i class="fa fa-check"></i><b>2.5</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html"><i class="fa fa-check"></i><b>3</b> TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS</a>
<ul>
<li class="chapter" data-level="3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#test-for-autocorrelation-using-the-sample-autocorrelation-function"><i class="fa fa-check"></i><b>3.1</b> Test for Autocorrelation Using the Sample Autocorrelation Function</a></li>
<li class="chapter" data-level="3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#an-example-on-site-wide-temporal-effects"><i class="fa fa-check"></i><b>3.2</b> An Example on Site-Wide Temporal Effects</a></li>
<li class="chapter" data-level="3.3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#tests-for-trend"><i class="fa fa-check"></i><b>3.3</b> TESTS FOR TREND</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#parametric-test-for-trends---simple-linear-regression"><i class="fa fa-check"></i><b>3.3.1</b> Parametric Test for Trends - Simple Linear Regression</a></li>
<li class="chapter" data-level="3.3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#nonparametric-test-for-trends"><i class="fa fa-check"></i><b>3.3.2</b> Nonparametric Test for Trends</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html"><i class="fa fa-check"></i><b>4</b> CORRELATION, COVARIANCE, GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> INTRODUCTION</a></li>
<li class="chapter" data-level="4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#correlation-and-covariance"><i class="fa fa-check"></i><b>4.2</b> CORRELATION AND COVARIANCE</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>4.2.1</b> Pearson’s Correlation Coefficient</a></li>
<li class="chapter" data-level="4.2.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#spearmans-and-kendalls-correlaton-coeefficients"><i class="fa fa-check"></i><b>4.2.2</b> Spearman’s and Kendall’s Correlaton Coeefficients</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#geostatistics"><i class="fa fa-check"></i><b>4.3</b> GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#variogram-modelling"><i class="fa fa-check"></i><b>4.3.1</b> Variogram Modelling</a></li>
<li class="chapter" data-level="4.3.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#kriging"><i class="fa fa-check"></i><b>4.3.2</b> Kriging</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html"><i class="fa fa-check"></i><b>5</b> LINEAR REGRESSION ANALYSIS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#simple-linear-regression-analysis"><i class="fa fa-check"></i><b>5.1</b> Simple Linear Regression Analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#empirical-model-building-regression-analysis"><i class="fa fa-check"></i><b>5.1.1</b> Empirical model-building-regression analysis</a></li>
<li class="chapter" data-level="5.1.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#interpreting-the-regression-results"><i class="fa fa-check"></i><b>5.1.2</b> Interpreting the regression results</a></li>
<li class="chapter" data-level="5.1.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#r-squared-and-adjusted-r-squared"><i class="fa fa-check"></i><b>5.1.3</b> R-squared and Adjusted R-Squared</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-versus-generalized-linear-model"><i class="fa fa-check"></i><b>5.2</b> Data transformation versus generalized linear model</a></li>
<li class="chapter" data-level="5.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#multiple-linear-regression-mlr-model"><i class="fa fa-check"></i><b>5.3</b> Multiple Linear Regression (MLR) model</a></li>
<li class="chapter" data-level="5.4" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#hands-on-exercise-1"><i class="fa fa-check"></i><b>5.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html"><i class="fa fa-check"></i><b>6</b> CONVENTIONAL AND PROBABILISTIC RISK ASSESSMENT</a>
<ul>
<li class="chapter" data-level="6.1" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#introduction-3"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#conventional-or-point-risk-estimation"><i class="fa fa-check"></i><b>6.2</b> Conventional or Point Risk Estimation</a></li>
<li class="chapter" data-level="6.3" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#probabilistic-risk-assessment-using-monte-carlo-simulation"><i class="fa fa-check"></i><b>6.3</b> Probabilistic Risk Assessment Using Monte Carlo Simulation</a></li>
<li class="chapter" data-level="6.4" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#practical-exercise"><i class="fa fa-check"></i><b>6.4</b> <span style="color: green;"><strong>Practical Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>7</b> Datasets</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ecological Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Ecological Analysis</h1>
<p class="author"><em>Basim Alsaedi</em></p>
<p class="date"><em>2024-11-16</em></p>
</div>
<div id="introduction" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> INTRODUCTION<a href="index.html#introduction" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The distinction between data sample and the underlying data population is always ignored. For instance the mean concentration of a chemical contaminant in a soil sample of a contaminated site. Here, the <strong>data sample</strong> is the soil sample that was taken to the laboratory to find out the mean concentration of the contaminant while the <strong>data population</strong> is the entire data population consisting of all possible soil measurements of the chemical contaminant at the site. We need to define some terms to get this clear.</p>
<ul>
<li><strong>Data Population: </strong> is the entire set of individuals, items or observations of interest in a study. For instance all the soil samples from the contaminant site.</li>
<li><strong>Data Sample: </strong> is the subset of the population selected for analysis. For example, measuring the height of randomly selected trees in the forest.</li>
<li><strong>Data Distribution: </strong> describes how data points are spread of arranged.</li>
</ul>
<p><strong>Data Sample vs Data Population</strong></p>
<p>A deep understanding of the difference between data sample and data population is important in inferential statistics which seeks to generalize the results of data analyses performed on the data samples. A data population consists of all possible observations or data points concerning the characteristic of interest. For instance, when finding out the mean height of all the oak trees in a forest, the data population will be every height of every single oak tree in the forest.</p>
<p>Contrary, data sample is usually a limited subset of observations drawn for the entire population. In this case we can have a data sample by randomly selecting 100 oak trees and measuring their heights.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets simulate data of oak trees with R</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="index.html#cb1-1" tabindex="-1"></a><span class="co"># Seed for reproducibility</span></span>
<span id="cb1-2"><a href="index.html#cb1-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="index.html#cb1-3" tabindex="-1"></a></span>
<span id="cb1-4"><a href="index.html#cb1-4" tabindex="-1"></a><span class="co"># A population of 12500 oak trees </span></span>
<span id="cb1-5"><a href="index.html#cb1-5" tabindex="-1"></a>population_heights <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">12500</span>, <span class="at">mean =</span> <span class="dv">20</span>, <span class="at">sd=</span><span class="dv">5</span>)</span>
<span id="cb1-6"><a href="index.html#cb1-6" tabindex="-1"></a><span class="fu">head</span>(population_heights)</span></code></pre></div>
<pre><code>## [1] 17.19762 18.84911 27.79354 20.35254 20.64644 28.57532</code></pre>
<p>We have simulated the heights of 12500 oak trees in a forest. The variance <code>population_heights</code> represent the data population for the oak tree heights. Lets randomly select 86 trees from the entire data population of oak tree heights</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="index.html#cb3-1" tabindex="-1"></a><span class="co"># Randomly select 86 trees </span></span>
<span id="cb3-2"><a href="index.html#cb3-2" tabindex="-1"></a>sample_heights <span class="ot">&lt;-</span> <span class="fu">sample</span>(population_heights, <span class="at">size=</span><span class="dv">86</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-3"><a href="index.html#cb3-3" tabindex="-1"></a><span class="fu">tail</span>(sample_heights)</span></code></pre></div>
<pre><code>## [1] 25.88792 29.03996 29.00965 37.10547 17.76631 19.81021</code></pre>
<p>The variable <code>sample_heights</code> represents data sample for the oak tree heights.</p>
<p>If we make this experiment more interesting, we find the mean and standard deviation for the data population and the data sample for the oak tree heights. Lets do it!</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="index.html#cb5-1" tabindex="-1"></a><span class="co"># Mean and standard deviation of the entire population</span></span>
<span id="cb5-2"><a href="index.html#cb5-2" tabindex="-1"></a>population_stats <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb5-3"><a href="index.html#cb5-3" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">mean</span>(population_heights),</span>
<span id="cb5-4"><a href="index.html#cb5-4" tabindex="-1"></a>  <span class="at">SD =</span> <span class="fu">sd</span>(population_heights)</span>
<span id="cb5-5"><a href="index.html#cb5-5" tabindex="-1"></a>)</span>
<span id="cb5-6"><a href="index.html#cb5-6" tabindex="-1"></a></span>
<span id="cb5-7"><a href="index.html#cb5-7" tabindex="-1"></a>population_stats</span></code></pre></div>
<pre><code>##      Mean        SD 
## 19.995609  4.996295</code></pre>
<p>The entire oak tree data population has a mean height of approximately 20 meters and a standard deviation of approx 5 meters. Lets see how it compares with the data sample of the oak tree heights.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="index.html#cb7-1" tabindex="-1"></a><span class="co"># Mean and standard deviation of the sample</span></span>
<span id="cb7-2"><a href="index.html#cb7-2" tabindex="-1"></a>sample_stats <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-3"><a href="index.html#cb7-3" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">mean</span>(sample_heights),</span>
<span id="cb7-4"><a href="index.html#cb7-4" tabindex="-1"></a>  <span class="at">SD =</span> <span class="fu">sd</span>(sample_heights)</span>
<span id="cb7-5"><a href="index.html#cb7-5" tabindex="-1"></a>)</span>
<span id="cb7-6"><a href="index.html#cb7-6" tabindex="-1"></a></span>
<span id="cb7-7"><a href="index.html#cb7-7" tabindex="-1"></a>sample_stats</span></code></pre></div>
<pre><code>##      Mean        SD 
## 21.094995  5.507379</code></pre>
<p>There is a minor difference between the data sample and the entire data population of the oak tree heights. As you can see the selected sample of oak trees has an average height of 21 meters and a standard deviation of 5.5 meters.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Run the code below to generate the data of soil samples collected in farm with livestock. The main objective was to find the pH of the soil.</p>
<p>Use the code below to simulate the collection of the data.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="index.html#cb9-1" tabindex="-1"></a><span class="co"># Set seed for reproducibility </span></span>
<span id="cb9-2"><a href="index.html#cb9-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb9-3"><a href="index.html#cb9-3" tabindex="-1"></a></span>
<span id="cb9-4"><a href="index.html#cb9-4" tabindex="-1"></a><span class="co"># Simulate the data collection</span></span>
<span id="cb9-5"><a href="index.html#cb9-5" tabindex="-1"></a>farm_population_pH <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">5342</span>, <span class="at">mean=</span><span class="fl">3.61</span>, <span class="at">sd=</span><span class="fl">0.8</span>)</span>
<span id="cb9-6"><a href="index.html#cb9-6" tabindex="-1"></a><span class="fu">head</span>(farm_population_pH)</span></code></pre></div>
<pre><code>## [1] 3.864037 3.471632 3.544874 3.192810 3.239502 3.724600</code></pre>
<p>You are required to work on the problems below;</p>
<ol style="list-style-type: lower-roman">
<li>What is the Mean and Standard Deviation of the pH of the entire farm population soil samples.</li>
<li>Select 65 random samples from the entire population.</li>
<li>Calculate the Mean and Standard Deviation of the sample.</li>
<li>How does the Mean and Standard deviation differ from the entire population?</li>
</ol>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Run the code below to generate the data of soil samples collected in farm with livestock. The main objective was to find the pH of the soil.</p>
<p>Use the code below to simulate the collection of the data.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="index.html#cb11-1" tabindex="-1"></a><span class="co"># Set seed for reproducibility </span></span>
<span id="cb11-2"><a href="index.html#cb11-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">76</span>)</span>
<span id="cb11-3"><a href="index.html#cb11-3" tabindex="-1"></a></span>
<span id="cb11-4"><a href="index.html#cb11-4" tabindex="-1"></a><span class="co"># Simulate the data collection</span></span>
<span id="cb11-5"><a href="index.html#cb11-5" tabindex="-1"></a>farm_population_pH <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">5342</span>, <span class="at">mean=</span><span class="fl">3.61</span>, <span class="at">sd=</span><span class="fl">0.8</span>)</span>
<span id="cb11-6"><a href="index.html#cb11-6" tabindex="-1"></a><span class="fu">head</span>(farm_population_pH)</span></code></pre></div>
<pre><code>## [1] 3.864037 3.471632 3.544874 3.192810 3.239502 3.724600</code></pre>
<p>You are required to work on the problems below;</p>
<ol style="list-style-type: lower-roman">
<li>What is the Mean and Standard Deviation of the pH of the entire farm population soil samples.</li>
</ol>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="index.html#cb13-1" tabindex="-1"></a>population_stats <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb13-2"><a href="index.html#cb13-2" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">mean</span>(farm_population_pH),</span>
<span id="cb13-3"><a href="index.html#cb13-3" tabindex="-1"></a>  <span class="at">standard_deviation =</span> <span class="fu">sd</span>(farm_population_pH)</span>
<span id="cb13-4"><a href="index.html#cb13-4" tabindex="-1"></a>)</span>
<span id="cb13-5"><a href="index.html#cb13-5" tabindex="-1"></a></span>
<span id="cb13-6"><a href="index.html#cb13-6" tabindex="-1"></a>population_stats <span class="co"># show the results</span></span></code></pre></div>
<pre><code>##               Mean standard_deviation 
##          3.6218315          0.7934042</code></pre>
<ol start="2" style="list-style-type: lower-roman">
<li>Select 65 random samples from the entire population.</li>
</ol>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="index.html#cb15-1" tabindex="-1"></a>farm_sample_pH <span class="ot">&lt;-</span> <span class="fu">sample</span>(farm_population_pH, </span>
<span id="cb15-2"><a href="index.html#cb15-2" tabindex="-1"></a>                         <span class="at">size =</span> <span class="dv">65</span>, </span>
<span id="cb15-3"><a href="index.html#cb15-3" tabindex="-1"></a>                         <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-4"><a href="index.html#cb15-4" tabindex="-1"></a><span class="fu">head</span>(farm_sample_pH)</span></code></pre></div>
<pre><code>## [1] 3.478034 4.268278 4.084203 4.044815 2.613637 3.575463</code></pre>
<ol start="3" style="list-style-type: lower-roman">
<li>Calculate the Mean and Standard Deviation of the sample.</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="index.html#cb17-1" tabindex="-1"></a>sample_stats <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb17-2"><a href="index.html#cb17-2" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">mean</span>(farm_sample_pH),</span>
<span id="cb17-3"><a href="index.html#cb17-3" tabindex="-1"></a>  <span class="at">standard_deviation =</span> (<span class="fu">sd</span>(farm_sample_pH))</span>
<span id="cb17-4"><a href="index.html#cb17-4" tabindex="-1"></a>)</span>
<span id="cb17-5"><a href="index.html#cb17-5" tabindex="-1"></a></span>
<span id="cb17-6"><a href="index.html#cb17-6" tabindex="-1"></a>sample_stats <span class="co"># show the results</span></span></code></pre></div>
<pre><code>##               Mean standard_deviation 
##          3.7237092          0.7554283</code></pre>
<ol start="4" style="list-style-type: lower-roman">
<li>How does the Mean and Standard deviation differ from the entire population?</li>
</ol>
<p><span style="color: brown;"><em>The sample mean is slightly higher than the whole population mean while the standard deviation of the whole populations is almost equal to the data sample’s standard deviation</em></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
<div id="data-distributions" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Data Distributions<a href="index.html#data-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Data Distribution</strong> describes how data values in data population are spread across the range of possible values. For instance, in our case the height of oak trees in the forest might be distributed normally, meaning that most trees cluster around the average height. Understanding data distribution is crucial in ecological analysis since it helps in;</p>
<ul>
<li>identifying patterns ( for instance seasonal changes in bird populations).</li>
<li>choosing appropriate statistical tests.</li>
<li>modelling ecological phenomena accurately.</li>
</ul>
<p>When dealing with continuous data values like height of oak trees, soil acidity or rainfall, <strong>Probability Distribution Functions</strong> is used to find the likelihood of different outcomes in a population. There are two types of probability distribution functions, namely;</p>
<ol style="list-style-type: lower-roman">
<li>Cumulative distribution function,</li>
<li>Empirical Cumulative distribution function.</li>
</ol>
<p>Below is the distribution of oak tree heights represented in a density plot.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="index.html#cb19-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-2"><a href="index.html#cb19-2" tabindex="-1"></a></span>
<span id="cb19-3"><a href="index.html#cb19-3" tabindex="-1"></a><span class="co"># Create a data frame from the data </span></span>
<span id="cb19-4"><a href="index.html#cb19-4" tabindex="-1"></a>oak_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Height =</span> population_heights)</span>
<span id="cb19-5"><a href="index.html#cb19-5" tabindex="-1"></a></span>
<span id="cb19-6"><a href="index.html#cb19-6" tabindex="-1"></a><span class="co"># Plot the density plot </span></span>
<span id="cb19-7"><a href="index.html#cb19-7" tabindex="-1"></a><span class="fu">ggplot</span>(oak_df, </span>
<span id="cb19-8"><a href="index.html#cb19-8" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Height)) <span class="sc">+</span> </span>
<span id="cb19-9"><a href="index.html#cb19-9" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb19-10"><a href="index.html#cb19-10" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-11"><a href="index.html#cb19-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribution of tree heights&quot;</span>,</span>
<span id="cb19-12"><a href="index.html#cb19-12" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tree Height(m)&quot;</span>,</span>
<span id="cb19-13"><a href="index.html#cb19-13" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Density&quot;</span></span>
<span id="cb19-14"><a href="index.html#cb19-14" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb19-15"><a href="index.html#cb19-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Above is the distribution of oak tree heights, lets find its probability using the two types of distribution functions.</p>
<p><strong>Cumulative Distribution Function</strong></p>
<p>This distribution function leans toward that a probability of a random variable is less than or equal to a certain value.</p>
<p>We can randomly select a sample of heights from a population using the following code:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="index.html#cb20-1" tabindex="-1"></a>sample_heights <span class="ot">&lt;-</span> <span class="fu">sample</span>(population_heights, <span class="at">size=</span><span class="dv">86</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="index.html#cb21-1" tabindex="-1"></a><span class="fu">tail</span>(sample_heights)</span></code></pre></div>
<pre><code>## [1] 16.77457 21.71678 21.76080 36.45259 25.02581 14.43727</code></pre>
<p>For example, if we analyze heights, the CDF could help answer:
<em>“What percentage of people have a height less than or equal to 170 cm?”</em></p>
<p>The CDF of a normal distribution can be visualized using:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="index.html#cb23-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(population_heights), <span class="fu">max</span>(population_heights), <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb23-2"><a href="index.html#cb23-2" tabindex="-1"></a>cdf_values <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(x, <span class="at">mean =</span> <span class="fu">mean</span>(population_heights), <span class="at">sd =</span> <span class="fu">sd</span>(population_heights))</span>
<span id="cb23-3"><a href="index.html#cb23-3" tabindex="-1"></a></span>
<span id="cb23-4"><a href="index.html#cb23-4" tabindex="-1"></a><span class="fu">plot</span>(x, cdf_values, <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, </span>
<span id="cb23-5"><a href="index.html#cb23-5" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Height&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Cumulative Probability&quot;</span>, </span>
<span id="cb23-6"><a href="index.html#cb23-6" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Cumulative Distribution Function (CDF)&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><strong>Empirical Cumulative Distribution Function</strong></p>
<p>The Empirical Cumulative Distribution Function (ECDF) is a way to estimate the CDF based on the actual observed data (your sample). Instead of assuming a theoretical distribution, it calculates the proportion of values that are less than or equal to each observed value in the sample.</p>
<p>Lets create an ECDF plot in R using the sample heights</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="index.html#cb24-1" tabindex="-1"></a><span class="co"># calculate CDF </span></span>
<span id="cb24-2"><a href="index.html#cb24-2" tabindex="-1"></a>CDF <span class="ot">&lt;-</span> <span class="fu">ecdf</span>(sample_heights)</span>
<span id="cb24-3"><a href="index.html#cb24-3" tabindex="-1"></a></span>
<span id="cb24-4"><a href="index.html#cb24-4" tabindex="-1"></a><span class="co"># draw the cdf plot</span></span>
<span id="cb24-5"><a href="index.html#cb24-5" tabindex="-1"></a><span class="fu">plot</span>(CDF,</span>
<span id="cb24-6"><a href="index.html#cb24-6" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Empirical Cumulative Distribution Function (ECDF)&quot;</span>, </span>
<span id="cb24-7"><a href="index.html#cb24-7" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Height&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Cumulative Probability&quot;</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>As you can see, the ECDF graph shows a step-like increase whenever a new height is encountered and the curve provides a data-driven approximation of how heights are distributed in the sample.</p>
<p>Here are the main differences between CDF(Cumulative Distribution Function) and ECDF(Empirical Cumulative Distribution Function);</p>
<ul>
<li>CDF is based on the entire population while ECDF is based on the observed sample data.</li>
<li>The shape of CDF curve is smooth while the ECDF has a step-like plot.
CDF is used to make model assumptions and probability estimates while ECDF is used to make data driven insights and explanatory analysis.</li>
</ul>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
<div id="types-of-distribution" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Types of Distribution<a href="index.html#types-of-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In statistical tests, it is assumed that the data sample represents the underlying data population. Similarly, the distribution of the data sample is assumed to be similar to the one of the data population.</p>
<p>These are what characterizes the data distribution; whether the data is;</p>
<ul>
<li>discrete or continuous</li>
<li>symmetrical or asymmetrical</li>
<li>bounded by lower and/or upper limits or unbounded.</li>
</ul>
<p>Lets discuss different types of data distributions.</p>
<div id="normal-distribution" class="section level4 hasAnchor" number="1.1.1.1">
<h4><span class="header-section-number">1.1.1.1</span> Normal distribution<a href="index.html#normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The normal distribution is a continuous symmetrical distribution in the real number domain (i.e., with the set of possible values ranging between -∞ and ∞) whose probability density function plots as a smooth bell-shaped curve, and whose
cumulative distribution is S-shaped.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>To demonstrate this, lets generate 100 random data values with a mean of 5 and a standard deviation of 3.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="index.html#cb25-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb25-2"><a href="index.html#cb25-2" tabindex="-1"></a></span>
<span id="cb25-3"><a href="index.html#cb25-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">3</span>)</span>
<span id="cb25-4"><a href="index.html#cb25-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(data)</span>
<span id="cb25-5"><a href="index.html#cb25-5" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb25-6"><a href="index.html#cb25-6" tabindex="-1"></a><span class="fu">ggplot</span>(df, </span>
<span id="cb25-7"><a href="index.html#cb25-7" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> data)) <span class="sc">+</span> </span>
<span id="cb25-8"><a href="index.html#cb25-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb25-9"><a href="index.html#cb25-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-10"><a href="index.html#cb25-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribution of data sample&quot;</span>,</span>
<span id="cb25-11"><a href="index.html#cb25-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Sample Value&quot;</span>,</span>
<span id="cb25-12"><a href="index.html#cb25-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Density&quot;</span></span>
<span id="cb25-13"><a href="index.html#cb25-13" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb25-14"><a href="index.html#cb25-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The data distribution below represents a near bell-shaped curve.</p>
<p>A normal distribution with a mean of zero and variance of 1 (or
standard deviation of 1, since standard deviation is the square root of variance and square root of 1 is 1) is referred to as a <strong>standard normal distribution</strong></p>
<p>A standard normal distribution has many applications in statistics such as computation of cumulative probabilities and critical values for hypothesis tests.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets generate a random data set that is standardized.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="index.html#cb26-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb26-2"><a href="index.html#cb26-2" tabindex="-1"></a></span>
<span id="cb26-3"><a href="index.html#cb26-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb26-4"><a href="index.html#cb26-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(data)</span>
<span id="cb26-5"><a href="index.html#cb26-5" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb26-6"><a href="index.html#cb26-6" tabindex="-1"></a><span class="fu">ggplot</span>(df, </span>
<span id="cb26-7"><a href="index.html#cb26-7" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> data)) <span class="sc">+</span> </span>
<span id="cb26-8"><a href="index.html#cb26-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb26-9"><a href="index.html#cb26-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-10"><a href="index.html#cb26-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribution of data sample&quot;</span>,</span>
<span id="cb26-11"><a href="index.html#cb26-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Sample Value&quot;</span>,</span>
<span id="cb26-12"><a href="index.html#cb26-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Density&quot;</span></span>
<span id="cb26-13"><a href="index.html#cb26-13" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb26-14"><a href="index.html#cb26-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Any data sample that follows a normal distribution can be standardized to a <em>standard normal distribution</em> by subtracting its mean from each individual data value and dividing the result by its standard deviation. The resultant values can be referred to as <em>standard score</em>, <em>normal score</em>, <em>normal quantile</em> or <em>z-value</em>)</p>
<p>Here is the formula for calculation the z-value (standardized score); <span class="math display">\[z = {{x - \overline x}\over{\sigma}}\]</span></p>
<p>Where;</p>
<ul>
<li><span class="math inline">\(x\)</span> is the actual value</li>
<li><span class="math inline">\(\overline x\)</span> is the data sample mean</li>
<li><span class="math inline">\(\sigma\)</span> is the standard deviation</li>
</ul>
<p><span style="color: orange;"><strong>Try it</strong></span></p>
<p>——————-will generate a data distribution with a known standard deviation and mean then standardize it. Will then plot both samples - raw data and the standardized one—————————-</p>
<p><span style="color: orange;"><strong>Example: CUMULATIVE AND EXCEEDANCE PROBABILITIES FOR A NORMAL DISTRIBUTION</strong></span></p>
<p>Groundwater Manganese Concentrations in mg/L</p>
<p>______________________<strong>Expand on this</strong>____________________________________</p>
<p>modify the code below to show up the distribution</p>
<pre><code>x = seq(0, 0.4, length=100)
y = dnorm(x, 0.52, 0.18)
polygon(c(0, x, 0.4), c(0, y, 0), col = &quot;gray&quot;)

# Add a shaded area 
x = seq(1, 0.9, length=25)
y = dnorm(x, 0.52, 0.18)
polygon(c(1, x, 0.9), c(0, y, 0), col = &quot;gray&quot;)
</code></pre>
<p><strong>Goodness-of-Fit (GOF) Tests for the Normal Distribution</strong></p>
<p>In parametric statistical tests, it assumed that the data is normally distributed or can be normalized by data transformation such as log transform. The parameters, such as mean and standard deviation, in parametric tests must be specified.</p>
<p>Verifying the data normality is crucial before conducting the tests. If it fails the test of normality other types of tests(non parametric) are considered. The <em>GOF</em> tests are used to access the normality of the data sample which requires 8 to 10 randomly picked data values.</p>
<p>The tests are;</p>
<ul>
<li>Normal probability plot - also known as normal quantile plot.</li>
<li>Coefficient of Variation(CV)</li>
<li>Coefficient of Skewness</li>
<li>Shapiro-Wilk(SW) and Shapiro-Francia(SF) procedures</li>
<li>Filiben’s probability plot correlation coefficient (PPCC)</li>
<li>Shapiro-Wilk multiple group normality</li>
</ul>
<p>The CV test is the most commonly used method. It is computed simply by dividing the standard deviation by the mean. If the resultant value is greater than 1 then the data fails the normality test, otherwise it passes. <span class="math display">\[CV = {\sigma\over{\overline x}}\]</span></p>
<p>Other GOF tests that are used in testing for normal and other distributions are Anderson–Darling (AD) test and the Lilliefors–Kolmogorov–Smirnov test</p>
<p>The Coefficient of Skewness stated above provides a more direct measure of skewness where skewness of the magnitude of greater than 0.5 is considered moderate to the substantial degree of skewness.</p>
<p>——————————<strong>Add an example</strong>————————</p>
<p><strong>Central Limit Theorem</strong></p>
<p>____________________simplify it with an example _________________________</p>
</div>
<div id="lognormal-gamma-and-other-continuous-distributions" class="section level4 hasAnchor" number="1.1.1.2">
<h4><span class="header-section-number">1.1.1.2</span> Lognormal, Gamma, and Other Continuous Distributions<a href="index.html#lognormal-gamma-and-other-continuous-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Before we dive into Gamma distribution, we need to to get the definition of exponential distribution. <strong>Exponential distribution</strong> is the probability of the waiting time between events in a <em>Poisson Process</em>.</p>
<p>Imagine you’re analyzing environmental data, such as soil contamination levels or water flow rates. Often, these values are not normally distributed because they can’t be negative and tend to have a few extremely high values. This is where the lognormal distribution comes in—it describes data whose logarithms follow a normal distribution. For example, if you take the natural logarithm of highly skewed mercury concentration values, their distribution becomes nearly normal, making statistical analysis easier. However, when back-transforming results, the arithmetic mean can be underestimated, leading to what’s called transformation bias—but the median, often equal to the geometric mean, provides a useful estimate. Aside from lognormal, environmental studies frequently rely on other distributions such as gamma, logistic, and uniform, each useful in different scenarios. The gamma distribution, for instance, is often applied to model waiting times or rainfall amounts, offering flexibility through its shape and scale parameters. Understanding these distributions allows us to apply the right statistical methods, improve predictions, and make sense of complex real-world data patterns effectively.</p>
<p>Lets dive deep into each type of the distribution mentioned</p>
<p><strong>Gamma Distribution</strong></p>
<p>Exponential infers the probability until the first event happens while Gamma distribution gives us the probability of the waiting time until the <span class="math inline">\(n^{th}\)</span> event.</p>
<p>The gamma distribution is bounded by zero on the left (no negative values) and can stretch infinitely to the right, making it suitable for data that exhibit long right tails. It is a powerful tool for modeling real-world data that is positively skewed, such as rainfall amounts, insurance claims, and even environmental contaminant levels.</p>
<p>When dealing with skewed data, both the <strong>lognormal</strong> and <strong>gamma</strong> distributions are commonly used. However, the gamma distribution has an advantage: it avoids the pitfalls of <strong>transformation bias</strong>, which can arise when converting data back from logarithmic scales to the original scale.</p>
<p>The gamma distribution is controlled by two key parameters:</p>
<ul>
<li><em>Shape parameter (k)</em> – Determines the shape of the distribution. A higher k makes the distribution look more like a normal distribution.</li>
<li><em>Scale parameter (θ)</em> – Controls the spread or range of the distribution.</li>
</ul>
<p>Want to see how these parameters influence the distribution? Let’s generate some random data and visualize it!</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="index.html#cb28-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb28-2"><a href="index.html#cb28-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-3"><a href="index.html#cb28-3" tabindex="-1"></a></span>
<span id="cb28-4"><a href="index.html#cb28-4" tabindex="-1"></a><span class="co"># Generate random data from a gamma distribution</span></span>
<span id="cb28-5"><a href="index.html#cb28-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)  <span class="co"># Ensures reproducibility</span></span>
<span id="cb28-6"><a href="index.html#cb28-6" tabindex="-1"></a>gamma_data <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1000</span>, <span class="at">shape =</span> <span class="dv">5</span>, <span class="at">scale =</span> <span class="dv">2</span>)</span>
<span id="cb28-7"><a href="index.html#cb28-7" tabindex="-1"></a></span>
<span id="cb28-8"><a href="index.html#cb28-8" tabindex="-1"></a><span class="co"># Visualize the data distribution</span></span>
<span id="cb28-9"><a href="index.html#cb28-9" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(gamma_data), <span class="fu">aes</span>(<span class="at">x =</span> gamma_data)) <span class="sc">+</span></span>
<span id="cb28-10"><a href="index.html#cb28-10" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb28-11"><a href="index.html#cb28-11" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Gamma-Distributed Data&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-12"><a href="index.html#cb28-12" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-13"><a href="index.html#cb28-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><span style="color: orange;"><strong>Try it</strong></span></p>
<p>Try tweaking the shape and scale values in the code above to see how they affect the distribution.</p>
<ul>
<li>Increase the shape parameter (k) to see how the distribution approaches normality.</li>
<li>Reduce the scale parameter (θ) to create a sharper peak.</li>
</ul>
<p>Want to check if your data follows a gamma distribution? You can perform Goodness-of-Fit (GOF) tests using the <code>fitdistrplus</code> package in R.</p>
<p>The package is installed by:</p>
<pre><code>install.packages(&quot;fitdistrplus&quot;)</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="index.html#cb30-1" tabindex="-1"></a><span class="fu">library</span>(fitdistrplus)</span></code></pre></div>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="index.html#cb33-1" tabindex="-1"></a><span class="co"># Fit a gamma distribution to the data</span></span>
<span id="cb33-2"><a href="index.html#cb33-2" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">fitdist</span>(gamma_data, <span class="st">&quot;gamma&quot;</span>)</span>
<span id="cb33-3"><a href="index.html#cb33-3" tabindex="-1"></a></span>
<span id="cb33-4"><a href="index.html#cb33-4" tabindex="-1"></a><span class="co"># Print summary of the fit</span></span>
<span id="cb33-5"><a href="index.html#cb33-5" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## Fitting of the distribution &#39; gamma &#39; by maximum likelihood 
## Parameters : 
##       estimate Std. Error
## shape 4.851288 0.20991639
## rate  0.491825 0.02242213
## Loglikelihood:  -2845.914   AIC:  5695.827   BIC:  5705.643 
## Correlation matrix:
##           shape      rate
## shape 1.0000000 0.9491175
## rate  0.9491175 1.0000000</code></pre>
<p>The gamma distribution is an excellent choice for modeling skewed data, offering flexibility and reliable statistical methods without the transformation bias of lognormal distributions. By experimenting with different parameters and visualizing the results, you can better understand its applications in environmental science, finance, and beyond!</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
<p><strong>Logistic Distribution</strong></p>
<p>The logistic distribution, like the normal distribution, is symmetric and unbounded. However, it differs in having <strong>fatter tails</strong>, meaning it contains more extreme values on both sides. This makes it useful in various fields, such as:</p>
<ul>
<li><em>Logistic regression</em>, where it models binary outcomes (e.g., success/failure).</li>
<li><em>Ecological modeling</em>, where population growth follows an S-shaped logistic curve.</li>
<li><em>Machine learning</em>, for classification problems.</li>
</ul>
<p>The image below shows the slight difference between the logistic and normal distribution
<img src="images/lognormal-distribution.png" /></p>
<p>Here are the key characteristics of lognormal distribution;</p>
<ul>
<li><em>Symmetry:</em> Centered around a location parameter (mean).</li>
<li><em>Scale Parameter:</em> Determines the spread, similar to the standard deviation in normal distribution.</li>
<li><em>Fat Tails:</em> Greater occurrence of extreme values compared to the normal distribution.</li>
</ul>
<p>The cumulative distribution function (CDF) of the logistic distribution resembles the logistic function:
<span class="math display">\[{P(t)}={{e^t}\over{1 + e^t}}\]</span>
In logistic regression, the probability of success is expressed as:
<span class="math display">\[{\pi(x)}={{e^{(b_0 +b_1x)}}\over{1+e^{(b_0+b_1x)}}}\]</span>
The <em>logit function</em>, which serves as the response variable in logistic regression, defined as;
<span class="math display">\[{log({{\pi(x)}\over{1-\pi(x)}})}={b_0 + b_1x}\]</span></p>
<p><span style="color: orange;"><strong>Try it</strong></span></p>
<p>Let’s generate some logistic-distributed data and compare it with the normal distribution to understand their differences.</p>
<p>The below one is a logistic distribution</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="index.html#cb35-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb35-2"><a href="index.html#cb35-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb35-3"><a href="index.html#cb35-3" tabindex="-1"></a></span>
<span id="cb35-4"><a href="index.html#cb35-4" tabindex="-1"></a><span class="co"># Generate random data from the logistic distribution</span></span>
<span id="cb35-5"><a href="index.html#cb35-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)  <span class="co"># Ensures reproducibility</span></span>
<span id="cb35-6"><a href="index.html#cb35-6" tabindex="-1"></a>logistic_data <span class="ot">&lt;-</span> <span class="fu">rlogis</span>(<span class="dv">1000</span>, <span class="at">location =</span> <span class="dv">0</span>, <span class="at">scale =</span> <span class="dv">1</span>)</span>
<span id="cb35-7"><a href="index.html#cb35-7" tabindex="-1"></a></span>
<span id="cb35-8"><a href="index.html#cb35-8" tabindex="-1"></a><span class="co"># Visualize the data distribution</span></span>
<span id="cb35-9"><a href="index.html#cb35-9" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(logistic_data), <span class="fu">aes</span>(<span class="at">x =</span> logistic_data)) <span class="sc">+</span></span>
<span id="cb35-10"><a href="index.html#cb35-10" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">fill =</span> <span class="st">&quot;lightcoral&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb35-11"><a href="index.html#cb35-11" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of Logistic-Distributed Data&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-12"><a href="index.html#cb35-12" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Values&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-13"><a href="index.html#cb35-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Now let’s compare their probability density functions (PDFs).</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="index.html#cb36-1" tabindex="-1"></a><span class="co"># Define x-axis range</span></span>
<span id="cb36-2"><a href="index.html#cb36-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">300</span>)</span>
<span id="cb36-3"><a href="index.html#cb36-3" tabindex="-1"></a></span>
<span id="cb36-4"><a href="index.html#cb36-4" tabindex="-1"></a><span class="co"># Compute density for normal and logistic distributions</span></span>
<span id="cb36-5"><a href="index.html#cb36-5" tabindex="-1"></a>normal_density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb36-6"><a href="index.html#cb36-6" tabindex="-1"></a>logistic_density <span class="ot">&lt;-</span> <span class="fu">dlogis</span>(x, <span class="at">location =</span> <span class="dv">0</span>, <span class="at">scale =</span> <span class="dv">1</span>)</span>
<span id="cb36-7"><a href="index.html#cb36-7" tabindex="-1"></a></span>
<span id="cb36-8"><a href="index.html#cb36-8" tabindex="-1"></a><span class="co"># Plot the distributions</span></span>
<span id="cb36-9"><a href="index.html#cb36-9" tabindex="-1"></a><span class="fu">plot</span>(x, normal_density, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, </span>
<span id="cb36-10"><a href="index.html#cb36-10" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Density&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;x&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Normal vs Logistic Distribution&quot;</span>)</span>
<span id="cb36-11"><a href="index.html#cb36-11" tabindex="-1"></a><span class="fu">lines</span>(x, logistic_density, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb36-12"><a href="index.html#cb36-12" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;Normal Distribution&quot;</span>, <span class="st">&quot;Logistic Distribution&quot;</span>),</span>
<span id="cb36-13"><a href="index.html#cb36-13" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>You can try experiment with different location and scale parameters in the above code to see how the logistic distribution changes. Location is changes to shift the distribution left and right while the scale is increased to make the distribution spread out more.</p>
<p>Want to see logistic regression in action? Here’s a quick example of modeling a binary outcome.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="index.html#cb37-1" tabindex="-1"></a><span class="co"># Simulating data</span></span>
<span id="cb37-2"><a href="index.html#cb37-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb37-3"><a href="index.html#cb37-3" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb37-4"><a href="index.html#cb37-4" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">100</span>, <span class="dv">1</span>, <span class="fu">plogis</span>(<span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">1.2</span> <span class="sc">*</span> x))  <span class="co"># Logistic function</span></span>
<span id="cb37-5"><a href="index.html#cb37-5" tabindex="-1"></a></span>
<span id="cb37-6"><a href="index.html#cb37-6" tabindex="-1"></a><span class="co"># Fit logistic regression</span></span>
<span id="cb37-7"><a href="index.html#cb37-7" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">family =</span> binomial)</span>
<span id="cb37-8"><a href="index.html#cb37-8" tabindex="-1"></a></span>
<span id="cb37-9"><a href="index.html#cb37-9" tabindex="-1"></a><span class="co"># Summary of model</span></span>
<span id="cb37-10"><a href="index.html#cb37-10" tabindex="-1"></a><span class="fu">summary</span>(logistic_model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x, family = binomial)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.2892     0.2357   1.227     0.22    
## x             1.3348     0.3044   4.385 1.16e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 136.66  on 99  degrees of freedom
## Residual deviance: 107.25  on 98  degrees of freedom
## AIC: 111.25
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The logistic distribution is a powerful tool for modeling data with skewed distributions and binary outcomes. Understanding its properties, generating data, and visualizing it interactively can provide valuable insights, especially in fields like statistics, machine learning, and population modeling.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
<ul>
<li><strong>Other Continuous Distributions</strong></li>
</ul>
<p>Other types of continuous distributions include;</p>
<ul>
<li><em>Uniform distribution:</em> is appropriate when the only available data consists of the minimum value and maximum value . All values within this range have an equal probability of occurring, meaning the probability density function (PDF) is constant at within the interval , and zero elsewhere.</li>
<li><em>Triangular distribution:</em> is suitable when the minimum value , maximum value , and most likely value are known. This distribution assumes that values increase linearly from to the peak , and then decrease linearly to.</li>
</ul>
<pre><code>install.packages(&quot;triangle&quot;)
library(triangle)</code></pre>
<ul>
<li><em>Extreme Value distributions:</em> Extreme value distributions model the smallest or largest values in a dataset. A common example is analyzing annual peak streamflow rates at a monitoring station to estimate flood magnitudes expected within a specific period (e.g., 50-year or 100-year floods).</li>
</ul>
<p>One commonly used extreme value distribution is the Log-Pearson Type III distribution, which is right-skewed and bounded on the left by zero (since negative values are not possible). This distribution is widely used in flood frequency analysis and is related to the gamma distribution.</p>
<p>For analyzing low flow values, distributions such as the Weibull and Gumbel distributions are commonly employed. These distributions are particularly useful for estimating probabilities of extreme low flow conditions over time.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p><span style="color: green;"><strong>Practical Exercise!</strong></span></p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="distributions-used-in-inferential-statistics" class="section level4 hasAnchor" number="1.1.1.3">
<h4><span class="header-section-number">1.1.1.3</span> Distributions Used in Inferential Statistics<a href="index.html#distributions-used-in-inferential-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When the sample size is large (typically ≥30) and the data are not highly skewed (skewness coefficient ≤ 0.5 or 1), the <strong>central limit theorem</strong> allows for approximate normality, enabling extrapolations from sample statistics to population parameters. However, for smaller samples—common in environmental data—or when the population standard deviation is unknown, <strong>exact sampling theory</strong> is preferred, leading to the use of distributions like <strong>Student’s t, chi-square</strong>, and <strong>F distributions</strong>. These distributions are essential for <strong>statistical inference</strong>, including confidence interval estimation, hypothesis testing for population means, and significance tests for regression coefficients.</p>
<div id="students-t-distribution" class="section level5 hasAnchor" number="1.1.1.3.1">
<h5><span class="header-section-number">1.1.1.3.1</span> <strong>Student’s t Distribution</strong><a href="index.html#students-t-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>This type of distribution is essential for inference when the population standard deviation is unknown. The t-distribution is used for hypothesis testing, confidence intervals, and regression analysis, among other applications.</p>
<p>Given a random sample <span class="math inline">\(x_1,x2,...,x_n\)</span> from a normal distribution with an unknown mean and standard deviation , the t-statistic is given by:
<span class="math display">\[t = {{x-\overline X}\over{s/\sqrt n}}\]</span>
Where:</p>
<ul>
<li><span class="math inline">\(x\)</span> is the new observation</li>
<li><span class="math inline">\(\overline X\)</span> is the sample mean</li>
<li><span class="math inline">\(s\)</span> is the sample standard deviation</li>
<li><span class="math inline">\(n\)</span> is the sample size</li>
</ul>
<p>It can be used in ecology to;</p>
<ul>
<li>Compare species populations – if the two populations have the same mean</li>
<li>Assessing biodiversity changes – like before and fater habitat restoration differs significantly</li>
<li>Analyzing environmental variables – like poullution levels between two forests areas differs.</li>
</ul>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>We will investigate difference in tree heights in a forested area.</p>
<ul>
<li>Generationg and plotting t-distribution</li>
</ul>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="index.html#cb40-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb40-2"><a href="index.html#cb40-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-3"><a href="index.html#cb40-3" tabindex="-1"></a></span>
<span id="cb40-4"><a href="index.html#cb40-4" tabindex="-1"></a><span class="co"># Define x values</span></span>
<span id="cb40-5"><a href="index.html#cb40-5" tabindex="-1"></a>t_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb40-6"><a href="index.html#cb40-6" tabindex="-1"></a></span>
<span id="cb40-7"><a href="index.html#cb40-7" tabindex="-1"></a><span class="co"># Compute density for different degrees of freedom</span></span>
<span id="cb40-8"><a href="index.html#cb40-8" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">dt</span>(t_values, <span class="at">df=</span><span class="dv">2</span>)</span>
<span id="cb40-9"><a href="index.html#cb40-9" tabindex="-1"></a>df12 <span class="ot">&lt;-</span> <span class="fu">dt</span>(t_values, <span class="at">df=</span><span class="dv">12</span>)</span>
<span id="cb40-10"><a href="index.html#cb40-10" tabindex="-1"></a>norm <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(t_values) <span class="co"># Standard normal</span></span>
<span id="cb40-11"><a href="index.html#cb40-11" tabindex="-1"></a></span>
<span id="cb40-12"><a href="index.html#cb40-12" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>t_values, <span class="at">StdNormal=</span>norm, <span class="at">df2=</span>df2, <span class="at">df12=</span>df12)</span>
<span id="cb40-13"><a href="index.html#cb40-13" tabindex="-1"></a></span>
<span id="cb40-14"><a href="index.html#cb40-14" tabindex="-1"></a><span class="co"># Plot the distributions</span></span>
<span id="cb40-15"><a href="index.html#cb40-15" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>x)) <span class="sc">+</span></span>
<span id="cb40-16"><a href="index.html#cb40-16" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>StdNormal, <span class="at">linetype=</span><span class="st">&quot;Std Normal&quot;</span>)) <span class="sc">+</span></span>
<span id="cb40-17"><a href="index.html#cb40-17" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>df2, <span class="at">linetype=</span><span class="st">&quot;t, df = 2&quot;</span>)) <span class="sc">+</span></span>
<span id="cb40-18"><a href="index.html#cb40-18" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>df12, <span class="at">linetype=</span><span class="st">&quot;t, df = 12&quot;</span>)) <span class="sc">+</span></span>
<span id="cb40-19"><a href="index.html#cb40-19" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;Probability Density&quot;</span>, <span class="at">x=</span><span class="st">&quot;t values&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-20"><a href="index.html#cb40-20" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="st">&quot;&quot;</span>, <span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;solid&quot;</span>, <span class="st">&quot;dashed&quot;</span>, <span class="st">&quot;dotdash&quot;</span>)) <span class="sc">+</span></span>
<span id="cb40-21"><a href="index.html#cb40-21" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<ul>
<li>Perform two sample t-test</li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="index.html#cb41-1" tabindex="-1"></a><span class="co"># Sample data (species richness in two forest areas)</span></span>
<span id="cb41-2"><a href="index.html#cb41-2" tabindex="-1"></a>area_A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">25</span>, <span class="dv">27</span>, <span class="dv">30</span>, <span class="dv">28</span>, <span class="dv">26</span>, <span class="dv">29</span>, <span class="dv">31</span>)</span>
<span id="cb41-3"><a href="index.html#cb41-3" tabindex="-1"></a>area_B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">22</span>, <span class="dv">24</span>, <span class="dv">21</span>, <span class="dv">23</span>, <span class="dv">22</span>, <span class="dv">25</span>)</span>
<span id="cb41-4"><a href="index.html#cb41-4" tabindex="-1"></a></span>
<span id="cb41-5"><a href="index.html#cb41-5" tabindex="-1"></a><span class="co"># Perform two-sample t-test</span></span>
<span id="cb41-6"><a href="index.html#cb41-6" tabindex="-1"></a><span class="fu">t.test</span>(area_A, area_B, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  area_A and area_B
## t = 4.558, df = 14, p-value = 0.0004468
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.845765 7.904235
## sample estimates:
## mean of x mean of y 
##    27.375    22.000</code></pre>
<p>Lets now visualize the critical regions in the t-distributions</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="index.html#cb43-1" tabindex="-1"></a><span class="co"># Define x values</span></span>
<span id="cb43-2"><a href="index.html#cb43-2" tabindex="-1"></a>x_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length=</span><span class="dv">200</span>)</span>
<span id="cb43-3"><a href="index.html#cb43-3" tabindex="-1"></a>y_vals <span class="ot">&lt;-</span> <span class="fu">dt</span>(x_vals, <span class="at">df=</span><span class="dv">10</span>)</span>
<span id="cb43-4"><a href="index.html#cb43-4" tabindex="-1"></a></span>
<span id="cb43-5"><a href="index.html#cb43-5" tabindex="-1"></a><span class="co"># Critical region (alpha = 0.05, two-tailed)</span></span>
<span id="cb43-6"><a href="index.html#cb43-6" tabindex="-1"></a>critical_val <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df=</span><span class="dv">10</span>)</span>
<span id="cb43-7"><a href="index.html#cb43-7" tabindex="-1"></a></span>
<span id="cb43-8"><a href="index.html#cb43-8" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb43-9"><a href="index.html#cb43-9" tabindex="-1"></a><span class="fu">plot</span>(x_vals, y_vals, <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Probability Density&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;t values&quot;</span>, <span class="at">main=</span><span class="st">&quot;t-Distribution with Critical Regions&quot;</span>)</span>
<span id="cb43-10"><a href="index.html#cb43-10" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">c</span>(<span class="sc">-</span>critical_val, critical_val), <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>This will help you with the interpretation</p>
<ul>
<li>Compares the t-distribution with different degrees of freedom to the normal distribution. The t-distribution has heavier tails for small degrees of freedom.</li>
<li>One-Sample t-Test: Tests if the mean tree height significantly differs from 14m.</li>
<li>Two-Sample t-Test: Tests if species richness significantly differs between two areas.</li>
<li>Critical Region Visualization: Shows rejection regions for hypothesis testing.</li>
</ul>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="chi-square-distribution" class="section level5 hasAnchor" number="1.1.1.3.2">
<h5><span class="header-section-number">1.1.1.3.2</span> <strong>Chi-Square Distribution</strong><a href="index.html#chi-square-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The Chi-square(<span class="math inline">\(x^2\)</span>) distribution is widely used in ecological research for analyzing categorical data and testing statistical hypotheses. Many ecological studies involve count data, presence-absence data, or species distribution models, where the Chi-square test provides insights into species interactions, habitat preferences, and environmental associations.</p>
<p>This type of chi-square distribution arises when we sum the squares of independent standard normal variables.</p>
<p>In ecology, chi-square distribution may be used to analyze species-habitat relationships and species interactions.</p>
<p><span style="color: brown;"><strong>Try it!</strong></span></p>
<p>We will analyze the presence and absence of species A in a habitat in a contingency table.</p>
<p>Null Hypothesis - Species A’s occurrence is independent of habitat type
Alternative Hypothesis - Species A prefers a particular habitat</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="index.html#cb44-1" tabindex="-1"></a><span class="co"># Create contingency table</span></span>
<span id="cb44-2"><a href="index.html#cb44-2" tabindex="-1"></a>species_habitat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">20</span>, <span class="dv">15</span>, <span class="dv">35</span>), <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb44-3"><a href="index.html#cb44-3" tabindex="-1"></a><span class="fu">colnames</span>(species_habitat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Present&quot;</span>, <span class="st">&quot;Absent&quot;</span>)</span>
<span id="cb44-4"><a href="index.html#cb44-4" tabindex="-1"></a><span class="fu">rownames</span>(species_habitat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Forest&quot;</span>, <span class="st">&quot;Grassland&quot;</span>)</span>
<span id="cb44-5"><a href="index.html#cb44-5" tabindex="-1"></a></span>
<span id="cb44-6"><a href="index.html#cb44-6" tabindex="-1"></a><span class="co"># Perform Chi-square test</span></span>
<span id="cb44-7"><a href="index.html#cb44-7" tabindex="-1"></a><span class="fu">chisq.test</span>(species_habitat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  species_habitat
## X-squared = 7.9192, df = 1, p-value = 0.004891</code></pre>
<p>The p-value is way below 0.05 therefore we reject the null hypothesis. We have enough evidence to conclude that Species A prefers a particular habitat.</p>
<p>Lets repeat the analysis with observed and expected bird counts on different wetland sites. We will use goodness-of-fit test</p>
<p>Null hypothesis - Birds are evenly distributed.
Alternate hypothesis - Birds are not evenly distributed.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="index.html#cb46-1" tabindex="-1"></a><span class="co"># Observed and expected bird counts</span></span>
<span id="cb46-2"><a href="index.html#cb46-2" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">55</span>, <span class="dv">60</span>, <span class="dv">40</span>)</span>
<span id="cb46-3"><a href="index.html#cb46-3" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">50</span>, <span class="dv">50</span>, <span class="dv">50</span>)</span>
<span id="cb46-4"><a href="index.html#cb46-4" tabindex="-1"></a></span>
<span id="cb46-5"><a href="index.html#cb46-5" tabindex="-1"></a><span class="co"># Perform Chi-square goodness-of-fit test</span></span>
<span id="cb46-6"><a href="index.html#cb46-6" tabindex="-1"></a><span class="fu">chisq.test</span>(observed, <span class="at">p =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>, <span class="dv">4</span>)) <span class="co"># Equal probability across sites</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed
## X-squared = 5, df = 3, p-value = 0.1718</code></pre>
<p>p-value is above 0.05 therefore we conclude that the birds are evenly distributed.</p>
<p>The chi-square distribution is used to construct confidence intervals for variance estimates such as error variance in ecological regression models.</p>
<p>The F-distributions, which is the ration of two chi-square distributions is used in ANOVA tests for comparing species abundance across multiple environmental conditions.</p>
<p>Lets perform an example to demonstrate this</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="index.html#cb48-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))  </span>
<span id="cb48-2"><a href="index.html#cb48-2" tabindex="-1"></a></span>
<span id="cb48-3"><a href="index.html#cb48-3" tabindex="-1"></a><span class="co"># Chi-square distribution for different degrees of freedom</span></span>
<span id="cb48-4"><a href="index.html#cb48-4" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dchisq</span>(x, <span class="at">df=</span><span class="dv">2</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">10</span>, <span class="at">ylab=</span><span class="st">&quot;Probability density&quot;</span>, </span>
<span id="cb48-5"><a href="index.html#cb48-5" tabindex="-1"></a>      <span class="at">main=</span><span class="st">&quot;Chi-square Distributions in Ecology&quot;</span>, <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb48-6"><a href="index.html#cb48-6" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dchisq</span>(x, <span class="at">df=</span><span class="dv">5</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">10</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb48-7"><a href="index.html#cb48-7" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dchisq</span>(x, <span class="at">df=</span><span class="dv">10</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">10</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb48-8"><a href="index.html#cb48-8" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;df = 2&quot;</span>, <span class="st">&quot;df = 5&quot;</span>, <span class="st">&quot;df = 10&quot;</span>), </span>
<span id="cb48-9"><a href="index.html#cb48-9" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb48-10"><a href="index.html#cb48-10" tabindex="-1"></a></span>
<span id="cb48-11"><a href="index.html#cb48-11" tabindex="-1"></a><span class="co"># F-distribution for different df values</span></span>
<span id="cb48-12"><a href="index.html#cb48-12" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x, <span class="at">df1=</span><span class="dv">1</span>, <span class="at">df2=</span><span class="dv">10</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">ylab=</span><span class="st">&quot;Probability density&quot;</span>, </span>
<span id="cb48-13"><a href="index.html#cb48-13" tabindex="-1"></a>      <span class="at">main=</span><span class="st">&quot;F Distributions in Ecology&quot;</span>, <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb48-14"><a href="index.html#cb48-14" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x, <span class="at">df1=</span><span class="dv">6</span>, <span class="at">df2=</span><span class="dv">60</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb48-15"><a href="index.html#cb48-15" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x, <span class="at">df1=</span><span class="dv">10</span>, <span class="at">df2=</span><span class="dv">100</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb48-16"><a href="index.html#cb48-16" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;df1 = 1, df2 = 10&quot;</span>, <span class="st">&quot;df1 = 6, df2 = 60&quot;</span>, <span class="st">&quot;df1 = 10, df2 = 100&quot;</span>), </span>
<span id="cb48-17"><a href="index.html#cb48-17" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
<div id="f-distribution" class="section level5 hasAnchor" number="1.1.1.3.3">
<h5><span class="header-section-number">1.1.1.3.3</span> <strong>F Distribution</strong><a href="index.html#f-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The F-distribution, named after the British statistician <strong>Ronald Fisher</strong>, is commonly used in ecological studies for testing hypotheses involving variance and regression models. It is the distribution of the <strong>F-statistic</strong>, which is computed as the ratio of two chi-square distributed variables, each normalized by their respective degrees of freedom.</p>
<p>Mathematically, the F-statistic is expressed as:</p>
<p><span class="math display">\[F = {{X_{k1}^2/k1}\over{X_{k2}^2/k2}}\]</span>
where:</p>
<ul>
<li><span class="math inline">\(X_{k1}^2/k1\)</span> is a chi-square distributed variable with <span class="math inline">\(k1\)</span> degrees of freedom,</li>
<li><span class="math inline">\(X_{k1}^2/k1\)</span> is anothe chi-square distributed variable with <span class="math inline">\(k2\)</span> degress of freedom</li>
</ul>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets visualize F-distribution in Ecology</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="index.html#cb49-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))  </span>
<span id="cb49-2"><a href="index.html#cb49-2" tabindex="-1"></a></span>
<span id="cb49-3"><a href="index.html#cb49-3" tabindex="-1"></a><span class="co"># F-distributions for different degrees of freedom</span></span>
<span id="cb49-4"><a href="index.html#cb49-4" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x, <span class="at">df1=</span><span class="dv">1</span>, <span class="at">df2=</span><span class="dv">10</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">ylab=</span><span class="st">&quot;Probability Density&quot;</span>, </span>
<span id="cb49-5"><a href="index.html#cb49-5" tabindex="-1"></a>      <span class="at">main=</span><span class="st">&quot;F Distribution in Ecology&quot;</span>, <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb49-6"><a href="index.html#cb49-6" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x, <span class="at">df1=</span><span class="dv">6</span>, <span class="at">df2=</span><span class="dv">60</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb49-7"><a href="index.html#cb49-7" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">df</span>(x, <span class="at">df1=</span><span class="dv">10</span>, <span class="at">df2=</span><span class="dv">100</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb49-8"><a href="index.html#cb49-8" tabindex="-1"></a></span>
<span id="cb49-9"><a href="index.html#cb49-9" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;df1 = 1, df2 = 10&quot;</span>, <span class="st">&quot;df1 = 6, df2 = 60&quot;</span>, <span class="st">&quot;df1 = 10, df2 = 100&quot;</span>), </span>
<span id="cb49-10"><a href="index.html#cb49-10" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>As df1 and df2 increase, the F-distribution becomes less-skewed and more bell-shaped.</p>
</div>
</div>
<div id="dicrete-distributions" class="section level4 hasAnchor" number="1.1.1.4">
<h4><span class="header-section-number">1.1.1.4</span> Dicrete Distributions<a href="index.html#dicrete-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A random variable is considered discrete if it takes only whole-number values, rather than fractions (for example, a class cannot have 10.5 students). Discrete data include both count data and categorical or qualitative data, such as whether an organism is present or absent or whether a value exceeds a control limit. Two commonly used distributions for modeling discrete data are the binomial distribution, which applies to categorical data, and the Poisson distribution, which is used for count data.</p>
<div id="binomial-distribution" class="section level5 hasAnchor" number="1.1.1.4.1">
<h5><span class="header-section-number">1.1.1.4.1</span> <strong>Binomial Distribution</strong><a href="index.html#binomial-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The binomial distribution models the number of successes in a fixed number of independent trials, where each trial has only two possible outcomes: success (1) or failure (0).</p>
<p>Imagine we are testing 20 groundwater monitoring wells for a contaminant. Each well either detects the contaminant (success) or does not detect it (failure). For instance;</p>
<ul>
<li>Probability of detecting the contaminant (success): p = 0.4</li>
<li>Probability of not detecting the contaminant (failure): q = 1 - p = 0.6</li>
</ul>
<p>The probability of getting exactly successes in n trials is given by:</p>
<p><span class="math display">\[{P(X=k)}={\begin{pmatrix} n \\ k \end{pmatrix}p^k(1-p)^{n-k}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\({\begin{pmatrix} n \\ k \end{pmatrix}}={{n!}\over{k!(n-k)!}}\)</span> is the binomial coefficient.</li>
<li><span class="math inline">\(p\)</span> is the probability of success.</li>
<li><span class="math inline">\((1-p)\)</span> is the probability of failure.</li>
<li><span class="math inline">\(k\)</span> is the number of successes.</li>
</ul>
<p>For a Binomial(n, p) distributions:</p>
<ul>
<li><p>Mean(Expected Value):
<span class="math display">\[E(X) = np\]</span>
This tells us the average of successes over many trials.</p></li>
<li><p>Variance
<span class="math display">\[\sigma^2 = np(1-p)\]</span></p></li>
<li><p>Standard deviation
<span class="math display">\[\sigma = \sqrt{np(1-p)}\]</span></p></li>
</ul>
<p>In this case, for our groundwater monitoring example</p>
<ul>
<li>Expected Value: <span class="math inline">\(E(X) = 20 X 0.4 = 8\)</span></li>
<li>Standard Deviation
<span class="math display">\[\sigma = \sqrt{20 x 0.4 X 0.6} = \sqrt {4.8} = 2.19\]</span></li>
</ul>
<p>Lets apply R for this example of groundwater contamination. R provides four main functions to work with the binomial distribution:</p>
<ul>
<li><code>dbinom(x, size, prob)</code>: Computes <span class="math inline">\(P(X=x\)</span>, the probability of exactly <strong>x</strong> successes.</li>
<li><code>pbinom(x, size, prob)</code>: Computes <span class="math inline">\(P(\geq x)\)</span>, the cumulative probability.</li>
<li><code>qbinom(p, size, prob)</code>: Computes the quantile for a given probability.</li>
<li><code>rbinom(n, size, prob)</code>: Generates random binomial values (simulating real-world experiments)</li>
</ul>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets simulate binomial outcomes</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="index.html#cb50-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb50-2"><a href="index.html#cb50-2" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="dv">10</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="fl">0.4</span>) </span></code></pre></div>
<pre><code>##  [1]  7 10  7 11 11  4  8 11  8  8</code></pre>
<p>This simulates 10 trials where we sample 20 wells each time, and each well has a 40% chance of detecting the contaminant.</p>
<p>Lets try the probability of detecting the contaminant in exactly 9 wells</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="index.html#cb52-1" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">9</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="fl">0.4</span>)</span></code></pre></div>
<pre><code>## [1] 0.1597385</code></pre>
<p>This means there’s a 15.97% chance that exactly 9 out of 20 wells will detect the contaminant.</p>
<p>Now lets try the Probability of Detecting the Contaminant in 9 or Fewer Wells to find the cumulative probability of detecting the contaminant in at most 9 wells.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="index.html#cb54-1" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">9</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="fl">0.4</span>)</span></code></pre></div>
<pre><code>## [1] 0.7553372</code></pre>
<p>Lets plot it</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="index.html#cb56-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">lend =</span> <span class="dv">2</span>)  <span class="co"># Adjust bar ends</span></span>
<span id="cb56-2"><a href="index.html#cb56-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">15</span>, <span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">15</span>, <span class="dv">20</span>, <span class="fl">0.4</span>), <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">lwd =</span> <span class="dv">6</span>,</span>
<span id="cb56-3"><a href="index.html#cb56-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;# of Wells with Contaminant&quot;</span>, </span>
<span id="cb56-4"><a href="index.html#cb56-4" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability&quot;</span>,</span>
<span id="cb56-5"><a href="index.html#cb56-5" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Binomial Distribution (n=20, p=0.4)&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>From the graph;</p>
<ul>
<li>The most probable outcome is finding the contaminant in 8 wells.</li>
<li>Extreme values (0 or 15 wells detecting contaminants) are very unlikely.</li>
</ul>
<p><strong>What if?</strong></p>
<p>When we increase n (e.g., testing 100 wells instead of 20), the distribution becomes smoother and begins to resemble a normal distribution.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="index.html#cb57-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">40</span>, <span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">40</span>, <span class="dv">100</span>, <span class="fl">0.4</span>), <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">lwd =</span> <span class="dv">6</span>,</span>
<span id="cb57-2"><a href="index.html#cb57-2" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;# of Wells with Contaminant&quot;</span>,</span>
<span id="cb57-3"><a href="index.html#cb57-3" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability&quot;</span>,</span>
<span id="cb57-4"><a href="index.html#cb57-4" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Binomial Distribution (n=100, p=0.4)&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>The graph is left skewed when N was adjusted</p>
</div>
<div id="poisson-distribution" class="section level5 hasAnchor" number="1.1.1.4.2">
<h5><span class="header-section-number">1.1.1.4.2</span> <strong>Poisson Distribution</strong><a href="index.html#poisson-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Suppose a count of the wood turtle, a protected species under the New Jersey Endangered Species Statute, is conducted in a specific geographic region. What would be a suitable data distribution model for the results obtained? Since counts are discrete rather than continuous (e.g., there can be 5 or 12 turtles, but not 7.4 turtles), continuous distribution models such as the normal, lognormal, and gamma distributions would not be appropriate. Additionally, because we are interested in the number of turtles rather than their presence or absence, the binomial distribution—though discrete—would also not be suitable, as it is designed for binary data (i.e., yes/no types of data).</p>
<p>The Poisson distribution, named after Siméon Poisson, is a discrete probability distribution used to model the number of events occurring within a fixed space or time interval, given an estimated average rate of occurrence (denoted by λ). If our focus were on the presence or absence of turtles in a given area rather than their actual count, the binomial distribution would be the appropriate choice.</p>
<p>The probability mass function (PMF) for the Poisson distribution is given by:</p>
<p><span class="math display">\[P(X=k) = {{e^{-\lambda}\lambda^k}\over{k!}}\]</span>
Where:</p>
<ul>
<li><span class="math inline">\(P(X=k)\)</span> is the probability that the Poisson-distributed random variable <span class="math inline">\(X\)</span> takes a value <span class="math inline">\(k\)</span> (where <span class="math inline">\(k\)</span> can be 0, 1, 2, etc)</li>
<li><span class="math inline">\(\lambda\)</span> is the mean or expected number of occurrences.</li>
<li><span class="math inline">\(e\)</span> is the base of the natural logarithm (apporximately 2.71828)</li>
<li><span class="math inline">\(k!\)</span>(k factorial) is computed as <span class="math inline">\(k \times (k-1) \times(k-2) \times...\times 1\)</span></li>
</ul>
<p>For the Poisson distribution, the mean (expected value) is <span class="math inline">\(\lambda\)</span>, and the variance is also equal to <span class="math inline">\(\lambda\)</span>, meaning the distribution’s spread is directly tied to the mean.</p>
<p>Consider a scenario where the expected number of turtles per hectare is 5. The probability of finding exactly 10 turtles per hectare can be computed in R as:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="index.html#cb58-1" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">10</span>, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.01813279</code></pre>
<p>This yields approximately 0.0181 (or 1.81%). Conversely, the probability of finding 10 or fewer turtles can be obtained using:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="index.html#cb60-1" tabindex="-1"></a><span class="fu">ppois</span>(<span class="dv">10</span>, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.9863047</code></pre>
<p>which results in 0.9863 (or 98.63%). Thus, the probability of finding more than 10 turtles is:
<span class="math display">\[1 - 0.9863 = 0.0137\]</span></p>
<p>Lets visualize this;</p>
<p>The following R script generates Poisson probability mass function plots for different values of <span class="math inline">\(\lambda\)</span> (2, 5, and 20):</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="index.html#cb62-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb62-2"><a href="index.html#cb62-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">lend =</span> <span class="dv">2</span>)</span>
<span id="cb62-3"><a href="index.html#cb62-3" tabindex="-1"></a></span>
<span id="cb62-4"><a href="index.html#cb62-4" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">2</span>), <span class="at">type =</span> <span class="st">&#39;h&#39;</span>, <span class="at">lwd =</span> <span class="dv">6</span>, <span class="at">xlab =</span> <span class="st">&#39;Count or # of Occurrences (k)&#39;</span>,</span>
<span id="cb62-5"><a href="index.html#cb62-5" tabindex="-1"></a><span class="at">ylab =</span> <span class="st">&#39;Probability (P(X = k))&#39;</span>)</span>
<span id="cb62-6"><a href="index.html#cb62-6" tabindex="-1"></a><span class="fu">mtext</span>(<span class="at">side =</span> <span class="dv">3</span>, <span class="at">line =</span> <span class="fl">0.5</span>, <span class="fu">expression</span>(lambda <span class="sc">==</span> <span class="dv">2</span>))</span>
<span id="cb62-7"><a href="index.html#cb62-7" tabindex="-1"></a></span>
<span id="cb62-8"><a href="index.html#cb62-8" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">15</span>, <span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">15</span>, <span class="dv">5</span>), <span class="at">type =</span> <span class="st">&#39;h&#39;</span>, <span class="at">lwd =</span> <span class="dv">4</span>, <span class="at">xlab =</span> <span class="st">&#39;Count or # of Occurrences (k)&#39;</span>,</span>
<span id="cb62-9"><a href="index.html#cb62-9" tabindex="-1"></a><span class="at">ylab =</span> <span class="st">&#39;Probability (P(X = k))&#39;</span>)</span>
<span id="cb62-10"><a href="index.html#cb62-10" tabindex="-1"></a><span class="fu">mtext</span>(<span class="at">side =</span> <span class="dv">3</span>, <span class="at">line =</span> <span class="fl">0.5</span>, <span class="fu">expression</span>(lambda <span class="sc">==</span> <span class="dv">5</span>))</span>
<span id="cb62-11"><a href="index.html#cb62-11" tabindex="-1"></a></span>
<span id="cb62-12"><a href="index.html#cb62-12" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">40</span>, <span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">40</span>, <span class="dv">20</span>), <span class="at">type =</span> <span class="st">&#39;h&#39;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">&#39;Count or # of Occurrences (k)&#39;</span>,</span>
<span id="cb62-13"><a href="index.html#cb62-13" tabindex="-1"></a><span class="at">ylab =</span> <span class="st">&#39;Probability (P(X = k))&#39;</span>)</span>
<span id="cb62-14"><a href="index.html#cb62-14" tabindex="-1"></a><span class="fu">mtext</span>(<span class="at">side =</span> <span class="dv">3</span>, <span class="at">line =</span> <span class="fl">0.5</span>, <span class="fu">expression</span>(lambda <span class="sc">==</span> <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>As <span class="math inline">\(\lambda\)</span> increases, the Poisson distribution becomes more symmetric and begins to resemble the normal distribution. The Poisson distribution can also serve as an approximation for the binomial distribution when the number of trials (<span class="math inline">\(n\)</span>) is large and the probability of success (<span class="math inline">\(p\)</span>) is small, such that <span class="math inline">\(\lambda = np\)</span>. Typically, the Poisson approximation to the binomial is valid when <span class="math inline">\(n \geq 20\)</span> and <span class="math inline">\(p\leq 0.05\)</span>, or when <span class="math inline">\(n \geq 100\)</span> and <span class="math inline">\(np \geq 10\)</span>.</p>
<p>A common application of the Poisson distribution in environmental science is Poisson regression, where the response variable consists of event counts assumed to follow a Poisson distribution, while predictor variables influence these counts. For instance, turtle population density per hectare might be modeled as a function of habitat type (e.g., forested wetlands, upland forests, agricultural fields) and proximity to roadways or urban areas.</p>
<p>A key issue in Poisson regression is overdispersion—when the observed data variance significantly exceeds the mean. Overdispersion can lead to poor model fit and necessitate alternative models, such as the negative binomial distribution.</p>
<p>In summary, the Poisson distribution provides a useful model for count data, particularly when events occur independently over a fixed interval of time or space.</p>
</div>
</div>
</div>
</div>
<div id="hands-on-exercises" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> <span style="color: green;"><strong>Hands-on Exercises</strong></span><a href="index.html#hands-on-exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="hypothesis-testing.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/balsaedi/RCourse/edit/main/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/balsaedi/RCourse/blob/main/index.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
