<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 LINEAR REGRESSION ANALYSIS | Ecological Analysis</title>
  <meta name="description" content="Chapter 5 LINEAR REGRESSION ANALYSIS | Ecological Analysis" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 LINEAR REGRESSION ANALYSIS | Ecological Analysis" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 LINEAR REGRESSION ANALYSIS | Ecological Analysis" />
  
  
  

<meta name="author" content="Basim Alsaedi" />


<meta name="date" content="2024-11-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlation-covariance-geostatistics.html"/>
<link rel="next" href="conventional-and-probabilistic-risk-assessment.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SHORT TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUCTION</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-distributions"><i class="fa fa-check"></i><b>1.1</b> Data Distributions</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#types-of-distribution"><i class="fa fa-check"></i><b>1.1.1</b> Types of Distribution</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#hands-on-exercises"><i class="fa fa-check"></i><b>1.2</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>2</b> HYPOTHESIS TESTING</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-tests"><i class="fa fa-check"></i><b>2.2</b> Parametric tests</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-single-sample-test"><i class="fa fa-check"></i><b>2.2.1</b> Parametric single-sample test</a></li>
<li class="chapter" data-level="2.2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-two-sample-test"><i class="fa fa-check"></i><b>2.2.2</b> Parametric two-sample test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-test"><i class="fa fa-check"></i><b>2.3</b> Nonparametric test</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-sample-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.1</b> Nonparametric One-Sample Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="2.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-two-sample-paired-sign-test-and-paired-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.2</b> Nonparametric two-sample paired sign test and paired Wilcoxon Signed Rank Test</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-one-way-anova"><i class="fa fa-check"></i><b>2.4.1</b> Parametric One-Way ANOVA</a></li>
<li class="chapter" data-level="2.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-way-anova-kruskal-wallis-test"><i class="fa fa-check"></i><b>2.4.2</b> Nonparametric One-Way ANOVA (Kruskal-Wallis Test)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hands-on-exercise"><i class="fa fa-check"></i><b>2.5</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html"><i class="fa fa-check"></i><b>3</b> TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS</a>
<ul>
<li class="chapter" data-level="3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#test-for-autocorrelation-using-the-sample-autocorrelation-function"><i class="fa fa-check"></i><b>3.1</b> Test for Autocorrelation Using the Sample Autocorrelation Function</a></li>
<li class="chapter" data-level="3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#an-example-on-site-wide-temporal-effects"><i class="fa fa-check"></i><b>3.2</b> An Example on Site-Wide Temporal Effects</a></li>
<li class="chapter" data-level="3.3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#tests-for-trend"><i class="fa fa-check"></i><b>3.3</b> TESTS FOR TREND</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#parametric-test-for-trends---simple-linear-regression"><i class="fa fa-check"></i><b>3.3.1</b> Parametric Test for Trends - Simple Linear Regression</a></li>
<li class="chapter" data-level="3.3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#nonparametric-test-for-trends"><i class="fa fa-check"></i><b>3.3.2</b> Nonparametric Test for Trends</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#hands-on-exercises-1"><i class="fa fa-check"></i><b>3.4</b> <span style="color: green;"><strong>Hands-On Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html"><i class="fa fa-check"></i><b>4</b> CORRELATION, COVARIANCE, GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> INTRODUCTION</a></li>
<li class="chapter" data-level="4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#correlation-and-covariance"><i class="fa fa-check"></i><b>4.2</b> CORRELATION AND COVARIANCE</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>4.2.1</b> Pearson’s Correlation Coefficient</a></li>
<li class="chapter" data-level="4.2.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#spearmans-and-kendalls-correlaton-coefficients"><i class="fa fa-check"></i><b>4.2.2</b> Spearman’s and Kendall’s Correlaton Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#covariance"><i class="fa fa-check"></i><b>4.3</b> COVARIANCE</a></li>
<li class="chapter" data-level="4.4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#geostatistics"><i class="fa fa-check"></i><b>4.4</b> GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#variogram-modelling"><i class="fa fa-check"></i><b>4.4.1</b> Variogram Modelling</a></li>
<li class="chapter" data-level="4.4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#kriging"><i class="fa fa-check"></i><b>4.4.2</b> Kriging</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html"><i class="fa fa-check"></i><b>5</b> LINEAR REGRESSION ANALYSIS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#simple-linear-regression-analysis"><i class="fa fa-check"></i><b>5.1</b> Simple Linear Regression Analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#empirical-model-building-regression-analysis"><i class="fa fa-check"></i><b>5.1.1</b> Empirical model-building-regression analysis</a></li>
<li class="chapter" data-level="5.1.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#interpreting-the-regression-results"><i class="fa fa-check"></i><b>5.1.2</b> Interpreting the regression results</a></li>
<li class="chapter" data-level="5.1.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#r-squared-and-adjusted-r-squared"><i class="fa fa-check"></i><b>5.1.3</b> R-squared and Adjusted R-Squared</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-versus-generalized-linear-model"><i class="fa fa-check"></i><b>5.2</b> Data transformation versus generalized linear model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-approach-log-transformation"><i class="fa fa-check"></i><b>5.2.1</b> Data Transformation Approach (Log Transformation)</a></li>
<li class="chapter" data-level="5.2.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#generalized-linear-modelglm"><i class="fa fa-check"></i><b>5.2.2</b> Generalized Linear Model(GLM)</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#multiple-linear-regression-mlr-model"><i class="fa fa-check"></i><b>5.3</b> Multiple Linear Regression (MLR) model</a></li>
<li class="chapter" data-level="5.4" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#hands-on-exercise-1"><i class="fa fa-check"></i><b>5.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html"><i class="fa fa-check"></i><b>6</b> CONVENTIONAL AND PROBABILISTIC RISK ASSESSMENT</a>
<ul>
<li class="chapter" data-level="6.1" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#introduction-3"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#conventional-or-point-risk-estimation"><i class="fa fa-check"></i><b>6.2</b> Conventional or Point Risk Estimation</a></li>
<li class="chapter" data-level="6.3" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#probabilistic-risk-assessment-using-monte-carlo-simulation"><i class="fa fa-check"></i><b>6.3</b> Probabilistic Risk Assessment Using Monte Carlo Simulation</a></li>
<li class="chapter" data-level="6.4" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#practical-exercise"><i class="fa fa-check"></i><b>6.4</b> <span style="color: green;"><strong>Practical Exercise</strong></span></a></li>
<li class="chapter" data-level="6.5" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#hands-on-exercise-2"><i class="fa fa-check"></i><b>6.5</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>7</b> Datasets</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ecological Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression-analysis" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> LINEAR REGRESSION ANALYSIS<a href="linear-regression-analysis.html#linear-regression-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Regression</strong> is the finding of a relation between the input(predictor/independent) variable/s and the continuous output(target/dependent) variable.</p>
<p>Now <strong>Linear Regression</strong> is finding the linear relationship between dependent variable and one or more independent features by fitting a linear equation to the observed data. If there is one independent variable therefore the regression in known as <strong>simple linear regression</strong> while if multiple variables are involved it is known as <strong>multiple linear regression.</strong></p>
<div id="simple-linear-regression-analysis" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Simple Linear Regression Analysis<a href="linear-regression-analysis.html#simple-linear-regression-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Simple linear regression seeks to explore and model the relationship between two quantitative variables. Here’s what it helps you do:</p>
<ul>
<li><em>Understand the strength of the relationship</em>:</li>
</ul>
<p>For example, it can reveal how strongly rainfall affects soil erosion. If the relationship is strong, changes in rainfall levels are likely to lead to significant changes in soil erosion.</p>
<ul>
<li><em>Make predictions</em>:</li>
</ul>
<p>It allows you to estimate the dependent variable’s value for a given value of the independent variable. For instance, if you know how much it rained, you can predict how much soil erosion occurred.</p>
<p>The beauty of simple linear regression lies in its simplicity—you’re working with just two variables. One acts as the input, and the other as the output. It’s like finding a straight-line path that best connects the data points and helps explain their relationship.</p>
<p>For instance, imagine plotting rainfall (in mm) on the x-axis and soil erosion (in kg) on the y-axis. A regression line (a straight line) is fitted to the data, showing the trend. If the line slopes upwards, it means more rain leads to more soil erosion—a positive relationship. If it slopes downward, it’s a negative relationship.</p>
<p>So, simple linear regression isn’t just math—it’s a way to uncover insights and make informed predictions from real-world data!</p>
<div id="empirical-model-building-regression-analysis" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Empirical model-building-regression analysis<a href="linear-regression-analysis.html#empirical-model-building-regression-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Simple linear regression is a <strong>parametric test</strong>, which means it relies on certain assumptions about your data to ensure accurate and reliable results. Let’s break down these assumptions:</p>
<p><strong>Key Assumptions of Simple Linear Regression</strong></p>
<ol style="list-style-type: decimal">
<li><em>Homogeneity of variance (Homoscedasticity)</em>:</li>
</ol>
<p>The prediction errors (residuals) should remain roughly the same across all values of the independent variable. In simpler terms, the “spread” of data points around the regression line should stay consistent, not get wider or narrower.</p>
<ol start="2" style="list-style-type: decimal">
<li><em>Independence of observations</em>:</li>
</ol>
<p>Each data point in your dataset should be collected independently. For example, there shouldn’t be hidden relationships or patterns among your observations, like duplicate measurements or a biased sampling method.</p>
<ol start="3" style="list-style-type: decimal">
<li><em>Normality</em>:</li>
</ol>
<p>The data (especially the residuals) should follow a normal distribution. This is important for making valid inferences from your model.</p>
<ol start="4" style="list-style-type: decimal">
<li><em>Linearity</em>:</li>
</ol>
<p>The relationship between the independent and dependent variables should be linear. That means the best-fitting line through your data points should be straight, not curved or clustered into groups.</p>
<p><strong>What if these assumptions aren’t met?</strong></p>
<p>If your data violate assumptions like homoscedasticity or normality, don’t worry—you still have options! For instance, you can use a nonparametric test like the <em>Spearman rank test</em>, which doesn’t rely on strict parametric assumptions.</p>
<p>By ensuring your data meets these conditions, you can confidently use simple linear regression to model and predict relationships between variables!</p>
<p>The formula for simple linear regression looks like this: <span class="math display">\[y = \alpha + \beta X + \epsilon\]</span></p>
<p>where;</p>
<ul>
<li><span class="math inline">\(y\)</span>: the predicted value of the dependent variable.</li>
<li><span class="math inline">\(X\)</span>: the independent variable believed to be influencing the value of <span class="math inline">\(y\)</span></li>
<li><span class="math inline">\(\alpha\)</span>: the intercept, or the starting point. It tells you the predicted value of <span class="math inline">\(y\)</span> when <span class="math inline">\(X\)</span> (the independent variable) is 0.</li>
<li><span class="math inline">\(\beta\)</span>: the regression coeefficient, which measures the expected change in <span class="math inline">\(y\)</span> for each one unit increase in <span class="math inline">\(X\)</span>. This is the slope/gradient of the line.</li>
<li><span class="math inline">\(\epsilon\)</span>: the error term, representing how much actual data points deviate from the predicted line.</li>
</ul>
<p><em>This is how linear regression works:</em></p>
<p>Linear regression fits a <strong>line of best fit</strong> through your data points. It finds the value of <span class="math inline">\(\beta\)</span> (<strong>the slope</strong>) that minimizes the total error (the difference between the observed and predicted values of <span class="math inline">\(y\)</span>.</p>
<p>In simple terms, the regression line represents the most accurate straight-line relationship between your independent variable (<span class="math inline">\(X\)</span>) and your dependent variable (<span class="math inline">\(y\)</span>).</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets make this practical, you will be required to download the plant height data from <a href="https://environmentalcomputing.net/datasets/Plant_height.csv">here</a>.</p>
<p><strong>Remember:</strong> The goal in linear regression is obtain the best estimates for the model coefficients(<span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>).</p>
<p>We will break down the process in steps;</p>
<ul>
<li>Load the data set</li>
</ul>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="linear-regression-analysis.html#cb232-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/Plant_height.csv&quot;</span>)</span></code></pre></div>
<ul>
<li><p>The goal of this analysis is to find the linear association between the plant height and the temperature, particularly if plant height is dependent on the temperature.</p></li>
<li><p><em>Define the independent and dependent variables:</em> temperature(<code>temp</code>) is the independent variable while plant height(<code>loght</code>) is the dependent variable</p></li>
</ul>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="linear-regression-analysis.html#cb233-1" tabindex="-1"></a><span class="fu">lm</span>(loght <span class="sc">~</span> temp, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = loght ~ temp, data = df)
## 
## Coefficients:
## (Intercept)         temp  
##    -0.22566      0.04241</code></pre>
</div>
<div id="interpreting-the-regression-results" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Interpreting the regression results<a href="linear-regression-analysis.html#interpreting-the-regression-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To get a detailed breakdown of the regression results, such as the coefficient values, <span class="math inline">\(R^2\)</span>, test statistics, p-values, and confidence intervals, you need to save the output of the <code>lm</code> function to an object. Then, use the <code>summary()</code> function on that object to extract and review the analysis details.</p>
<p>Note: <code>loght</code> is log(plant height).</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="linear-regression-analysis.html#cb235-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(loght <span class="sc">~</span> temp, <span class="at">data =</span> df)</span>
<span id="cb235-2"><a href="linear-regression-analysis.html#cb235-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = loght ~ temp, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.97903 -0.42804 -0.00918  0.43200  1.79893 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.225665   0.103776  -2.175    0.031 *  
## temp         0.042414   0.005593   7.583 1.87e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6848 on 176 degrees of freedom
## Multiple R-squared:  0.2463, Adjusted R-squared:  0.242 
## F-statistic:  57.5 on 1 and 176 DF,  p-value: 1.868e-12</code></pre>
<p>The regression output provides the slope and intercept of the regression line. Based on this analysis, the regression equation for predicting the (log-transformed) plant height as a function of temperature is:</p>
<p><span class="math display">\[loght = −0.22566+0.04241*temp + \epsilon\]</span></p>
<p>and this is the breakdown of the analysis;</p>
<ul>
<li><em>Coefficients</em></li>
</ul>
<p>The intercept (-0.22566) represents the predicted value of log(plant height) when the temperature is zero.</p>
<p>The slope (0.04241) indicates that for every one-unit increase in temperature, the log(plant height) increases by approximately 0.04241.</p>
<ul>
<li><em>Significance of Coefficients</em></li>
</ul>
<p>The t-statistics and p-values test whether the coefficients are significantly different from zero.</p>
<p>Here, the p-value for temperature (&lt; 0.005) suggests a statistically significant relationship between temperature and plant height.</p>
<p>The intercept’s p-value (0.031) is less important since we typically focus on the slope’s significance.</p>
<ul>
<li><em>Overall Model Significance</em></li>
</ul>
<p>The F-statistic (57.5) and its associated p-value (&lt;0.001) confirm that the overall model is statistically significant.</p>
<p>With a single predictor, the p-value for the F-statistic is identical to the p-value for the slope coefficient.</p>
</div>
<div id="r-squared-and-adjusted-r-squared" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> R-squared and Adjusted R-Squared<a href="linear-regression-analysis.html#r-squared-and-adjusted-r-squared" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>R-squared</strong>, or the coefficient of determination, measures the proportion of the variance in the dependent variable (<span class="math inline">\(y\)</span>) that is explained by the independent variable(s) (<span class="math inline">\(x\)</span>) in a regression model. It is a goodness-of-fit statistic.</p>
<p>On the other hand, <strong>Adjusted R-squared</strong> modifies R-squared to account for the number of predictors in the model, providing a more accurate measure of model performance, especially for multiple regression.</p>
<p>Like our model above shows that:</p>
<ul>
<li>The <span class="math inline">\(R^2\)</span> value (0.2463) shows that approximately 24.6% of the variation in plant height is explained by temperature.</li>
<li>The adjusted <span class="math inline">\(R^2\)</span> (0.242) slightly adjusts for the model’s complexity and is more relevant when comparing models</li>
</ul>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>You will be provided the <code>creek_basin_data.csv</code> file by your instructor. The data is about the effect of the amount of rainfall on the creek run off. The objective is to investigate for a linear relationship between the amount of rainfall and the creek run off. You are required to;</p>
<ul>
<li>Build a simple linear regression model</li>
<li>Evaluate R-squared and Adjusted r-squared to find if the the linear model is effective.</li>
<li>Finally, visualize the model</li>
</ul>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ul>
<li>Build a simple linear regression model</li>
</ul>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="linear-regression-analysis.html#cb237-1" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb237-2"><a href="linear-regression-analysis.html#cb237-2" tabindex="-1"></a>creek_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/creek_basin_data.csv&quot;</span>)</span>
<span id="cb237-3"><a href="linear-regression-analysis.html#cb237-3" tabindex="-1"></a></span>
<span id="cb237-4"><a href="linear-regression-analysis.html#cb237-4" tabindex="-1"></a><span class="co"># Fit linear regression model</span></span>
<span id="cb237-5"><a href="linear-regression-analysis.html#cb237-5" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Runoff_cm <span class="sc">~</span> Rainfall_cm, <span class="at">data =</span> creek_data)</span>
<span id="cb237-6"><a href="linear-regression-analysis.html#cb237-6" tabindex="-1"></a></span>
<span id="cb237-7"><a href="linear-regression-analysis.html#cb237-7" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb237-8"><a href="linear-regression-analysis.html#cb237-8" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Runoff_cm ~ Rainfall_cm, data = creek_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.4759 -1.2265 -0.0395  1.1927  4.4345 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.01801    0.51541   0.035    0.972    
## Rainfall_cm  0.69281    0.02735  25.335   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.939 on 98 degrees of freedom
## Multiple R-squared:  0.8675, Adjusted R-squared:  0.8662 
## F-statistic: 641.9 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The regression line equation inform of <span class="math inline">\(y = \alpha + \beta x + \epsilon\)</span> goes by;
<span class="math display">\[\text Runoff = 0.01801 + 0.69281 \times Rainfall + \epsilon\]</span>
This means that a 0cm rain would yield to approximately 0.01801cm runoff
The p-value for rainfall is <span class="math inline">\(2 \times 10^{-16}\)</span>, meaning that the rainfall is a significant predictor for ruin off</p>
<ul>
<li>Evaluate R-squared and Adjusted r-squared to find if the the linear model is effective.</li>
</ul>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="linear-regression-analysis.html#cb239-1" tabindex="-1"></a><span class="co"># Extract R-squared and Adjusted R-squared to present it clearly</span></span>
<span id="cb239-2"><a href="linear-regression-analysis.html#cb239-2" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span>
<span id="cb239-3"><a href="linear-regression-analysis.html#cb239-3" tabindex="-1"></a>adjusted_r_squared <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>adj.r.squared</span>
<span id="cb239-4"><a href="linear-regression-analysis.html#cb239-4" tabindex="-1"></a></span>
<span id="cb239-5"><a href="linear-regression-analysis.html#cb239-5" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;R-Squared:&quot;</span>, r_squared, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## R-Squared: 0.8675463</code></pre>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="linear-regression-analysis.html#cb241-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Adjusted R-Squared:&quot;</span>, adjusted_r_squared, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Adjusted R-Squared: 0.8661947</code></pre>
<p>The Multiple r-squared = 08675, that is approximately 87% of the variability in runoff is explained by rainfall.
Since it is a simple linear regression problem and we only have one predictor, R² and Adjusted R² are very close.</p>
<ul>
<li>Finally, visualize the model</li>
</ul>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="linear-regression-analysis.html#cb243-1" tabindex="-1"></a><span class="co"># Load the required library</span></span>
<span id="cb243-2"><a href="linear-regression-analysis.html#cb243-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb243-3"><a href="linear-regression-analysis.html#cb243-3" tabindex="-1"></a></span>
<span id="cb243-4"><a href="linear-regression-analysis.html#cb243-4" tabindex="-1"></a><span class="co"># Scatter plot with regression line</span></span>
<span id="cb243-5"><a href="linear-regression-analysis.html#cb243-5" tabindex="-1"></a><span class="fu">ggplot</span>(creek_data, <span class="fu">aes</span>(<span class="at">x =</span> Rainfall_cm, <span class="at">y =</span> Runoff_cm)) <span class="sc">+</span></span>
<span id="cb243-6"><a href="linear-regression-analysis.html#cb243-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb243-7"><a href="linear-regression-analysis.html#cb243-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb243-8"><a href="linear-regression-analysis.html#cb243-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Rainfall vs Runoff&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Rainfall (cm)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Runoff (cm)&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
<div id="data-transformation-versus-generalized-linear-model" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Data transformation versus generalized linear model<a href="linear-regression-analysis.html#data-transformation-versus-generalized-linear-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="data-transformation-approach-log-transformation" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Data Transformation Approach (Log Transformation)<a href="linear-regression-analysis.html#data-transformation-approach-log-transformation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this sub-course, we will consider a study where we examine how pollution levels affect fish abundance in a river system. We assume:</p>
<ul>
<li>Low pollution results in higher fish abundance.</li>
<li>High pollution results in lower fish abundance.</li>
<li>Fish abundance is a count variable (discrete, non-negative).</li>
</ul>
<p>Ecological data is often skewed (many low values, few high values). Log transformation stabilizes variance and makes the distribution closer to normal:
<span class="math display">\[Y&#39;= log(Y + 1)\]</span>
where;</p>
<ul>
<li><span class="math inline">\(Y&#39;\)</span> is the transformed fish abundance</li>
<li><span class="math inline">\(Y\)</span> is the original fish abundance (adding 1 prevents log(0)).</li>
</ul>
<p>A linear regression model can be used after transformation:
<span class="math display">\[log(Y+1) = \beta_0 + \beta_1X + \epsilon\]</span>
as described. However transformation posses with several limitations such as;</p>
<ul>
<li>Interpretation is difficult because the response variable is no longer on the original scale.</li>
<li>Transformation may not fully address skewness in highly non-normal data.</li>
<li>Not ideal for count data, which follow discrete probability distributions.</li>
</ul>
</div>
<div id="generalized-linear-modelglm" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Generalized Linear Model(GLM)<a href="linear-regression-analysis.html#generalized-linear-modelglm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Instead of transforming the data, we can use a Poisson regression model, which assumes that fish abundance follows a Poisson distribution:
<span class="math display">\[Y \text ~ Poisson(\lambda)\]</span>
where <span class="math inline">\(Y\)</span> is the data value count(count of observed fish) and <span class="math inline">\(\lambda\)</span> is the expected abundance(fish abundance in our case)</p>
<p>GLMs use a log-link function to model the expected count directly:
<span class="math display">\[log(\lambda) = \beta_0 + \beta_1X\]</span>
Solving for <span class="math inline">\(\lambda\)</span>;
<span class="math display">\[\lambda = e^{\beta_o + \beta_1X}\]</span>
Keep in mind that;</p>
<ul>
<li><span class="math inline">\(e^{\beta_o}\)</span> is the expected abundance in low pollution areas</li>
<li><span class="math inline">\(e^{\beta_1X}\)</span> is the multiplicative effect of pollution.</li>
</ul>
<p>GLM(Poisson Regression model) posses various advantages where it;</p>
<ul>
<li>Maintains original scale of the response variable (counts).</li>
<li>is more appropriate for count data, which are often non-normal.</li>
<li>Exponential interpretation: <span class="math inline">\(e^{\beta_1}\)</span> gives the factor by which abundance changes due to pollution.</li>
</ul>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets simulate the fish population in respect to pollution levels using R.</p>
<p>Step 1: Generate the data</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="linear-regression-analysis.html#cb245-1" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb245-2"><a href="linear-regression-analysis.html#cb245-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb245-3"><a href="linear-regression-analysis.html#cb245-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb245-4"><a href="linear-regression-analysis.html#cb245-4" tabindex="-1"></a></span>
<span id="cb245-5"><a href="linear-regression-analysis.html#cb245-5" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb245-6"><a href="linear-regression-analysis.html#cb245-6" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb245-7"><a href="linear-regression-analysis.html#cb245-7" tabindex="-1"></a></span>
<span id="cb245-8"><a href="linear-regression-analysis.html#cb245-8" tabindex="-1"></a><span class="co"># Simulate pollution levels (Low = 0, High = 1)</span></span>
<span id="cb245-9"><a href="linear-regression-analysis.html#cb245-9" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>  <span class="co"># Number of observations</span></span>
<span id="cb245-10"><a href="linear-regression-analysis.html#cb245-10" tabindex="-1"></a>pollution <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb245-11"><a href="linear-regression-analysis.html#cb245-11" tabindex="-1"></a></span>
<span id="cb245-12"><a href="linear-regression-analysis.html#cb245-12" tabindex="-1"></a><span class="co"># Generate fish abundance (count data)</span></span>
<span id="cb245-13"><a href="linear-regression-analysis.html#cb245-13" tabindex="-1"></a>fish_abundance <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n, <span class="at">lambda =</span> <span class="fu">ifelse</span>(pollution <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">15</span>, <span class="dv">5</span>)) <span class="co"># Lower in polluted areas</span></span>
<span id="cb245-14"><a href="linear-regression-analysis.html#cb245-14" tabindex="-1"></a></span>
<span id="cb245-15"><a href="linear-regression-analysis.html#cb245-15" tabindex="-1"></a><span class="co"># Combine into a data frame</span></span>
<span id="cb245-16"><a href="linear-regression-analysis.html#cb245-16" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Pollution =</span> <span class="fu">factor</span>(pollution, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Low&quot;</span>, <span class="st">&quot;High&quot;</span>)),</span>
<span id="cb245-17"><a href="linear-regression-analysis.html#cb245-17" tabindex="-1"></a>                   <span class="at">Fish_Abundance =</span> fish_abundance)</span>
<span id="cb245-18"><a href="linear-regression-analysis.html#cb245-18" tabindex="-1"></a></span>
<span id="cb245-19"><a href="linear-regression-analysis.html#cb245-19" tabindex="-1"></a><span class="co"># Check its distribution </span></span>
<span id="cb245-20"><a href="linear-regression-analysis.html#cb245-20" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>Fish_Abundance)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="linear-regression-analysis.html#cb246-1" tabindex="-1"></a><span class="co"># Summary of simulated data</span></span>
<span id="cb246-2"><a href="linear-regression-analysis.html#cb246-2" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code></pre></div>
<pre><code>##  Pollution Fish_Abundance 
##  Low :57   Min.   : 2.00  
##  High:43   1st Qu.: 5.00  
##            Median :11.50  
##            Mean   :10.26  
##            3rd Qu.:14.25  
##            Max.   :22.00</code></pre>
<p>Apply log transformation since the data is right-skewed</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="linear-regression-analysis.html#cb248-1" tabindex="-1"></a><span class="co"># Log transform fish abundance (add 1 to avoid log(0))</span></span>
<span id="cb248-2"><a href="linear-regression-analysis.html#cb248-2" tabindex="-1"></a>data<span class="sc">$</span>Log_Abundance <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>Fish_Abundance <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb248-3"><a href="linear-regression-analysis.html#cb248-3" tabindex="-1"></a></span>
<span id="cb248-4"><a href="linear-regression-analysis.html#cb248-4" tabindex="-1"></a><span class="co"># Boxplot to visualize transformed vs. untransformed data</span></span>
<span id="cb248-5"><a href="linear-regression-analysis.html#cb248-5" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Pollution, <span class="at">y =</span> Fish_Abundance)) <span class="sc">+</span></span>
<span id="cb248-6"><a href="linear-regression-analysis.html#cb248-6" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb248-7"><a href="linear-regression-analysis.html#cb248-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Raw Fish Abundance vs. Pollution Level&quot;</span>) <span class="sc">+</span></span>
<span id="cb248-8"><a href="linear-regression-analysis.html#cb248-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-99-1.png" width="672" /></p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="linear-regression-analysis.html#cb249-1" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Pollution, <span class="at">y =</span> Log_Abundance)) <span class="sc">+</span></span>
<span id="cb249-2"><a href="linear-regression-analysis.html#cb249-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb249-3"><a href="linear-regression-analysis.html#cb249-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Log-Transformed Fish Abundance vs. Pollution Level&quot;</span>) <span class="sc">+</span></span>
<span id="cb249-4"><a href="linear-regression-analysis.html#cb249-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-99-2.png" width="672" />
The log transformation helps stabilize variance and make the distribution more normal.
However, using transformed data in regression may not always be statistically appropriate for count data.</p>
<p>Instead of transforming, we use a Poisson (GLM), which is designed for count data.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="linear-regression-analysis.html#cb250-1" tabindex="-1"></a><span class="co"># Fit Poisson GLM</span></span>
<span id="cb250-2"><a href="linear-regression-analysis.html#cb250-2" tabindex="-1"></a>glm_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Fish_Abundance <span class="sc">~</span> Pollution, <span class="at">family =</span> poisson, <span class="at">data =</span> data)</span>
<span id="cb250-3"><a href="linear-regression-analysis.html#cb250-3" tabindex="-1"></a></span>
<span id="cb250-4"><a href="linear-regression-analysis.html#cb250-4" tabindex="-1"></a><span class="co"># Model summary</span></span>
<span id="cb250-5"><a href="linear-regression-analysis.html#cb250-5" tabindex="-1"></a><span class="fu">summary</span>(glm_model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Fish_Abundance ~ Pollution, family = poisson, data = data)
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    2.66014    0.03503   75.94   &lt;2e-16 ***
## PollutionHigh -1.06948    0.07724  -13.85   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 289.134  on 99  degrees of freedom
## Residual deviance:  59.428  on 98  degrees of freedom
## AIC: 465.3
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The Poisson model directly models count data without transformation.
The coefficient for “High Pollution” = -1.06948 shows how pollution reduces fish abundance in a statistically valid way. A negative correlation where increase in pollution results in decrease in fish abundance and vice versa.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Using the <code>creek_basin_data.csv</code>, Log transform the data and fit with a generalized linear model. If the the transformation improves the R-squared value(from the simple linear regression model), then its is more appropriate(Shows the residuals may not be normally distributed)</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Lets log transform the data</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="linear-regression-analysis.html#cb252-1" tabindex="-1"></a><span class="co"># Apply log transformation to both variables</span></span>
<span id="cb252-2"><a href="linear-regression-analysis.html#cb252-2" tabindex="-1"></a>creek_data<span class="sc">$</span>log_Rainfall <span class="ot">&lt;-</span> <span class="fu">log</span>(creek_data<span class="sc">$</span>Rainfall_cm)</span>
<span id="cb252-3"><a href="linear-regression-analysis.html#cb252-3" tabindex="-1"></a>creek_data<span class="sc">$</span>log_Runoff <span class="ot">&lt;-</span> <span class="fu">log</span>(creek_data<span class="sc">$</span>Runoff_cm)</span>
<span id="cb252-4"><a href="linear-regression-analysis.html#cb252-4" tabindex="-1"></a></span>
<span id="cb252-5"><a href="linear-regression-analysis.html#cb252-5" tabindex="-1"></a><span class="co"># Fit linear model with log-transformed data</span></span>
<span id="cb252-6"><a href="linear-regression-analysis.html#cb252-6" tabindex="-1"></a>log_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Runoff <span class="sc">~</span> log_Rainfall, <span class="at">data =</span> creek_data)</span>
<span id="cb252-7"><a href="linear-regression-analysis.html#cb252-7" tabindex="-1"></a><span class="fu">summary</span>(log_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log_Runoff ~ log_Rainfall, data = creek_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.42140 -0.09909  0.01952  0.10424  0.61348 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -0.52368    0.14773  -3.545 0.000604 ***
## log_Rainfall  1.04825    0.05274  19.877  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2447 on 98 degrees of freedom
## Multiple R-squared:  0.8013, Adjusted R-squared:  0.7992 
## F-statistic: 395.1 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model above captures the nonlinear relationship of the rainfall amount the run off, however it is a lower accuracy than the simple linear model. Accuracy reduced by 0.05 which is 5%.</p>
<p>Now we fit a generalized Linear model</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="linear-regression-analysis.html#cb254-1" tabindex="-1"></a><span class="co"># Fit GLM (Gaussian with identity link function)</span></span>
<span id="cb254-2"><a href="linear-regression-analysis.html#cb254-2" tabindex="-1"></a>glm_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Runoff_cm <span class="sc">~</span> Rainfall_cm, <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>), <span class="at">data =</span> creek_data)</span>
<span id="cb254-3"><a href="linear-regression-analysis.html#cb254-3" tabindex="-1"></a><span class="fu">summary</span>(glm_model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Runoff_cm ~ Rainfall_cm, family = gaussian(link = &quot;identity&quot;), 
##     data = creek_data)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.01801    0.51541   0.035    0.972    
## Rainfall_cm  0.69281    0.02735  25.335   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 3.758101)
## 
##     Null deviance: 2780.55  on 99  degrees of freedom
## Residual deviance:  368.29  on 98  degrees of freedom
## AIC: 420.16
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>The GLM results are almost identical to the original linear model and the AIC = 420.16 confirms a relatively good model fit, though the log-transformed model had a stronger R².</p>
<p>If the residuals in the original linear model are not normal, the GLM can handle that better.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
<div id="multiple-linear-regression-mlr-model" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Multiple Linear Regression (MLR) model<a href="linear-regression-analysis.html#multiple-linear-regression-mlr-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Unlike simple linear regression, multiple linear regression describes the linear relationship between two or more independent variables with one target(dependent) variable. The objective of multiple linear regression is to;-</p>
<ol style="list-style-type: lower-roman">
<li>Find the strength of the relationship between two or more independent variables with the target variables.</li>
<li>Find the value of the target variable at a certain value of the independent variable.</li>
</ol>
<p>When working on a multiple linear regression it is assumed that; the <strong>variance is homogeneous</strong> such that the prediction error does not change significantly across the predictor(independent) variables. It is also assumed, <strong>observations were independent</strong> and there was no hidden relationships among the variables when collecting the data. Additionally, the collected data follows <strong>a normal distribution</strong> and the independent variables have <strong>a linear relationship(linearity)</strong> with the dependent variable, therefore, the line of best fit through the data points is straight and not curved.</p>
<p>Multiple linear regression is modeled by;-</p>
<p><img src="images/multiple_linear_regression.png" /></p>
<p>where;-</p>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(y\)</span> is the predicted value of the target variable.</li>
<li><span class="math inline">\(\beta_0\)</span> is the y-intercept. Value of y when all other parameters are zero.</li>
<li><span class="math inline">\(\beta_1X_1\)</span>: <span class="math inline">\(\beta_1\)</span> is the regression coefficient of the first independent variable while <span class="math inline">\(X_1\)</span> is the independent variable value.
<span class="math inline">\(\cdots\)</span> do the same for however the number of independent variables are present.</li>
<li><span class="math inline">\(\beta_nX_n\)</span>: the regression coefficient of the last independent variable.</li>
<li><span class="math inline">\(\epsilon\)</span> is the model error(variation not explained by the independent variables)</li>
</ol>
<p>The Multiple linear regression model calculates three things to find the best fit line for each independent variable;-</p>
<ol style="list-style-type: lower-roman">
<li>The regression coefficient <span class="math inline">\(\beta_iX_i\)</span> that will minimize the overall error rate(model error).</li>
<li>The associated p-value. If the relationship between the independent variable is statistically significant.</li>
<li>The t-statistic of the model. T-statistic is the ratio of the difference in a number’s estimated value from its assumed value to its standard error.</li>
</ol>
<p>——add an example ——————————</p>
<p>——Add Assumptions of Multiple Linear Regression———————-</p>
<p><span style="color: green;"><strong>Practical exercise</strong></span></p>
<p>Using the <code>airquality</code> data set, fit a multiple linear regression model whereby the Solar radiation(<code>Solar.R</code>), <code>Ozone</code> and <code>Wind</code> are the independent variables while the Temperature (<code>Temp</code>) is the dependent variable. Interpret and analyze the results</p>
</div>
<div id="hands-on-exercise-1" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> <span style="color: green;"><strong>Hands-on Exercise</strong></span><a href="linear-regression-analysis.html#hands-on-exercise-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this exercise, we will utilize the <strong>Global Species Abundance and Diversity</strong> data set that can be downloaded from <a href="">here</a>. It comprises of different species and diversity from different ecological sites, offering a global perspective on biodiversity</p>
<p>——————————————————————-Will be revisited ——————————————————–</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlation-covariance-geostatistics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conventional-and-probabilistic-risk-assessment.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/balsaedi/RCourse/edit/main/05-linear_regression_analysis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/balsaedi/RCourse/blob/main/05-linear_regression_analysis.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
