<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS | Ecological Analysis</title>
  <meta name="description" content="Chapter 3 TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS | Ecological Analysis" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS | Ecological Analysis" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS | Ecological Analysis" />
  
  
  

<meta name="author" content="Basim Alsaedi" />


<meta name="date" content="2024-11-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hypothesis-testing.html"/>
<link rel="next" href="correlation-covariance-geostatistics.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SHORT TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUCTION</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-distributions"><i class="fa fa-check"></i><b>1.1</b> Data Distributions</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#types-of-distribution"><i class="fa fa-check"></i><b>1.1.1</b> Types of Distribution</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#hands-on-exercises"><i class="fa fa-check"></i><b>1.2</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>2</b> HYPOTHESIS TESTING</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-tests"><i class="fa fa-check"></i><b>2.2</b> Parametric tests</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-single-sample-test"><i class="fa fa-check"></i><b>2.2.1</b> Parametric single-sample test</a></li>
<li class="chapter" data-level="2.2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-two-sample-test"><i class="fa fa-check"></i><b>2.2.2</b> Parametric two-sample test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-test"><i class="fa fa-check"></i><b>2.3</b> Nonparametric test</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-sample-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.1</b> Nonparametric One-Sample Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="2.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-two-sample-paired-sign-test-and-paired-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3.2</b> Nonparametric two-sample paired sign test and paired Wilcoxon Signed Rank Test</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-one-way-anova"><i class="fa fa-check"></i><b>2.4.1</b> Parametric One-Way ANOVA</a></li>
<li class="chapter" data-level="2.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nonparametric-one-way-anova-kruskal-wallis-test"><i class="fa fa-check"></i><b>2.4.2</b> Nonparametric One-Way ANOVA (Kruskal-Wallis Test)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hands-on-exercise"><i class="fa fa-check"></i><b>2.5</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html"><i class="fa fa-check"></i><b>3</b> TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS</a>
<ul>
<li class="chapter" data-level="3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#test-for-autocorrelation-using-the-sample-autocorrelation-function"><i class="fa fa-check"></i><b>3.1</b> Test for Autocorrelation Using the Sample Autocorrelation Function</a></li>
<li class="chapter" data-level="3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#an-example-on-site-wide-temporal-effects"><i class="fa fa-check"></i><b>3.2</b> An Example on Site-Wide Temporal Effects</a></li>
<li class="chapter" data-level="3.3" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#tests-for-trend"><i class="fa fa-check"></i><b>3.3</b> TESTS FOR TREND</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#parametric-test-for-trends---simple-linear-regression"><i class="fa fa-check"></i><b>3.3.1</b> Parametric Test for Trends - Simple Linear Regression</a></li>
<li class="chapter" data-level="3.3.2" data-path="test-for-autocorrelation-and-temporal-effects.html"><a href="test-for-autocorrelation-and-temporal-effects.html#nonparametric-test-for-trends"><i class="fa fa-check"></i><b>3.3.2</b> Nonparametric Test for Trends</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html"><i class="fa fa-check"></i><b>4</b> CORRELATION, COVARIANCE, GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> INTRODUCTION</a></li>
<li class="chapter" data-level="4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#correlation-and-covariance"><i class="fa fa-check"></i><b>4.2</b> CORRELATION AND COVARIANCE</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>4.2.1</b> Pearson’s Correlation Coefficient</a></li>
<li class="chapter" data-level="4.2.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#spearmans-and-kendalls-correlaton-coeefficients"><i class="fa fa-check"></i><b>4.2.2</b> Spearman’s and Kendall’s Correlaton Coeefficients</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#covariance"><i class="fa fa-check"></i><b>4.3</b> COVARIANCE</a></li>
<li class="chapter" data-level="4.4" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#geostatistics"><i class="fa fa-check"></i><b>4.4</b> GEOSTATISTICS</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#variogram-modelling"><i class="fa fa-check"></i><b>4.4.1</b> Variogram Modelling</a></li>
<li class="chapter" data-level="4.4.2" data-path="correlation-covariance-geostatistics.html"><a href="correlation-covariance-geostatistics.html#kriging"><i class="fa fa-check"></i><b>4.4.2</b> Kriging</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html"><i class="fa fa-check"></i><b>5</b> LINEAR REGRESSION ANALYSIS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#simple-linear-regression-analysis"><i class="fa fa-check"></i><b>5.1</b> Simple Linear Regression Analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#empirical-model-building-regression-analysis"><i class="fa fa-check"></i><b>5.1.1</b> Empirical model-building-regression analysis</a></li>
<li class="chapter" data-level="5.1.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#interpreting-the-regression-results"><i class="fa fa-check"></i><b>5.1.2</b> Interpreting the regression results</a></li>
<li class="chapter" data-level="5.1.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#r-squared-and-adjusted-r-squared"><i class="fa fa-check"></i><b>5.1.3</b> R-squared and Adjusted R-Squared</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-versus-generalized-linear-model"><i class="fa fa-check"></i><b>5.2</b> Data transformation versus generalized linear model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#data-transformation-approach-log-transformation"><i class="fa fa-check"></i><b>5.2.1</b> Data Transformation Approach (Log Transformation)</a></li>
<li class="chapter" data-level="5.2.2" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#generalized-linear-modelglm"><i class="fa fa-check"></i><b>5.2.2</b> Generalized Linear Model(GLM)</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#multiple-linear-regression-mlr-model"><i class="fa fa-check"></i><b>5.3</b> Multiple Linear Regression (MLR) model</a></li>
<li class="chapter" data-level="5.4" data-path="linear-regression-analysis.html"><a href="linear-regression-analysis.html#hands-on-exercise-1"><i class="fa fa-check"></i><b>5.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html"><i class="fa fa-check"></i><b>6</b> CONVENTIONAL AND PROBABILISTIC RISK ASSESSMENT</a>
<ul>
<li class="chapter" data-level="6.1" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#introduction-3"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#conventional-or-point-risk-estimation"><i class="fa fa-check"></i><b>6.2</b> Conventional or Point Risk Estimation</a></li>
<li class="chapter" data-level="6.3" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#probabilistic-risk-assessment-using-monte-carlo-simulation"><i class="fa fa-check"></i><b>6.3</b> Probabilistic Risk Assessment Using Monte Carlo Simulation</a></li>
<li class="chapter" data-level="6.4" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#practical-exercise"><i class="fa fa-check"></i><b>6.4</b> <span style="color: green;"><strong>Practical Exercise</strong></span></a></li>
<li class="chapter" data-level="6.5" data-path="conventional-and-probabilistic-risk-assessment.html"><a href="conventional-and-probabilistic-risk-assessment.html#hands-on-exercise-2"><i class="fa fa-check"></i><b>6.5</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>7</b> Datasets</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ecological Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="test-for-autocorrelation-and-temporal-effects" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> TEST FOR AUTOCORRELATION AND TEMPORAL EFFECTS<a href="test-for-autocorrelation-and-temporal-effects.html#test-for-autocorrelation-and-temporal-effects" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Environment Data is not always stable or stationary over time or space and is frequently subjected to sustained or cyclical change to the affecting factors. These concepts will help us understand the temporal effects better;</p>
<p><strong>Temporal Trends: </strong> refer to changes in a variable or phenomenon over time. Consider monitoring soil nitrogen levels in agricultural field over several years. There might be temporal rise of nitrogen immediately after application of nitrogen-based fertilizer and return back to almost the average state after time. Although there might be a general increase in soil nitrogen levels, but they won’t match the immediate spikes after fertilizer application.</p>
<p><strong>Autocorrelation</strong> or <strong>serial correlation: </strong> is the
correlation between data values of the same variable. <strong>Positive autocorrelation</strong> means that values close in time/space tend to be similar while <strong>negative autocorrelation</strong> means that they tend to differ.</p>
<p><strong>Monotonic trend: </strong> this is a trend that is in one direction, either constantly upward or downwards. A good example are the levels of carbon dioxide(CO2) concentrations in the atmosphere, they have been consistently rising due to industrial activities and deforestation.</p>
<p><strong>Cyclic or Seasonal trend</strong> refer to patterns that repeat at regular intervals such as daily ,hourly or annually. These trends are usually affected by natural cycles, human activities or climatic conditions. For instance, these trends are evident in phosphorous levels in water bodies that might increase during rainy seasons due agricultural runoff and decline during dry seasons.</p>
<p>When testing for autocorrelation and temporal effects the data samples are assumed to have values that are independent or uncorrelated, and identically or similarly distributed. The data are said to be <em>autocorrelated</em> or <em>serially correlated</em> when this assumption is violated.</p>
<p>These are the tests that are used to check for autocorrelation:</p>
<ul>
<li><p><em>Sample Autocorrelation Function(ACF): </em> used for a single time series where data is normally distributed.</p></li>
<li><p><em>Rank von Neumann ratio test</em> used when the data samples evidence of nonnormality.</p></li>
<li><p><em>The complete block design ANOVA or Friedman test</em> is used for multiple different data samples for instance testing the concentration of ground water contaminant from multiple monitoring wells at a site.</p></li>
</ul>
<div id="test-for-autocorrelation-using-the-sample-autocorrelation-function" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Test for Autocorrelation Using the Sample Autocorrelation Function<a href="test-for-autocorrelation-and-temporal-effects.html#test-for-autocorrelation-using-the-sample-autocorrelation-function" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before testing for autocorrelation using the ACF method, the data sample should be;</p>
<ul>
<li>normally distributed.</li>
<li>stationary(that is, not trending).</li>
<li>free of outliers.</li>
<li>containing atleast 10 to 12 observations.</li>
</ul>
<p>… And here is how ACf is computed.</p>
<ol style="list-style-type: decimal">
<li>Arrange the data in lagged data pairs (<span class="math inline">\(x_{i}, x_{i + k}\)</span>), for <span class="math inline">\(i\)</span> = 1, 2, ….(<span class="math inline">\(n-k\)</span>), where;</li>
</ol>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(n\)</span> is the size of the data samples(number of data values therein).</li>
<li><span class="math inline">\(k\)</span> is the lag. i.e number of sampling events dates separating one data value in the pair from the second value. For instance a lag of 1 shows that the two value pairs were collected in consecutive time intervals(e.g days) while lag shows that the data value pairs were collected every each time interval</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the sample Autocorrelation coefficient <span class="math display">\[r_k = {{\sum^{n-k}_{i=1}(x_i-x^!)(x_{i+k}- x^!)}\over{\sum^n_{i=1}(x_i - x^!)^2}}\]</span> where;</li>
</ol>
<ul>
<li><span class="math inline">\(n\)</span> is the data sample size.</li>
<li><span class="math inline">\(k\)</span> is the lag</li>
<li><span class="math inline">\(x^!\)</span> is the data sample mean</li>
<li><span class="math inline">\(x_{i}, x_{i + k}\)</span> are the components of the data pairs formed based on the lag.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li><p>If <span class="math inline">\(k\)</span> = 1, the sample autocorrelation coefﬁcient, <span class="math inline">\(r_1\)</span> is referred to as the ﬁrst order sample autocorrelation coefﬁcient. If <span class="math inline">\(k\)</span> = 2, <span class="math inline">\(r_2\)</span> is the second order coefﬁcient, and so on.</p></li>
<li><p>Lets breakdown the possible results of autocorrelation;</p></li>
</ol>
<ul>
<li><span class="math inline">\(r_0\)</span> = 1: Autocorrelation at lag 0 is always one because a value is perfectly correlated with itself.</li>
<li>Random Data: if the data is random, most autocorrelation coefficients will be close to zero, and will decrease further as the lag increases.</li>
<li>Autocorrelated Data: If there’s autocorrelation, some coefficients(<span class="math inline">\(r_k\)</span>) will be significantly larger than zero, but their strength decreases with higher lags.</li>
<li>Trend in data: If there is a trend, coefficients wont diminish, showing persistent correlation.</li>
</ul>
<p>As a summary, the normally distributed data, <span class="math inline">\(r_k\)</span> should be close to zero if there is no correlation. At a 95% confidence level, autocorrelation is insignificant if no <span class="math inline">\(r_k\)</span> exceeds the threshold <span class="math inline">\(2\over{\sqrt{n}}\)</span>. There result of each autocorrelation are therefore plotted in a correlogram and the confidence limits are show as the horizontal lines.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Climate and weather data are central to ecological research, helping us understand environmental trends and variability. In this exercise, you’ll examine whether daily temperature data from Melbourne exhibit autocorrelation over time. Autocorrelation indicates that today’s temperature might be correlated with yesterday’s, the day before, and so on. Detecting significant autocorrelation is important because it affects how we model and predict future climate patterns.</p>
<p>You are required to retrieve the <a href="https://www.kaggle.com/code/samfaraday/melbourne-daily-min-temperatures-eda">daily Temperature of Melbourne</a> and save it as a csv file.
Formulate the hypothesis;</p>
<ul>
<li><strong>Null hypothesis:</strong> The daily minimum temperature series is random(i.e there is no significant autocorrelation)</li>
<li><strong>Alternate hypothesis:</strong> The daily temperature time series exhibits significant autocorrelation (i.e., past values influence future values).</li>
</ul>
<p>Perform the analysis with R</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb115-1" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb115-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb115-2" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb115-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb115-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb115-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb115-4" tabindex="-1"></a></span>
<span id="cb115-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb115-5" tabindex="-1"></a><span class="co"># Load the data set</span></span>
<span id="cb115-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb115-6" tabindex="-1"></a>melbourne_temp <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/melboune-daily-temperature.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: One or more parsing issues, call `problems()` on
## your data frame for details, e.g.:
##   dat &lt;- vroom(...)
##   problems(dat)</code></pre>
<pre><code>## Rows: 3651 Columns: 2
## ── Column specification ─────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): Date, Daily minimum temperatures in Melbourne, Australia, 1981-1990
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb118-1" tabindex="-1"></a><span class="co"># Inspect the data structure</span></span>
<span id="cb118-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb118-2" tabindex="-1"></a><span class="fu">str</span>(melbourne_temp)</span></code></pre></div>
<pre><code>## spc_tbl_ [3,651 × 2] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ Date                                                         : chr [1:3651] &quot;1981-01-01&quot; &quot;1981-01-02&quot; &quot;1981-01-03&quot; &quot;1981-01-04&quot; ...
##  $ Daily minimum temperatures in Melbourne, Australia, 1981-1990: chr [1:3651] &quot;20.7&quot; &quot;17.9&quot; &quot;18.8&quot; &quot;14.6&quot; ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   Date = col_character(),
##   ..   `Daily minimum temperatures in Melbourne, Australia, 1981-1990` = col_character()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-1" tabindex="-1"></a><span class="co"># Convert the &#39;Date&#39; column to Date format.</span></span>
<span id="cb120-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-2" tabindex="-1"></a>melbourne_temp<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(melbourne_temp<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">&quot;%Y-%m-%d&quot;</span>)</span>
<span id="cb120-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-3" tabindex="-1"></a></span>
<span id="cb120-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-4" tabindex="-1"></a><span class="co"># Rename the temperature column</span></span>
<span id="cb120-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-5" tabindex="-1"></a><span class="fu">names</span>(melbourne_temp)[<span class="fu">names</span>(melbourne_temp) <span class="sc">==</span> <span class="st">&#39;Daily minimum temperatures in Melbourne, Australia, 1981-1990&#39;</span>] <span class="ot">&lt;-</span> <span class="st">&#39;Temperature&#39;</span></span>
<span id="cb120-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-6" tabindex="-1"></a></span>
<span id="cb120-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-7" tabindex="-1"></a><span class="co"># Convert to numeric </span></span>
<span id="cb120-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb120-8" tabindex="-1"></a>melbourne_temp <span class="ot">&lt;-</span> <span class="fu">transform</span>(melbourne_temp, <span class="at">Temperature =</span> <span class="fu">as.numeric</span>(Temperature))</span></code></pre></div>
<pre><code>## Warning in eval(substitute(list(...)), `_data`, parent.frame()): NAs introduced
## by coercion</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-1" tabindex="-1"></a><span class="co"># Remove rows with missing values </span></span>
<span id="cb122-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-2" tabindex="-1"></a>melbourne_temp <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(melbourne_temp)</span>
<span id="cb122-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-3" tabindex="-1"></a></span>
<span id="cb122-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-4" tabindex="-1"></a><span class="co"># Sort data by date if not already sorted</span></span>
<span id="cb122-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-5" tabindex="-1"></a>melbourne_temp <span class="ot">&lt;-</span> melbourne_temp[<span class="fu">order</span>(melbourne_temp<span class="sc">$</span>Date), ]</span>
<span id="cb122-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-6" tabindex="-1"></a></span>
<span id="cb122-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-7" tabindex="-1"></a><span class="co"># Create a time series object (assuming daily data; adjust the &#39;frequency&#39; parameter if needed)</span></span>
<span id="cb122-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-8" tabindex="-1"></a><span class="co"># Here, we assume the data is daily, so frequency = 365</span></span>
<span id="cb122-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-9" tabindex="-1"></a>temp_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(melbourne_temp<span class="sc">$</span>Temp, <span class="at">frequency =</span> <span class="dv">365</span>)</span>
<span id="cb122-10"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-10" tabindex="-1"></a></span>
<span id="cb122-11"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-11" tabindex="-1"></a><span class="co"># Plot the time series to visualize trends</span></span>
<span id="cb122-12"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-12" tabindex="-1"></a><span class="fu">plot</span>(temp_ts, <span class="at">main =</span> <span class="st">&quot;Daily Temperature Time Series (Melbourne)&quot;</span>,</span>
<span id="cb122-13"><a href="test-for-autocorrelation-and-temporal-effects.html#cb122-13" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Temperature (°C)&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb123-1" tabindex="-1"></a><span class="co"># Compute and plot the Sample Autocorrelation Function (ACF)</span></span>
<span id="cb123-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb123-2" tabindex="-1"></a><span class="fu">acf</span>(temp_ts, <span class="at">main =</span> <span class="st">&quot;ACF of Melbourne Daily Temperature&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-52-2.png" width="672" /></p>
<p>The results show the time series of daily temperature in Melbourne and its corresponding autocorrelation function (ACF). There is a cyclic trends in temperature over time and the ACF plot suggests strong autocorrelation at shorter lags, indicating a temporal dependency in the data.</p>
</div>
<div id="an-example-on-site-wide-temporal-effects" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> An Example on Site-Wide Temporal Effects<a href="test-for-autocorrelation-and-temporal-effects.html#an-example-on-site-wide-temporal-effects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Analysis of Site-Wide Temporal Effects on Groundwater Manganese Concentrations</strong></p>
<p>Generate the data</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-1" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb124-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb124-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-3" tabindex="-1"></a></span>
<span id="cb124-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-4" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb124-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb124-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-6" tabindex="-1"></a></span>
<span id="cb124-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-7" tabindex="-1"></a><span class="co"># Generate synthetic manganese concentration data</span></span>
<span id="cb124-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-8" tabindex="-1"></a>Mn_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">3.5</span>, <span class="fl">2.8</span>, <span class="fl">4.1</span>, <span class="fl">3.9</span>, <span class="fl">5.2</span>, <span class="fl">4.8</span>, <span class="fl">6.0</span>, <span class="fl">5.7</span>,  <span class="co"># Well 1</span></span>
<span id="cb124-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-9" tabindex="-1"></a>               <span class="fl">3.2</span>, <span class="fl">2.5</span>, <span class="fl">3.8</span>, <span class="fl">3.7</span>, <span class="fl">5.0</span>, <span class="fl">4.6</span>, <span class="fl">5.8</span>, <span class="fl">5.5</span>,  <span class="co"># Well 2</span></span>
<span id="cb124-10"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-10" tabindex="-1"></a>               <span class="fl">3.6</span>, <span class="fl">3.0</span>, <span class="fl">4.2</span>, <span class="fl">4.0</span>, <span class="fl">5.3</span>, <span class="fl">4.9</span>, <span class="fl">6.1</span>, <span class="fl">5.8</span>,  <span class="co"># Well 3</span></span>
<span id="cb124-11"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-11" tabindex="-1"></a>               <span class="fl">3.3</span>, <span class="fl">2.6</span>, <span class="fl">3.9</span>, <span class="fl">3.8</span>, <span class="fl">5.1</span>, <span class="fl">4.7</span>, <span class="fl">5.9</span>, <span class="fl">5.6</span>)  <span class="co"># Well 4</span></span>
<span id="cb124-12"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-12" tabindex="-1"></a></span>
<span id="cb124-13"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-13" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb124-14"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-14" tabindex="-1"></a>Mn2Data8 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb124-15"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-15" tabindex="-1"></a>  <span class="at">Mn =</span> Mn_values,</span>
<span id="cb124-16"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-16" tabindex="-1"></a>  <span class="at">Location =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Well1&quot;</span>, <span class="st">&quot;Well2&quot;</span>, <span class="st">&quot;Well3&quot;</span>, <span class="st">&quot;Well4&quot;</span>), <span class="at">each =</span> <span class="dv">8</span>),</span>
<span id="cb124-17"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-17" tabindex="-1"></a>  <span class="at">Time =</span> <span class="fu">rep</span>(<span class="fu">paste0</span>(<span class="st">&quot;Q&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>), <span class="at">times =</span> <span class="dv">4</span>)</span>
<span id="cb124-18"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-18" tabindex="-1"></a>)</span>
<span id="cb124-19"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-19" tabindex="-1"></a></span>
<span id="cb124-20"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-20" tabindex="-1"></a><span class="co"># Convert factors</span></span>
<span id="cb124-21"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-21" tabindex="-1"></a>Mn2Data8<span class="sc">$</span>Location <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Mn2Data8<span class="sc">$</span>Location)</span>
<span id="cb124-22"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-22" tabindex="-1"></a>Mn2Data8<span class="sc">$</span>Time <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Mn2Data8<span class="sc">$</span>Time)</span>
<span id="cb124-23"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-23" tabindex="-1"></a></span>
<span id="cb124-24"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-24" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb124-25"><a href="test-for-autocorrelation-and-temporal-effects.html#cb124-25" tabindex="-1"></a><span class="fu">head</span>(Mn2Data8)</span></code></pre></div>
<pre><code>##    Mn Location Time
## 1 3.5    Well1   Q1
## 2 2.8    Well1   Q2
## 3 4.1    Well1   Q3
## 4 3.9    Well1   Q4
## 5 5.2    Well1   Q5
## 6 4.8    Well1   Q6</code></pre>
<p>Groundwater manganese concentrations have been monitored quarterly across four wells for a period of two years (eight quarters). The data set above, 2009), includes measurements from each well per quarter. The goal is to determine whether there is a site-wide temporal trend in manganese concentrations over time.</p>
<p>To establish whether a time trend exists, we must first check for spatial variability among the four wells. If the manganese concentrations do not significantly differ across wells, we can then assess whether concentrations change over time.</p>
<p>Here is the process that will be followed;</p>
<ol style="list-style-type: decimal">
<li>Check for Spatial Variability (Homogeneity) by;</li>
</ol>
<ul>
<li>Testing whether the means or medians of the four well datasets are statistically equal.</li>
<li>Checking If the datasets show normality and homogeneity of variances, a two-way ANOVA without replication (Complete Block Design) is appropriate. Otherwise, the non-parametric Friedman test is used.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Check for Temporal Trends by;</li>
</ol>
<ul>
<li>Checking for a significant trend over time if no spatial variability is found.</li>
<li>A two-way ANOVA is performed again, switching the roles of <code>Time</code> and <code>Location</code> where initially <code>Time</code> was the factor of interest and <code>Location</code> as a blocking factor.</li>
</ul>
<p>The ANOVA model follows the equation:
<span class="math display">\[{Y_{ij}}={\mu + \alpha_i + \beta_j + \epsilon_{ij}}\]</span>
Where:</p>
<ul>
<li><span class="math inline">\(Y_{ij}\)</span> is the Manganese concentration</li>
<li><span class="math inline">\(\mu\)</span> is the overall mean</li>
<li><span class="math inline">\(\alpha_i\)</span> represents the effect of the well (location)</li>
<li><span class="math inline">\(\beta_j\)</span> represents the effect of time (quarter)</li>
<li><span class="math inline">\(\epsilon_{ij}\)</span> is the error term</li>
</ul>
<p>The hypothesis tests:</p>
<ul>
<li><strong>For spatial variability:</strong> <span class="math inline">\(H_0:\mu_1=\mu_2=\mu_3=\mu_4\)</span> (no significant difference between wells)</li>
<li><strong>For temporal trend</strong> <span class="math inline">\(H_0:\mu_{Q1}=\mu_{Q2}=...=\mu_{Q8}\)</span>(no significant difference across quarters)</li>
</ul>
<p>Check for variability</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb126-1" tabindex="-1"></a><span class="co"># Step 1: Check for Spatial Variability</span></span>
<span id="cb126-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb126-2" tabindex="-1"></a>Mn2.anova1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Mn <span class="sc">~</span> Location <span class="sc">+</span> Time, <span class="at">data =</span> Mn2Data8)</span>
<span id="cb126-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb126-3" tabindex="-1"></a><span class="fu">summary</span>(Mn2.anova1)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Location     3   0.57   0.189   125.5 1.44e-13 ***
## Time         7  35.63   5.091  3387.1  &lt; 2e-16 ***
## Residuals   21   0.03   0.002                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Results;</p>
<ul>
<li><strong>Location</strong>: p_value(denoted as Pr(&gt;F) on the table above) is less than 0.05 - therefore there is a significant spatial variability</li>
<li><strong>Time</strong>: p_value is less than 0.05 - there is a siginfant temporal trend.</li>
</ul>
<p>If there was no spatial variability we could have proceed to test the time trend. However, lets just proceed to show you how it is done.</p>
<p>Check the code below</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb128-1" tabindex="-1"></a><span class="co"># Step 2: Check for Temporal Effects</span></span>
<span id="cb128-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb128-2" tabindex="-1"></a>Mn2.anova2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Mn <span class="sc">~</span> Time <span class="sc">+</span> Location, <span class="at">data =</span> Mn2Data8)</span>
<span id="cb128-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb128-3" tabindex="-1"></a><span class="fu">summary</span>(Mn2.anova2)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Time         7  35.63   5.091  3387.1  &lt; 2e-16 ***
## Location     3   0.57   0.189   125.5 1.44e-13 ***
## Residuals   21   0.03   0.002                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>P-value is far much less than 0.05. The results confirm that manganese concentrations vary significantly over time.</p>
</div>
<div id="tests-for-trend" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> TESTS FOR TREND<a href="test-for-autocorrelation-and-temporal-effects.html#tests-for-trend" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When working with data that has a time component (i.e., data collected at different points in time), a time series plot is a useful first step in exploring whether the values are randomly distributed or if a trend or pattern exists. If the plot suggests a trend, the next step is to determine whether this trend is statistically significant or just a random occurrence.</p>
<p>To assess this, we can use parametric or nonparametric methods, depending on whether the data meets certain assumptions such as normality, absence of outliers, and constant variance.</p>
<ul>
<li><p><strong>Parametric methods</strong> assume that the data follows a specific distribution (usually normal). These methods rely on parameters like mean and variance. A common parametric approach for trend detection is <strong>simple linear regression</strong>.</p></li>
<li><p><strong>Nonparametric methods</strong> do not require the data to follow any particular distribution, making them more flexible. Two widely used nonparametric trend tests are:</p>
<ul>
<li><strong>The Mann-Kendall test</strong>, which determines whether a trend exists but does not measure its magnitude.</li>
<li><strong>The Theil-Sen method</strong>, which not only detects trends but also estimates the slope (rate of change) of the trend line.</li>
</ul></li>
</ul>
<p>In some cases, external factors like temperature or streamflow rate can influence the trend results. If these factors are not accounted for, they may lead to incorrect conclusions. Therefore, it is important to adjust for such variables before performing trend analysis.</p>
<div id="parametric-test-for-trends---simple-linear-regression" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Parametric Test for Trends - Simple Linear Regression<a href="test-for-autocorrelation-and-temporal-effects.html#parametric-test-for-trends---simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Simple linear regression is a commonly used parametric method for detecting trends over time. It involves plotting data against time and fitting a <strong>best-fit regression line</strong> to model the relationship.
The equation for this regression line is:
<span class="math display">\[Y_t = \beta_0 + \beta_1t + \epsilon_t\]</span>
Where:</p>
<ul>
<li><span class="math inline">\(Y_t\)</span> represents the observed data value at time <span class="math inline">\(t\)</span>(e.g., pollutant concentration, species population, or temperature).</li>
<li><span class="math inline">\(\beta_0\)</span> is the <strong>intercept</strong> (initial value at <span class="math inline">\(t=0\)</span>)</li>
<li><span class="math inline">\(\beta_1\)</span> is the <strong>slope coefficient</strong>, indicating the rate of change over time.</li>
<li><span class="math inline">\(\epsilon_t\)</span> represents random errors.</li>
</ul>
<p>A statistically significant <strong>positive slope</strong>(<span class="math inline">\(\beta_1&gt;0\)</span>) suggests an increasing trend, while a <strong>negative slope</strong>(<span class="math inline">\(\beta_1&lt;0\)</span>) indicates a declining trend.</p>
<p>To determine if the trend is significant, we set up the following hypotheses:</p>
<ul>
<li><strong>Null hypothesis</strong>(<span class="math inline">\(H_0\)</span>): There is no trend; the true slope is zero (<span class="math inline">\(\beta_1=0\)</span>).</li>
<li><strong>Alternative Hypothesis</strong> (<span class="math inline">\(H_a\)</span>): A trend exists; the slope is not zero (<span class="math inline">\(\beta_1≠0\)</span>).</li>
</ul>
<p>The <strong>t-test</strong> is used to check the significance of <span class="math inline">\(\beta_1\)</span>:
<span class="math display">\[{t} = {{\hat\beta_1}\over{SE(\hat\beta_1)}}\]</span>
Where <span class="math inline">\(\hat\beta_1\)</span> is the setimated slope and <span class="math inline">\(SE(\hat\beta_1)\)</span> is its standard error. The <strong>p-value</strong> associated with this test determines whether we reject <span class="math inline">\(H_0\)</span> at a given significance level <span class="math inline">\(\alpha\)</span> (typically 0.05)</p>
<p>Here are the assumptions must be satisfied for valid results;</p>
<ol style="list-style-type: decimal">
<li><strong>Linearity</strong>: The trend should be approximately linear.</li>
<li><strong>Independence</strong> : Observations should be independent over time.</li>
<li><strong>Normality of Residuals</strong>: The residuals (differences between actual and predicted values) should follow a normal distribution.</li>
<li><strong>Homoscedacity</strong>: Variance of residuals should be constant over time.</li>
<li><strong>Sufficient Data Points</strong>: At least 8–10 observations are recommended.</li>
</ol>
<p><span style="color: orange;"><strong>Try it!</strong></span>: <strong>Detecting Trends in River Nitrate Levels</strong></p>
<p>In ecological studies, trend analysis is often applied to environmental parameters such as nitrate concentration in rivers over time. The dataset below simulates nitrate levels (mg/L) measured monthly over several years.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb130-1" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb130-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb130-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb130-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb130-3" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-1" tabindex="-1"></a><span class="co"># Simulated ecological data: Nitrate levels in a river over time</span></span>
<span id="cb134-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb134-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-3" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">120</span>  <span class="co"># 10 years of monthly data</span></span>
<span id="cb134-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-4" tabindex="-1"></a>nitrate_levels <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.01</span> <span class="sc">*</span> time <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">120</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">0.2</span>)  <span class="co"># Simulated increasing trend</span></span>
<span id="cb134-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-5" tabindex="-1"></a></span>
<span id="cb134-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-6" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb134-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-7" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> time, <span class="at">nitrate =</span> nitrate_levels)</span>
<span id="cb134-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-8" tabindex="-1"></a></span>
<span id="cb134-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-9" tabindex="-1"></a><span class="co"># Fit linear regression model</span></span>
<span id="cb134-10"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-10" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(nitrate <span class="sc">~</span> time, <span class="at">data =</span> data)</span>
<span id="cb134-11"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-11" tabindex="-1"></a></span>
<span id="cb134-12"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-12" tabindex="-1"></a><span class="co"># Summary of the regression</span></span>
<span id="cb134-13"><a href="test-for-autocorrelation-and-temporal-effects.html#cb134-13" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = nitrate ~ time, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.60476 -0.12832  0.01333  0.12895  0.54269 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.0145997  0.0382374   52.69   &lt;2e-16 ***
## time        0.0098567  0.0005485   17.97   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2081 on 118 degrees of freedom
## Multiple R-squared:  0.7324, Adjusted R-squared:  0.7301 
## F-statistic:   323 on 1 and 118 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-1" tabindex="-1"></a><span class="co"># Extract p-value and slope</span></span>
<span id="cb136-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-2" tabindex="-1"></a>slope <span class="ot">&lt;-</span> <span class="fu">coef</span>(model)[<span class="dv">2</span>]</span>
<span id="cb136-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-3" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="dv">4</span>]</span>
<span id="cb136-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-4" tabindex="-1"></a></span>
<span id="cb136-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-5" tabindex="-1"></a><span class="co"># Decision based on p-value</span></span>
<span id="cb136-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-6" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb136-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-7" tabindex="-1"></a><span class="cf">if</span> (p_value <span class="sc">&lt;</span> alpha) {</span>
<span id="cb136-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-8" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Significant trend detected with slope:&quot;</span>, <span class="fu">round</span>(slope, <span class="dv">4</span>)))</span>
<span id="cb136-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-9" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb136-10"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-10" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;No significant trend detected.&quot;</span>)</span>
<span id="cb136-11"><a href="test-for-autocorrelation-and-temporal-effects.html#cb136-11" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;Significant trend detected with slope: 0.0099&quot;</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-1" tabindex="-1"></a><span class="co"># Plot the trend with regression line</span></span>
<span id="cb138-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-2" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> nitrate)) <span class="sc">+</span></span>
<span id="cb138-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb138-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb138-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Trend Analysis of Nitrate Levels in River&quot;</span>,</span>
<span id="cb138-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-6" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Time (Months)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Nitrate Concentration (mg/L)&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb138-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>Here is how we interpret the regression output:</p>
<ul>
<li><strong>Intercept</strong><span class="math inline">\((\beta_0)\)</span> = 2.0146 (baseline concentration)</li>
<li><strong>Slope</strong><span class="math inline">\(\beta_1\)</span> = 0.0099 (indicates an increasing trend in nitrate levels).</li>
<li><strong>p-value</strong>&lt;0.001 (significant trend detected).</li>
<li><strong>R-squared = 0.7324</strong>, meaning 73.2% of the variability in nitrate concentration is explained by time.</li>
</ul>
<p>This suggests that nitrate levels are increasing over time, which could indicate environmental pollution or agricultural runoff.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Using the Melbourne daily temperature(Used in Sample Autocorrelation Coeefficient Exercise), determine whether there is a statistically significant trend in temperature over time.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Formulate the hypotheses;</p>
<ul>
<li><strong>Null hypothesis</strong>: There is no significant trend in temperature over time.</li>
<li><strong>Alternate hypothesis</strong>: There is a significant increasing or decreasing trend in temperature over time.</li>
</ul>
<p>Here is the simple linear regression model;
<span class="math display">\[Temperatur = \beta_0 + \beta_1.Time + \epsilon\]</span>
where <span class="math inline">\(\beta_1\)</span> is the slope coefficient.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-1" tabindex="-1"></a><span class="co"># data set - melbourne_temp(reuse the variable name from the previous exercise)</span></span>
<span id="cb140-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-2" tabindex="-1"></a></span>
<span id="cb140-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-3" tabindex="-1"></a><span class="co"># Calculate time difference since the beginning </span></span>
<span id="cb140-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-4" tabindex="-1"></a>melbourne_temp<span class="sc">$</span>Time <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.Date</span>(melbourne_temp<span class="sc">$</span>Date) <span class="sc">-</span> <span class="fu">min</span>(<span class="fu">as.Date</span>(melbourne_temp<span class="sc">$</span>Date)))  <span class="co"># Convert Date to numerical</span></span>
<span id="cb140-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-5" tabindex="-1"></a></span>
<span id="cb140-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-6" tabindex="-1"></a><span class="co"># Visualize the time series </span></span>
<span id="cb140-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-7" tabindex="-1"></a><span class="fu">ggplot</span>(melbourne_temp, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Temperature)) <span class="sc">+</span></span>
<span id="cb140-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-8" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb140-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb140-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Daily Temperature Time Series (Melbourne)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Temperature (°C)&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb141-1" tabindex="-1"></a><span class="co"># Parametric Test for Trend: Linear Regression</span></span>
<span id="cb141-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb141-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Temperature <span class="sc">~</span> Time, <span class="at">data =</span> melbourne_temp)</span>
<span id="cb141-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb141-3" tabindex="-1"></a><span class="fu">summary</span>(model)  <span class="co"># Get regression output</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Temperature ~ Time, data = melbourne_temp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.1518  -2.8964  -0.1497   2.7674  15.1686 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.112e+01  1.345e-01  82.628   &lt;2e-16 ***
## Time        3.904e-05  6.380e-05   0.612    0.541    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.062 on 3645 degrees of freedom
## Multiple R-squared:  0.0001028,  Adjusted R-squared:  -0.0001716 
## F-statistic: 0.3746 on 1 and 3645 DF,  p-value: 0.5406</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb143-1" tabindex="-1"></a><span class="co"># Plot regression line</span></span>
<span id="cb143-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb143-2" tabindex="-1"></a><span class="fu">ggplot</span>(melbourne_temp, <span class="fu">aes</span>(<span class="at">x =</span> Time, <span class="at">y =</span> Temperature)) <span class="sc">+</span></span>
<span id="cb143-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb143-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb143-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb143-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb143-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb143-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Linear Trend in Melbourne&#39;s Temperature&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Temperature (°C)&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-57-2.png" width="672" /></p>
<p>The p-value(statistical significance) is 0.5406 which above 0.05, therefore the null hypothesis(<em>There is no significant trend in temperature over time</em>) is accepted. Furthermore the slope coefficient(<span class="math inline">\(\beta_1\)</span>) is <span class="math inline">\(3.904 \times 10^{-5}\)</span>(which is close to zero) suggests that temperature does not change significantly over time.</p>
<p>We can conclude that there is no change in temperature over time.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="nonparametric-test-for-trends" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Nonparametric Test for Trends<a href="test-for-autocorrelation-and-temporal-effects.html#nonparametric-test-for-trends" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="mannkendall-test-and-seasonal-mannkendall-test" class="section level4 hasAnchor" number="3.3.2.1">
<h4><span class="header-section-number">3.3.2.1</span> Mann–Kendall Test and Seasonal Mann–Kendall Test<a href="test-for-autocorrelation-and-temporal-effects.html#mannkendall-test-and-seasonal-mannkendall-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In ecological statistics, detecting trends in environmental data is crucial for understanding changes over time. However, traditional parametric tests such as linear regression require data to meet assumptions like normality and homoscedasticity, which are often violated in ecological datasets. Nonparametric tests like the <strong>Mann-Kendall (MK) test</strong> and <strong>Seasonal Mann-Kendall (SMK) test</strong> offer robust alternatives that do not assume any specific data distribution.</p>
<div id="mann-kendall-trend-test" class="section level5 hasAnchor" number="3.3.2.1.1">
<h5><span class="header-section-number">3.3.2.1.1</span> Mann-Kendall Trend Test<a href="test-for-autocorrelation-and-temporal-effects.html#mann-kendall-trend-test" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The Mann-Kendall test is a rank-based nonparametric test used to detect a monotonic trend in time-series data, whether linear or nonlinear.</p>
<p>Given a data set $ X = {x_1, x_2, …, x_n} $, the Mann-Kendall test examines all possible pairs $ x_i, x_j $ where $ i &lt; j $, and assigns a score based on their relative magnitudes:</p>
<p><span class="math display">\[S = \sum_{i=1}^{n-1} \sum_{j=i+1}^{n} \text{sgn}(x_j - x_i)\]</span></p>
<p>where the sign function is defined as:</p>
<p><span class="math display">\[\text{sgn}(x_j - x_i) =
\begin{cases}
+1, &amp; \text{if } x_j &gt; x_i \\
0, &amp; \text{if } x_j = x_i \\
-1, &amp; \text{if } x_j &lt; x_i
\end{cases}\]</span></p>
<p>A positive <span class="math inline">\(S\)</span> indicates an increasing trend, while a negative <span class="math inline">\(S\)</span> suggests a decreasing trend.</p>
<p>For large samples (<span class="math inline">\(n&gt;10\)</span>), the test statistic <span class="math inline">\(S\)</span> follows an approximately normal distribution with mean 0 and variance:</p>
<p><span class="math display">\[{Var(S)} = {{n(n-1)(2n-5)- \sum_t t(t-1)(2t+5)}\over{18}}\]</span>
Where t represents the number of tied ranks in the data set.</p>
<p>The standardized test statistic (Z-score) is given by:</p>
<p><span class="math display">\[{Z} =
\begin{cases}
{{s-1}\over{Var(S)}}, \text if \space S&gt;0\\
0,  \text if \space S = 0\\
{{s-1}\over{Var(S)}}, \text if \space S&lt;0
\end{cases}\]</span></p>
<p>Lets formulate the hypothesis;</p>
<ul>
<li><strong>Null hypothesis</strong>(<span class="math inline">\(H_0\)</span>): No trend in the data.</li>
<li><strong>Alternate Hypothesis</strong>(<span class="math inline">\(H_1\)</span>): Presence of a monotonic trend</li>
<li><strong>Decision Rule</strong>: Reject $H_0 if |Z|&gt;Z_{a/2} $ where <span class="math inline">\(Z_{a/2}\)</span> is the critical value from the normal distribution for a given significance level(e.g, 1.96 for <span class="math inline">\(\alpha = 0.05\)</span>)</li>
</ul>
<p><span style="color: orange;"><strong>Try it:</strong></span> <strong>Analysis for the monthly average temperature</strong></p>
<p>A package <code>trend</code> is needed for this practical and can be installed by;</p>
<pre><code>install.packages(&quot;trend&quot;)</code></pre>
<p>Run the analysis</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-1" tabindex="-1"></a><span class="fu">library</span>(trend)</span>
<span id="cb146-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-2" tabindex="-1"></a></span>
<span id="cb146-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-3" tabindex="-1"></a><span class="co"># Example dataset: Monthly average temperature</span></span>
<span id="cb146-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-4" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">12.4</span>, <span class="fl">12.8</span>, <span class="fl">13.1</span>, <span class="fl">12.9</span>, <span class="fl">13.5</span>, <span class="fl">13.7</span>, <span class="fl">13.9</span>, <span class="fl">14.0</span>, <span class="fl">14.1</span>, <span class="fl">14.5</span>, <span class="fl">14.8</span>, <span class="fl">15.0</span>)</span>
<span id="cb146-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-5" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">2000</span>, <span class="dv">2011</span>)</span>
<span id="cb146-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-6" tabindex="-1"></a></span>
<span id="cb146-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-7" tabindex="-1"></a><span class="co"># Perform Mann-Kendall Test</span></span>
<span id="cb146-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-8" tabindex="-1"></a>mk_result <span class="ot">&lt;-</span> <span class="fu">mk.test</span>(data)</span>
<span id="cb146-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb146-9" tabindex="-1"></a><span class="fu">print</span>(mk_result)</span></code></pre></div>
<pre><code>## 
##  Mann-Kendall trend test
## 
## data:  data
## z = 4.3201, n = 12, p-value = 1.56e-05
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##          S       varS        tau 
##  64.000000 212.666667   0.969697</code></pre>
</div>
<div id="seasonal-mann-kendall-smk-test" class="section level5 hasAnchor" number="3.3.2.1.2">
<h5><span class="header-section-number">3.3.2.1.2</span> Seasonal Mann-Kendall (SMK) Test<a href="test-for-autocorrelation-and-temporal-effects.html#seasonal-mann-kendall-smk-test" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Environmental data often exhibit <strong>seasonality</strong>, meaning the trend might be masked by cyclic variations. The <strong>Seasonal Mann-Kendall test</strong> adjusts for seasonality by performing the Mann-Kendall test on subsets of data corresponding to different seasons.</p>
<p>Here is how to perform it;</p>
<ol style="list-style-type: decimal">
<li><strong>Partition data</strong> into seasonal subsets (e.g, monthly data grouped by month across years)</li>
<li><strong>Apply the Mann-Kendall test</strong> to each seasonal subset/.</li>
<li><strong>Sum the S-values</strong> from each season to get an overall trend statistic</li>
</ol>
<p><span style="color: orange;"><strong>Try it!</strong></span> <strong>Monthly pollutant concentration across five years</strong></p>
<p>A package <code>Kendall</code> is required for this analysis and can be installed by;</p>
<pre><code>install.packages(&quot;Kendall&quot;)</code></pre>
<p>Run the analysis</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-1" tabindex="-1"></a><span class="co"># Load the library </span></span>
<span id="cb149-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-2" tabindex="-1"></a><span class="fu">library</span>(Kendall)</span>
<span id="cb149-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-3" tabindex="-1"></a></span>
<span id="cb149-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-4" tabindex="-1"></a><span class="co"># Example dataset: Monthly pollutant concentrations across 5 years</span></span>
<span id="cb149-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb149-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-6" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2010-01-01&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2014-12-01&quot;</span>), <span class="at">by=</span><span class="st">&quot;month&quot;</span>)</span>
<span id="cb149-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-7" tabindex="-1"></a>data_values <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(dates), <span class="at">mean=</span><span class="dv">50</span>, <span class="at">sd=</span><span class="dv">5</span>)</span>
<span id="cb149-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-8" tabindex="-1"></a>seasonal_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date=</span>dates, <span class="at">Value=</span>data_values)</span>
<span id="cb149-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-9" tabindex="-1"></a></span>
<span id="cb149-10"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-10" tabindex="-1"></a><span class="co"># Perform Seasonal Mann-Kendall Test</span></span>
<span id="cb149-11"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-11" tabindex="-1"></a><span class="co">#smk_result &lt;- SeasonalMannKendall(seasonal_data$Value ~ #as.POSIXlt(seasonal_data$Date)$mon + #as.POSIXlt(seasonal_data$Date)$year)</span></span>
<span id="cb149-12"><a href="test-for-autocorrelation-and-temporal-effects.html#cb149-12" tabindex="-1"></a><span class="co">#print(smk_result)</span></span></code></pre></div>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Using the Melbourne daily temperature data set, perform the following non-parametric tests to find if there is a significant trend in temperature over time;</p>
<ul>
<li><strong>Mann-Kendall Test</strong></li>
<li><strong>Seasonal Mann-Kendall Test</strong></li>
</ul>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ul>
<li><strong>Mann-Kendall Test</strong></li>
</ul>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb150-1" tabindex="-1"></a><span class="co"># Load the required library </span></span>
<span id="cb150-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb150-2" tabindex="-1"></a><span class="fu">library</span>(Kendall)</span>
<span id="cb150-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb150-3" tabindex="-1"></a></span>
<span id="cb150-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb150-4" tabindex="-1"></a><span class="co"># Perform the test</span></span>
<span id="cb150-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb150-5" tabindex="-1"></a>mk_test <span class="ot">&lt;-</span> <span class="fu">MannKendall</span>(melbourne_temp<span class="sc">$</span>Temperature)</span>
<span id="cb150-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb150-6" tabindex="-1"></a><span class="fu">print</span>(mk_test)</span></code></pre></div>
<pre><code>## tau = 0.0121, 2-sided pvalue =0.27545</code></pre>
<p><span class="math inline">\(\tau\)</span> = 0.0121 is small thus suggesting a slight increasing trend, though very weak. A value closer to -ve or +ve 1 would indicate a strong trend. The p-value is 0.27545(which is above 0.05) therefore we fail to reject the null hypothesis. This means <strong>there is no significant trend detected in the Melboourne</strong>. Lets try working on the <em>Seasonall Mann-Kendall Test.</em></p>
<ul>
<li><strong>Seasonal Mann-Kendall Test</strong></li>
</ul>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-1" tabindex="-1"></a><span class="co"># Install the package if not already installed</span></span>
<span id="cb152-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-2" tabindex="-1"></a><span class="co"># install.packages(&quot;trend&quot;)</span></span>
<span id="cb152-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-3" tabindex="-1"></a></span>
<span id="cb152-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-4" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb152-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-5" tabindex="-1"></a><span class="fu">library</span>(trend)</span>
<span id="cb152-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-6" tabindex="-1"></a></span>
<span id="cb152-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-7" tabindex="-1"></a><span class="co"># Convert data to time series format</span></span>
<span id="cb152-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-8" tabindex="-1"></a>melbourne_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(melbourne_temp<span class="sc">$</span>Temperature, <span class="at">frequency =</span> <span class="dv">365</span>) </span>
<span id="cb152-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-9" tabindex="-1"></a></span>
<span id="cb152-10"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-10" tabindex="-1"></a><span class="co"># Perform Seasonal Mann-Kendall Test</span></span>
<span id="cb152-11"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-11" tabindex="-1"></a>smk_test <span class="ot">&lt;-</span> <span class="fu">smk.test</span>(melbourne_ts)</span>
<span id="cb152-12"><a href="test-for-autocorrelation-and-temporal-effects.html#cb152-12" tabindex="-1"></a><span class="fu">print</span>(smk_test)</span></code></pre></div>
<pre><code>## 
##  Seasonal Mann-Kendall trend test (Hirsch-Slack test)
## 
## data:  melbourne_ts
## z = 2.8042, p-value = 0.005044
## alternative hypothesis: true S is not equal to 0
## sample estimates:
##        S     varS 
##   598.00 45324.67</code></pre>
<p>Alternatively, you can use the <code>Kendall</code> package</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-1" tabindex="-1"></a><span class="co"># install.packages(&quot;Kendall&quot;)</span></span>
<span id="cb154-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-2" tabindex="-1"></a><span class="fu">library</span>(Kendall)</span>
<span id="cb154-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-3" tabindex="-1"></a></span>
<span id="cb154-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-4" tabindex="-1"></a><span class="co"># Convert time into a time series object</span></span>
<span id="cb154-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-5" tabindex="-1"></a>melbourne_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(melbourne_temp<span class="sc">$</span>Temperature, <span class="at">frequency =</span> <span class="dv">365</span>)</span>
<span id="cb154-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-6" tabindex="-1"></a></span>
<span id="cb154-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-7" tabindex="-1"></a><span class="co"># Perform Seasonal Mann-Kendall Test</span></span>
<span id="cb154-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-8" tabindex="-1"></a>smk_test <span class="ot">&lt;-</span> <span class="fu">SeasonalMannKendall</span>(melbourne_ts)</span>
<span id="cb154-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb154-9" tabindex="-1"></a><span class="fu">print</span>(smk_test)</span></code></pre></div>
<pre><code>## tau = 0.0367, 2-sided pvalue =0.0049713</code></pre>
<p>After taking a closer looking using the Seasonal Mann-Kendall test we find that;</p>
<ul>
<li>The <strong>test statistic (z)</strong> = 2.802 – a positive value that suggests an increasing trend in temperature.</li>
<li>P-value of less than 0.05 – Meaning that we reject the null hypothesis.</li>
<li><strong>S (Mann-Kendall Statistic) </strong> = 598 – A positive S value further confirms an upward trend.</li>
</ul>
<p>It can be conclude that since <strong>p-value is low (p &lt; 0.05)</strong>, we reject the null hypothesis and conclude that there is a significant increasing trend in Melbourne’s temperature over time.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
<div id="theilsen-trend-test" class="section level4 hasAnchor" number="3.3.2.2">
<h4><span class="header-section-number">3.3.2.2</span> Theil–Sen Trend Test<a href="test-for-autocorrelation-and-temporal-effects.html#theilsen-trend-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When studying climate change, pollution levels, or species populations, scientists often need to determine whether a trend exists over time. The Theil-Sen estimator is a robust, nonparametric method for estimating trends, making it perfect for ecological data, where outliers and missing values (non-detects) are common!</p>
<p>Theil-sen is preferred since;</p>
<ul>
<li><strong>Robust to Outliers</strong> – Unlike least-squares regression, Theil-Sen takes the median of all slopes, making it resistant to extreme values.</li>
<li><strong>No Normality Assumptions</strong> – Works with non-normally distributed data (great for environmental datasets!).</li>
<li><strong>Handles Missing Data</strong> – Can be used with censored (non-detect) values using the <code>cenken()</code> function in R.</li>
</ul>
<p><span style="color: orange;"><strong>try it!</strong></span></p>
<p><strong>Analyzing Water Quality Trends</strong></p>
<p>In this exercise, we will analyze nitrate concentrations in a river over time to detect pollution trends. We will simulated data.</p>
<p>Lets break it down step by step</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb156-1" tabindex="-1"></a><span class="co"># Install required packages if not already installed</span></span>
<span id="cb156-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb156-2" tabindex="-1"></a><span class="co">#install.packages(&quot;NADA&quot;)  # For dealing with non-detects</span></span>
<span id="cb156-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb156-3" tabindex="-1"></a><span class="co">#install.packages(&quot;tidyverse&quot;)  # For data manipulation &amp; visualization</span></span>
<span id="cb156-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb156-4" tabindex="-1"></a></span>
<span id="cb156-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb156-5" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb156-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb156-6" tabindex="-1"></a><span class="fu">library</span>(NADA)  </span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;NADA&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     cor</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb159-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ────────────
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ lubridate 1.9.4     ✔ tibble    3.2.1
## ✔ purrr     1.0.2     ✔ tidyr     1.3.1</code></pre>
<pre><code>## ── Conflicts ─────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ✖ dplyr::select() masks MASS::select()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<ul>
<li>Simulate Nitrate Concentration Data</li>
</ul>
<p>Imagine we are monitoring nitrate levels (mg/L) in a river over 10 years (2010-2019). Some measurements were below the detection limit (<code>ND</code> = non-detects).</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-1" tabindex="-1"></a><span class="co"># Create a dataset of nitrate levels over time</span></span>
<span id="cb162-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb162-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-3" tabindex="-1"></a>  <span class="at">Year =</span> <span class="dv">2010</span><span class="sc">:</span><span class="dv">2019</span>,</span>
<span id="cb162-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-4" tabindex="-1"></a>  <span class="at">Nitrate =</span> <span class="fu">c</span>(<span class="fl">2.1</span>, <span class="fl">2.5</span>, <span class="fl">2.3</span>, <span class="fl">2.7</span>, <span class="fl">2.8</span>, <span class="fl">3.0</span>, <span class="fl">3.5</span>, <span class="fl">3.8</span>, <span class="cn">NA</span>, <span class="fl">4.2</span>),  <span class="co"># Some missing values</span></span>
<span id="cb162-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-5" tabindex="-1"></a>  <span class="at">Detection_Limit =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="cn">NA</span>)  <span class="co"># Limit for ND values</span></span>
<span id="cb162-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-6" tabindex="-1"></a>)</span>
<span id="cb162-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-7" tabindex="-1"></a></span>
<span id="cb162-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-8" tabindex="-1"></a><span class="co"># View data</span></span>
<span id="cb162-9"><a href="test-for-autocorrelation-and-temporal-effects.html#cb162-9" tabindex="-1"></a><span class="fu">print</span>(data)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##     Year Nitrate Detection_Limit
##    &lt;int&gt;   &lt;dbl&gt;           &lt;dbl&gt;
##  1  2010     2.1            NA  
##  2  2011     2.5            NA  
##  3  2012     2.3            NA  
##  4  2013     2.7            NA  
##  5  2014     2.8            NA  
##  6  2015     3              NA  
##  7  2016     3.5            NA  
##  8  2017     3.8             0.5
##  9  2018    NA               0.5
## 10  2019     4.2            NA</code></pre>
<p>Some values are missing (<code>NA</code>), and some are below the detection limit (<code>ND</code>).</p>
<ul>
<li>Perform the Theil-Sen Estimation</li>
</ul>
<p>To compute the trend, we use <code>cenken()</code>, which handles both detected and non-detect values.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-1" tabindex="-1"></a><span class="co"># Replace non-detects (NDs) with detection limits</span></span>
<span id="cb164-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-2" tabindex="-1"></a>data<span class="sc">$</span>Nitrate[<span class="fu">is.na</span>(data<span class="sc">$</span>Nitrate)] <span class="ot">&lt;-</span> data<span class="sc">$</span>Detection_Limit[<span class="fu">is.na</span>(data<span class="sc">$</span>Nitrate)]</span>
<span id="cb164-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-3" tabindex="-1"></a></span>
<span id="cb164-4"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-4" tabindex="-1"></a><span class="co"># Apply Theil-Sen estimator</span></span>
<span id="cb164-5"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-5" tabindex="-1"></a><span class="co">#result &lt;- cenken(Year, Nitrate, data = data)</span></span>
<span id="cb164-6"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-6" tabindex="-1"></a></span>
<span id="cb164-7"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-7" tabindex="-1"></a><span class="co"># Print result</span></span>
<span id="cb164-8"><a href="test-for-autocorrelation-and-temporal-effects.html#cb164-8" tabindex="-1"></a><span class="co">#print(result)</span></span></code></pre></div>
<p>Lets visualize the trend</p>
<pre><code># Extract slope and intercept
slope &lt;- result$coefficients[2]
intercept &lt;- result$coefficients[1]

# Create trend line equation
data &lt;- data %&gt;% 
  mutate(Predicted_Nitrate = intercept + slope * Year)

# Plot
ggplot(data, aes(x = Year, y = Nitrate)) +
  geom_point(color = &quot;blue&quot;, size = 3) +  # Actual data points
  geom_line(aes(y = Predicted_Nitrate), color = &quot;red&quot;, size = 1) +  # Theil-Sen trend
  labs(title = &quot;Trend of Nitrate Levels in River (2010-2019)&quot;,
       subtitle = paste(&quot;Slope:&quot;, round(slope, 3), &quot;mg/L per year&quot;),
       x = &quot;Year&quot;,
       y = &quot;Nitrate Concentration (mg/L)&quot;) +
  theme_minimal()</code></pre>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Finally, lets repeat the analysis(Melbourne daily temperature performed in the exercises earlier). Thjis time you will be required to perform the <strong>Theil-Sen Slope Estimator</strong>.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="test-for-autocorrelation-and-temporal-effects.html#cb166-1" tabindex="-1"></a><span class="co"># Perform the Theil-Sen Slope Estimator</span></span>
<span id="cb166-2"><a href="test-for-autocorrelation-and-temporal-effects.html#cb166-2" tabindex="-1"></a>theil_sen <span class="ot">&lt;-</span> <span class="fu">sens.slope</span>(melbourne_temp<span class="sc">$</span>Temperature)</span>
<span id="cb166-3"><a href="test-for-autocorrelation-and-temporal-effects.html#cb166-3" tabindex="-1"></a><span class="fu">print</span>(theil_sen)</span></code></pre></div>
<pre><code>## 
##  Sen&#39;s slope
## 
## data:  melbourne_temp$Temperature
## z = 1.0906, n = 3647, p-value = 0.2754
## alternative hypothesis: true z is not equal to 0
## 95 percent confidence interval:
##  -4.861449e-05  2.023472e-04
## sample estimates:
##  Sen&#39;s slope 
## 6.736275e-05</code></pre>
<p>The Theil-sen slope estimate = <span class="math inline">\(6.736 \times 10^{-5}\)</span> indicates a very small positive value that suggests a slight increasing trend. Contrary to the <strong>Seasonal Mann-Kendall</strong> test, the p-value = 0.2754(above 0.05) indicating that we fail to reject the null hypothesis and there is trend is not statistically significant.</p>
<p>Taking a closer look, the Seasonal Mann-Kendall found a significant trend while Theil-Sen test failed to find, this discrepancy might be due to;</p>
<ol style="list-style-type: decimal">
<li>Seasonal effects influencing the Mann-Kendall test but having less impact in the Theil-Sen slope.</li>
<li>High variance in temperature data, reducing the power of the Theil-Sen test.</li>
</ol>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hypothesis-testing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="correlation-covariance-geostatistics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/balsaedi/RCourse/edit/main/03-autocorrelation_and_temporal_effects_testing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/balsaedi/RCourse/blob/main/03-autocorrelation_and_temporal_effects_testing.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
